Algorithm-Squad/Algorithm

src/weekly1/ethan/leetCode/146_Permutations.ts
src/weekly1/ethan/leetCode/169_MajorityElement.ts
src/weekly1/ethan/leetCode/283_MoveZeroes.ts
src/weekly1/ethan/leetCode/35_SearchInsertPosition.ts
src/weekly1/ethan/leetCode/39_CombinationSum.ts

- 출처 : https://leetcode.com/problems/search-insert-position/ 
> Example 1
```js
Input : nums = [1, 3, 5, 6], target = 5
Output : 2
```
> Example 2
```js
Input: nums = [1,3,5,6], target = 2
Output: 1
```
> Example 3
```js
Input: nums = [1,3,5,6], target = 7
Output: 4
```
- 문제 및 풀이 설명
1. 정렬된 숫자 배열을 이용해 target이 들어가야할 인덱스 번호를 반환하는 문제로 입력 배열의 길이가 10,000 길이, 각 원소의 값 크기도 -10,000 ~ 10,000 사이로 들어와 복잡도를 신경 안써도 되는 듯 했으나 복잡도를 O(logn)을 요구사항이 주어져 효율성 측면에서도 고려해봐야하는 문제였습니다.
2. 각 원소를 순회하면서 그 원소의 타겟을 만나 대소 관계에서 크거나 작다는 조건에 부합하면 원소의 자릿수를 반환하게 해주었고, 원소 전체를 순회했을 때, 이 조건을 만족하지 못하면 원소의 끝자리에 들어가야하는 값으로 해서 그 원소의 최대 길이를 반환해 엣지 케이스를 처리했습니다.
---
- 출처 : https://leetcode.com/problems/majority-element/
> Example 1
```js
Output: 3
``` 
> Example 2
```js
Input: nums = [2,2,1,1,1,2,2]
Output: 2
```
- …

Ethan / 1월 1주차 / 5문제

---

src/weekly1/jace/leetCode/169_MajorityElement.js
src/weekly1/jace/leetCode/283_MoveZeroes.js

https://leetcode.com/problems/majority-element/
**Testcase**
```javascript
Output: 3
Input: nums = [2,2,1,1,1,2,2]
Output: 2
```
**문제 풀이 및 설명**
```javascript
const nums = [3, 2, 3];
// const nums = [2, 2, 1, 1, 1, 2, 2];
const majorityElement = (nums) => {
nums.sort(compareFunc);
return nums[Math.floor(nums.length / 2)];
};
const compareFunc = (a, b) => a - b;
console.log(majorityElement(nums));
```
1. 정수로 이루어진 배열 `nums`에서 가장 많이 중복되는 요소(Majority Element)는 최소한 배열 길이의 절반(`2/n`)만큼 중복되기 된다
2. 따라서 배열 `nums`를 정렬한 후 배열의 중간(median) 인덱스의 요소는 언제나 Majority Element가 된다
3. `sort()` 메서드는 배열의 요소들을 문자열로 취급하여 유니코드 값 순서대로 배열 요소들을 정렬하기 때문에, `sort()` 메서드의 매개변수로 `compareFunc`라는 숫자 타입을 올바로 오름차순 정렬해줄 함수를 전달한다
*** 
https://leetcode.com/problems/move-zeroes/
**Testcase**
```javascript
Input: …
```

Jace / 1월 1주차 / 2문제

---

src/weekly1/poco/leetCode/169_MajorityElement.js
src/weekly1/poco/leetCode/283_MoveZeroes.js
src/weekly1/poco/leetCode/46_Permutations.js

순열 알고리즘
순열은 조합과 달리 순서가 의미가 있다.
함수의 내용은 조합과 동일하나, index 요소를 선택하고 남은 배열을 재귀적 구현을 실행할 때, 해당 index의 다음 요소들을 검토하는 것이 아닌,
전체 배열에서 index 요소를 제외한 배열에 대해서 n-1개를 조합한다고 생각하자
재귀함수 return 조건은 주어진 배열에서 1개를 선택할 때이다.
---
숫자로 이루어진 길이 n의 배열에서 가장 많은 갯수의 요소를 return하라
가장 많은 갯수를 가진 요소는 배열의 길이의 절반 (2/n) 보다 더 많은 갯수를 갖는다
배열안에서 원하는 결과값은 과반수의 갯수를 가지고 있음.
즉, 오름차순 혹은 내림차순으로 정렬했을때, 배열의 중간인덱스의 값은 과반수가 넘는 요소
sort 매서드 정렬 시간복잡도 O(nlogn)
---
숫자로 이루어진 배열. 배열의 요소중에 숫자 0을 모두 배열의 마지막으로 옮긴다. 대신 0이 아닌 다른 숫자의 순서는 그대로 둔다.
배열을 새롭게 복사하지 않고, 원본 배열에서 이동시킨다. (즉, 새로운 배열을 생성하여 메모리를 할당하지 않는다)
nums 배열을 순회하면서, 배열의 요소가 0인 경우, 해당 요소 다음 요소부터 splice 매서드를 통해 배열 잘라내기(새로운 배열 생성 x) -> 
시간복잡도는??
nums 배열에 특정 문자 push
이후 nums 배열을 다시 순회하면서 특정문자인 경우 0으로 변경.
시간복잡도 배열 2회 순회 O(n^2)

Poco / 1주차 / 4문제

---

src/weekly1/nanii/leetCode/169_MajorityElement.js
src/weekly1/nanii/leetCode/283_MoveZeroes.js
src/weekly1/nanii/leetCode/35_SearchInsertPosition.js
src/weekly1/nanii/leetCode/39_CombinationSum.js

https://leetcode.com/problems/search-insert-position/
**Testcase**
```js
Input : nums = [1, 3, 5, 6], target = 5
Output : 2
```
```js
Input: nums = [1,3,5,6], target = 2
Output: 1
```
```js
Input: nums = [1,3,5,6], target = 7
Output: 4
```
**문제 풀이 및 설명**
1. 타겟이 위치한 인덱스를 이동시키면서 배열을 순회하고 싶었지만 그렇게 되면 시간 복잡도가 O(n)이 되기때문에 이를 위해 이진탐색방법을 활용하였습니다.
2. ` const mid = start + Math.floor((end - start)/ 2)` 배열 중간 인덱스를 이용합니다.
3. 중간값이 타겟값보다 클 경우 배열의 중간에서 end 인덱스의 위치를 -1 줄이고, 중간값이 타겟값보다 작을 경우 start 인덱스의 위치를 +1 증가시키며 값을 비교하며 타겟의 인덱스를 탐색합니다.
---------------
https://leetcode.com/problems/majority-element/
**Testcase**
```js
Output: 3
```
```js
Input: nums = [2,2,1,1,1,2,2]
Output: 2
```
**문제 풀이 및 설명**
1. 문제를 보는 순간 배열요소를 key, 중복되는 횟수를 value 로 지정하여 Map 객체를 만들고 싶었지만,,Map객체의 value 수정방안이 생각이 …

Nanii / 1월 1주차 / 4문제

---

src/weekly2/ethan/leetCode/20_ValidParentheses.ts
src/weekly2/ethan/leetCode/49_GroupAnagrams.ts
src/weekly2/ethan/programmers/신규아이디추천.ts

- 출처 : [Leet Code - 20](https://leetcode.com/problems/valid-parentheses/)
> Example 1
```sh
Input: s = "()"
Output: true
```
> Example 2
```sh
Input: s = "()[]{}"
Output: true
```
> Example 3
```sh
Input: s = "(]"
Output: false
```
이 문제는 문자열에 대해 괄호의 갯수와 짝이 일치하는지 확인하는 문제 입니다. 정해진 개수란 짝에 대해 비교하기 위해 괄호 갯수가 알맞게 있는지를 물어보는 것이고, 짝이 일치한다는 것은 열린 소괄호`(`는 닫힌 소괄호`)`와 맞아야하고, 열린 중괄호 `{`는 닫힌 중괄호 `}`와 맞는 식으로 소/중/대 괄호의 짝을 맞춰야한다는 의미 입니다. 여기서 또 열린 괄호가 온 다음에 닫힌 괄호가 와야하며, 닫힌 괄호가 먼저 오는 경우에는 짝이 맞는 것이 아니라고 이해했습니다.
- 입력되는 문자열의 길이는 1부터 10,000 길이로 들어오기 때문에 1개의 괄호만 들어왔을 때에 대한 것을 처리해야할 필요가 있다고 생각했고, 괄호에 대한 짝을 맞추는 문제는 스택 자료구조가 적합하다고 판단해서, 대체할 수 있는 배열을 스택처럼 사용해서 문제를 해결했습니다.
- 문자열의 각 문자를 탐색하면서 `(`, `{`, `[` 중 열린 괄호를 만나면 스택에 그 괄호와 상대되는 닫힌 괄호 문자를 스택에 넣었습니다.
- 만약 여기서 열린 괄호가 아닌 닫힌 괄호를 만났을 때, 스택에 있는 괄호를 빼면서 일치하는지 비교하고, 만약 …

Ethan / 2 주차 / 3 문제

---

src/weekly2/nanii/leetCode/20_ValidParentheses.js
src/weekly2/nanii/leetCode/49_GroupAnagrams.js
src/weekly2/nanii/programmers/신규아이디추천_Lv1[Array].js
src/weekly2/nanii/programmers/신규아이디추천_Lv1[String].js

- 출처 : [Leet Code - 20](https://leetcode.com/problems/valid-parentheses/)
> Example 1
```
Input: s = "()"
Output: true
```
> Example 2
```
Input: s = "()[]{}"
Output: true
```
> Example 3
```
Input: s = "(]"
Output: false
```
- 괄호문제하면 스택처럼 한방향에서 입출력이 되어야하므로 배열의 push, pop메서드를 사용했습니다.
- 경우의 수가 `'{' , '[' , '(', '}' , ']' , ')'` 으로 총 6가지라고 생각하여 switch문을 사용했습니다. (추후 굳이 6가지로 생각하지 않고 쌍으로 생각하면 더 짧게 작성가능하다는 걸 깨달았습니다)
- string을 순회하면서  `'{' , '[' , '('` 이면 push 하고 `'}' , ']' , ')'`이면 해당 배열의 마지막 요소가 짝이 맞는 지 확인하고 pop을 하면서 짝이 잘 맞으면 빈 배열을 반환합니다.
- 예외케이스 `s = "]"` push를 아예 진행하지 않았을 경우의 예외처리를 위해 `type.length !== 0`조건을 추가하였습니다.
- 출처 : [Leet Code - 49](https://leetcode.com/problems/group-anagrams/)
> Example 1
```
Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: …
```

Nanii / 2주차 / 3문제

---

src/weekly2/den/leetcode/20_ValidParentheses.js
src/weekly2/den/leetcode/49_GroupAnagrams.js
src/weekly2/den/programmers/신규아이디추천.js

- 출처 : [LeeCode - 20](https://leetcode.com/problems/valid-parentheses/)
> Example 1
```js
Input: s = "{[]}"
output: true
```
> Example 2
```js
Input: s = "[{(}])"
output: false
```
여는 괄호와 닫는 괄호가 순서에 맞게 나열되어 있는지 확인하는 작업을 진행하는 함수를 만들었습니다.  
그러기 위해서 빈 배열을 하나 만들어 스택의 형태로 for문을 이용해서 여는 괄호를 만날 때마다 같은 형태의 닫는 괄호를 빈 배열에 쌓아 놓고, 닫는 괄호를 만나면 스택의 최상단 요소를 꺼내와 비교해서 같은 종류의 괄호가 맞는지 확인하는 작업을 했습니다.
1. 스택 형태로 관리할 빈 배열을 생성.
2. for문을 이용해 input 배열 요소들을 확인.
3. 여는 배열 `( , { , [` 을 만나면, 같은 종류의 닫는 배열 `) , } , ]`을 배열에 push.
4. 닫는 배열 `) , } , ]`을 만나면, pop을 이용해 스택의 최상단 요소를 가져와 비교.
- 만약 스택에 요소가 없으면 바로 false를 리턴
- 스택에서 가져온 요소와 닫는 요소가 같지 않다면 false 리턴
5. for문의 조건을 모두 통과하고 for문이 끝났다면, input 배열의 괄호들이 모두 순서에 맞게 나열되어 있다는 것을 의미함으로, true를 리턴.  
---
- 출처 : [LeeCode - 49](https://leetcode.com/problems/group-anagrams/description/) …

Den / 2주차 / 3문제

---

src/weekly2/litae/leetCode/20_ValidParentheses.js
src/weekly2/litae/leetCode/49_GroupAnagrams.js
src/weekly2/litae/programmers/2021kakao_RecommendNewID.js

litae / 2주차 / 3문제

---

src/weekly3/den/baekjoon/일곱난쟁이.js
src/weekly3/den/programmers/모음사전.js

- 출처 : [Baekjoon - 2309](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
> Example 1
```js
Input : 20 7 23 19 10 15 25 8 13
Output : 7 8 10 13 19 20 23
```
9명의 난쟁이 중 7명의 난쟁이를 뽑아서 이들의 키의 합이 100인 상황을 찾아야 된다고 이해했습니다. 그래서 9명의 난쟁이들 중 2명의 키의 합이, 9명의 키의 합에서 100을 뺀 값과 같은 경우를 찾는 로직을 2중for문을 사용해 구현했습니다.
---
- 출처 : [Programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
> Example 1
```js
Input: numbers = "EA"
Output: 782
```
> Example 2
```js
Input: numbers = "EIO"
Output: 1189
```
사전에 등록되어 있는 단어들의 알파벳 구성이 A,E,I,O,U이고 단어의 길이가 최대 5인 상황에서 단어들을 직접 나열해보면서 어떤 패턴이 있을지 파악했습니다. 알파벳이 몇 번째 자리에 있는지에 따라 그리고 어떤 알파벳이냐에 따라서 변화하는 패턴을 찾았고, 그 패턴을 로직에 반영해 구현했습니다.
---
- 출처 : [Programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/42839)
> Example 1 …

Den / 3주차 / 2문제

---

src/weekly3/ethan/boj/2309_일곱난쟁이.js
src/weekly3/ethan/programmers/모음사전.ts
src/weekly3/ethan/programmers/소수찾기.ts

- 출처 : https://www.acmicpc.net/problem/2309
> Example 1
```sh
Input: 20 7 23 19 10 15 25 8 13
Output: 7 8 10 13 19 20 23
```
- 아홉 개의 줄을 걸쳐 난쟁이에 대한 키 값이 주어지고, 각 키는 100을 넘지 않는 자연수로 제공됩니다
- 여기서 일곱 난쟁이의 키의 총 합이 100이며, 이 조건을 만족하는 난쟁이의 키를 출력하는 문제입니다.
- 각 난쟁이들의 키는 모두 다르며, 가능한 정답이 여러가지의 경우에는 아무거나 출력합니다. (단, 오름차순으로 출력)
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/84512
> Example 1
```sh
Input: word = "AAAAE"
Output: 6
```
> Example 2
```sh
Input: word = "AAAE"
Output: 10
```
> Example 3
```sh
Input: word = "I"
Output: 1563
```
> Example 4
```sh
Input: word = "EIO"
Output: 1189
```
- 문자열 하나가 입력으로 주어지고, 이 단어가 사전에서 몇 번째 단어인지 반환하는 문제입니다.
- 알파벳 모음 'A', 'E', 'I', 'O', 'U'만 사용하여 만들 수 있는, 길이 5이하의 모든 단어에 대해
사전에 첫 단어는 "A"이고, 그 다음은 "AA", 마지막 단어는 "UUUUU"로 구성된 사전이 제공됩니다.
---
- 출처 : …

Ethan / 3주차 / 3 문제

---

src/weekly3/poco/BOJ/일곱난쟁이.js
src/weekly3/poco/programmers/소수찾기.js

1. 주어진 9개의 숫자중에, 합하여 100을 만들수 있는 7개의 숫자를 오름차순으로 출력하는 문제.
2. 즉, 9개의 숫자 중에 2개의 숫자를 제외해야하고, 이 2개의 숫자의 합은 9개의 숫자의 합에서 100을 뺀 수와 같다.
3. 따라서, 9개의 숫자를 모두 더한 값(sum)을 구하고, sum과 100과의 차이와 같은 2개 숫자의 합을 이중 for문을 통해서 구해서 배열 
(exception)에 담았고, input의 요소 중 exception의 요소와 일치하지 않는 숫자들만 출력하였다.
시간복잡도는 이중 for문 사용으로 O(n^2) 메모리 9340 KB, 시간 120ms
---
1. 문자열 numbers의 각 자리의 숫자들을 순서 있게 조합해서 만들 수 있는 모든 숫자를 구한다(permutation)
1-1. 순서 있는 조합(순열)을 구하기 위해 배열과 조합할 숫자의 갯수를 매개변수로 하는 permute 함수를 작성한다.
1-2. 문제에서 주어진 numbers는 문자열이기 때문에, split 매서드를 통해 각 숫자를 요소로 갖는 배열을 만들고,
1개 ~ 해당 배열의 길이까지의 순서있는 조합을 찾는다.
2. 조합된 수가 소수인지 판별하고 소수들을 배열에 담고, 배열의 길이를 최종 출력한다
2-1. 소수 판별의 경우, 2부터 n의 제곱근까지 수를 나눠서 나머지가 0인 경우가 발생하면 합성수에 해당한다.

Poco / 3주차 / 2문제

---

src/weekly3/litae/baekjoon/2309_TheSevenDwarfs.js
src/weekly3/litae/programmers/완전탐색_SearchPrime.js

- 출처 : [(링크)](https://school.programmers.co.kr/learn/courses/30/lessons/42839)
- 소수인지 여부를 확인하는 함수 isPrime
- 순열을 통해 모든 경우의 수를 확인하는 함수 mergeNumbers
- 출처 : [(링크)](https://www.acmicpc.net/problem/2309)
- 난쟁이 9명의 몸무게의 합을 구한 다음 진짜 일곱 난쟁이 몸무게의 합인 100과의 차를 구한다
- 가짜 난쟁이 2명의 몸무게 합이 위의 차와 같다

litae / 3주차 / 2문제

---

src/weekly4/nanii/baekjoon/1914_하노이탑.js
src/weekly4/nanii/leetCode/509_FibonacciNumber.js
src/weekly4/nanii/programmers/콜라문제.js

- 출처 : [Leetcode - 509](https://leetcode.com/problems/fibonacci-number)
> Example 1
```js
Input: n = 2
Output: 1
```
> Example 2
```js
Input: n = 3
Output: 2
```
> Example 3
```js
Input: n = 4
Output: 3
```
주어진 예시의 `F(0) = 0, F(1) = 1, F(n) = F(n - 1) + F(n - 2)`을 코드로 써봤는데 바로 풀렸습니다.
피보나치수열 : 앞 두개 항목의 합이 다음 항목의 값이 되는 수열
--------
- 출처 : [programmers - 콜라문제](https://school.programmers.co.kr/learn/courses/30/lessons/132267)
> Example 1
```js
Input: a = 2, b = 1, n = 20
Output: 19
```
> Example 2
```js
Input: a = 3, b = 1, n = 20
Output: 9
```
얻은 콜라의 갯수는 n을 a로 나눈 몫에 b를 곱한 값이고, 그 다음 n은 얻은 콜라에 n를 a 로 나눈 나머지를 더한 값임을 이용하면서
더이상 a로 나누어 지지 않을 때까지 반복하여 값을 구하는 문제입니다.
----- 
- 출처 : [baekjoon - 1914](https://www.acmicpc.net/problem/1914)
> Example 1
```js
Input: 3
Output: 7
1 3
1 2
3 2
1 3
2 1
2 3
1 3 …
```

Nanii / 4주차 / 2.5문제

---

src/weekly4/litae/leetcode/509_ FibonacciNumber.js
src/weekly4/litae/programmers/Cola.js

- 출처 : [Leetcode 509](https://leetcode.com/problems/fibonacci-number/)
> Example 1
```
Input: n = 2
Output: 1
```
> Example 2
```
Input: n = 3
Output: 2
```
> Example 3
```
Input: n = 4
Output: 3
```
조건문을 사용하여 F(0)일 경우 0, F(1)일 경우 1일을 리턴하고, 1보다 큰 n의 경우 F(n - 1) + F(n - 2)를 리턴하도록 하였습니다.
</br>
</br>
</br>
- 출처 : [Programmers 콜라 문제](https://school.programmers.co.kr/learn/courses/30/lessons/132267)
> Example 1
```
a | b | n | result
-- | -- | -- | --
2 | 1 | 20 | 19
3 | 1 | 20 | 9
```
빈 병의 개수에서 새 콜라로 교환되는 기준을 나눈 후 교환비(b)를 곱해준다. 소수점이 나올 경우(나누어 떨어지지 않는 경우) 교환이 성립되지 않기 때문에 Math.floor를 사용하여 내림해준다. 남은 빈 병의 수를 교환되고 남은 빈 병의 수와 새로 생길 수 있는 빈 병의 수(교환된 콜라의 수)를 더한 값이 다시 남은 빈 병의 개수가 된다. 이를 반복문을 사용하여 빈 병의 개수(n)가 새 콜라로 교환되는 빈 병의 수(a)보다 작아질 때까지(더이상 새 콜라로 교환이 되지 않을 때까지) 실행되도록 한다.

litae / 1월 4주차 / 2문제

---

src/weekly4/poco/leetCode/509_FibonacciNumber.js
src/weekly4/poco/programmers/콜라문제_Lv1.js

- 출처 : https://leetcode.com/problems/fibonacci-number/
숫자 n이 주어졌을때, F(N)의 결과값은 F(N-1) + F(N-2)이다.
F(1) = 1, F(0) = 0일때, 위의 조건을 만족하는 함수를 만드는 문제
피보나치 수열 문제로, 재귀적 방법을 활용하였고, 값이 주어진 F(1), F(0)을 종료조건으로 설정.
예를들어 F(5)를 구한다고 가정했을 때, F(5)는 F(4) + F(3)이다.
다시 F(4) = F(3) + F(2) / F(3) = F(2) + F(1) / F(2) = F(1) + F(0).... 방식으로 해결
---
- 출처 :https://school.programmers.co.kr/learn/courses/30/lessons/132267
빈병 n개를 가지고 있고, a개 만큼 b개의 새로운 콜라로 바꿔준다고 했을 때, 최종적으로 받을 수 있는 새로운 콜라 병의 갯수를 구하는 문제.
재귀(recursion)을 연습 및 사용하도록 문제에 접근하였고, 재귀를 종료시키기 위한 조건은 빈병이 a개보다 작을 때로 설정.
빈병 n개를 a개로 나누었을 때 몫에 b를 곱한만큼 새로운 병을 얻을 수 있고, 빈병 n개가 a보다 큰 경우
새로운 콜라를 얻는 과정을 반복하기 위해, 빈병의 갯수는 새롭게 얻는 병의 수(+ 빈병 n개가 a로 나누어떨어지지 않는 경우의 나머지)를
매개변수로하는 solution 함수를 호출함.

Poco / 4주차 / 2문제

---

src/weekly5/den/programmers/K번째수.js
src/weekly5/den/programmers/가장큰수.js

- 출처 : (Programmers - Lv. 1)[https://school.programmers.co.kr/learn/courses/30/lessons/42748]
> Example 1
```js
Input: (array, commands) = ([1, 5, 2, 6, 3, 7, 4], [2, 5, 3], [4, 4, 1], [1, 7, 3])
Output: [5, 6, 3]
```
문제에서 요구한대로,
1. input 배열에서 i번째 부터 j번째 까지의 숫자들을 자르기 위해서, slice를 이용해 새로운 배열을 만들었습니다.
2. 새로운 배열을 오름차순 정렬하기 위해 sort를 사용했습니다.
3. 마지막으로 새로운 배열에서 K번째 요소를 꺼내와서 answer 배열에 push해서, 최종적으로 answer를 반환했습니다.
---
- 출처 : (Programmers - Lv. 2)[https://school.programmers.co.kr/learn/courses/30/lessons/42746]
> Example 1
```js
Input: [6, 10, 2]
Output: "6210"
```
> Example 2
```js
Input: [3, 30, 34, 5, 9]
Output: "9534330"
```
1. 우선 Input으로 들어온 배열의 각각의 숫자들을 크기 비교하기 위해 1000 단위로 변환했습니다.
- 10보다 작으면: ex. 9일 때 -> 9999.1
- 9보다 크고 100보다 작을 때: ex. 98일 때 -> 9898.2
- 99보다 크고 1000보다 작을 때: ex. 987일 때 -> …

Den / 5주차 / 2문제

---

src/weekly5/leetCode/300_Longest IncreasingSubsequence.js
src/weekly5/programmers/K번째수.js
src/weekly5/programmers/가장큰수.js

- 출처 : [programmers](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
> Example 1
```js
Input : arr = [1, 5, 2, 60, 3, 7, 4]
commands = [[2, 5, 3], [4, 4, 1], [1, 7, 3]]
Output : [5, 6, 3]
```
문제 순서대로 array.slice() 메소드를 이용하여 배열을 자른 후, array.sort() 메소드를 이용하여 오름차순으로 정렬하고 해당 인덱스에 위치한 값을 array.at() 메소드를 사용하여 반환합니다.
--------
- 출처 : [programmers](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
> Example 1
```js
Input : numbers = [6, 10, 2]
Output : "6210"
```
> Example 2
```js
Input : numbers = [3, 30, 34, 5, 9]
Output : "9534330"
```
배열의 요소를 비교하여 내림차순으로 정렬하는데 이때 문자열로 연결한 두 수를 비교해야하므로 
array.sort()메소드를 활용하여 (a, b) 매개변수를 받아 a+b, b+a를 서로 비교합니다.
내림 차순으로 정렬을 위해 (b+a)-(a+b)를 비교하여 생성한 배열의 요소를 join()메소드를 사용하여 연결합니다.
--------
- 출처 : [Leetcode - 300]( …

Nanii / 5주차 / 2.5문제

---

src/weekly5/poco/leetCode/300_LongestIncreasingSubsequence.js
src/weekly5/poco/programmers/K번째수.js
src/weekly5/poco/programmers/가장큰수.js

- 출처 : https://leetcode.com/problems/longest-increasing-subsequence
문제 설명 및 해결
정수로 이루어진 배열에서 연속적으로 증가하는 숫자 배열의 길이를 구하는 문제
for 루프를 통해 주어진 배열을 순회하였고, result 배열이 비어있는 경우(= nums 배열의 첫번째 인자)
result 배열에 push를 해주었고, nums 배열의 이후 인자들은 result 배열의 마지막 인자와 값을 비교하여
마지막 인자보다 큰 경우, 바로 push를 해주었고, 반대의 경우, while문을 통해 해당 값이 위치할 인덱스를 찾아서
result 배열에 위치시킨다. 예를 들어 result 배열 = [10], 현재 비교값이 9 인 경우,
result 배열은 결과적으로 [9]가 되어야하기 때문에, result[0] = 9 로 변경.
다음 result 배열 [2, 5], 현재 값 3 인 경우, result 배열은 [2, 3]이 되어야 하기 때문에,
5의 위치(result[1])에 3을 넣어주는 방식으로 문제 해결.
시간복잡도 O(nlogn 또는 n^2)예상...
runtime 62ms, memory 42MB
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/42746
문제설명 및 해결
0 또는 양의 정수로 이루어진 배열이 주어지고, 배열의 숫자들을 이어 붙여 만들 수 있는 가장 큰 수를 리던하는 문제
예를 들어, [6, 10, 2] 인 경우, 이어 붙여서 만들 수 있는 가장 큰 수는 "6210"(출력형식은 …

Poco / 5주차 / 3문제

---

src/weekly5/programmers/theK-thNumber.js
src/weekly5/programmers/theLargestNumber.js

- 출처 : (프로그래머스 K번째 수)[https://school.programmers.co.kr/learn/courses/30/lessons/42748]
> Example 1
```js
Input : arr = [1, 5, 2, 60, 3, 7, 4]
commands = [[2, 5, 3], [4, 4, 1], [1, 7, 3]]
Output : [5, 6, 3]
```
- 출처 : (프로그래머스 가장 큰 수)[https://school.programmers.co.kr/learn/courses/30/lessons/42746]
> Example 1
```js
Input : numbers = [6, 10, 2]
Output : "6210"
```
> Example 2
```js
Input : numbers = [3, 30, 34, 5, 9]
Output : "9534330"
```

litae / 5주차 / 2문제

---

src/weekly6/nanii/leetCode/100_SameTree.js
src/weekly6/nanii/leetCode/102_BinaryTreeLevelOrderTraversal.js
src/weekly6/nanii/leetCode/226_InvertBinaryTree.js
src/weekly6/nanii/programmers/타겟넘버.js

- 출처 : [Leetcode - 100](https://leetcode.com/problems/same-tree)
> Example 1
```js
Input: p = [1,2,3], q = [1,2,3]
Output: true
```
> Example 2
```js
Input: p = [1,2], q = [1,null,2]
Output: false
```
재귀를 사용하여 오른쪽값과 왼쪽값을 비교해가면서 확인하다 값이 다를 때 바로 false 반환하게끔 구현하였습니다
----
- 출처 : [Leetcode - 102](https://leetcode.com/problems/binary-tree-level-order-traversal)
> Example 1
```js
Input: root = [3,9,20,null,null,15,7]
Output: [[3],[9,20],[15,7]]
```
> Example 2
```js
Input: []
Output: []
```
tree의 value를 확인해서 배열에 푸시를 하는데, 이때 왼쪽과 오른쪽의 값이 같은 배열의 인덱스에 위치하기 위해 새로운 배열 []을 만들어 놓고, 생성된 배열이 있으면 그 위치에 value를 푸시하고 없으면 새로 만들어서 value를 푸시하여 왼쪽값과 오른쪽값을 쌍으로 만드는 과정이 필요합니다. 그 다음 왼쪽과 오른쪽을 재귀를 사용해 계속해서 값을 찾아갑니다.
----
- 출처 : [Leetcode - 226](https://leetcode.com/problems/invert-binary-tree)
> Example 1
```js
Input: …
```

Nanii / 6주차 / 4문제

---

src/weekly6/den/leetcode/100_SameTree.js
src/weekly6/den/leetcode/226_InvertBinaryTree.js
src/weekly6/den/programmers/타겟넘버.js

- 출처 : [Leetcode - 266 / Easy](https://leetcode.com/problems/invert-binary-tree/)
> Example 1
```js
Input: root = [4,2,7,1,3,6,9]
Output: [4,7,2,9,6,3,1]
```
> Example 2
```js
Input: root = [2,1,3]
Output: [2,3,1]
```
데이터 구조가 트리인 input 값에서, 각각의 노드의 위치를 반대로 즉 오른쪽 <-> 왼쪽 변환하라는 문제로 이해했습니다. 재귀를 이용해서 노드의 자식이 더 이상 없다면 root를 반환하게 해, 노드의 위치를 바꿨습니다.
---
- 출처 : [Leetcode - 100 / Easy](https://leetcode.com/problems/same-tree/)
> Example 1
```js
Input: p = [1,2,3], q = [1,2,3]
Output: true
```
> Example 2
```js
Input: p = [1,2], q = [1,null,2]
Output: false
```
두 개의 트리가 정확히 같은 구조로 구성되어 있는지 판별하는 문제로 이해했습니다. 각각의 트리의 오른쪽과 왼쪽을 같이 재귀를 돌게 해서, 각각의 브랜치를 재귀로 제일 아래 레벨에 도달 했을 때, 두 트리가 같은 레벨에 도달했는지 여부를 판별해서 만약 같은 레벨이 아니라면 false를 리턴하고 똑같은 레벨이라면 true를 리턴하게 했습니다.
---
- 출처 : [Programmers / Lv. …

Den / 6주차 / 3문제

---

src/weekly6/litae/leetcode/100_SameTree.js
src/weekly6/litae/leetcode/102_BinaryTreeLevelOrderTraversal.js
src/weekly6/litae/leetcode/266_InvertBinaryTree.js
src/weekly6/litae/programmers/TargetNumber.js

- 출처 : [266. Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree/)
> Example 1
```
Input: root = [4,2,7,1,3,6,9]
Output: [4,7,2,9,6,3,1]
```
> Example 2
```
Input: root = [2,1,3]
Output: [2,3,1]
```
> Example 3
```
Input: root = []
Output: []
```
1. root이 존재하지 않을때는 root을 리턴하여 종료
2. 변수 temp에 root.left를 저장하여 root.left와 root.right 값을 교체
3. root.left 또는 root.right가 있을 경우 재귀
- 출처 : [100. Same Tree](https://leetcode.com/problems/same-tree/)
> Example 1
```
Input: p = [1,2,3], q = [1,2,3]
Output: true
```
> Example 2
```
Input: p = [1,2], q = [1,null,2]
Output: false
```
> Example 3
```
Input: p = [1,2,1], q = [1,1,2]
Output: false
```
1. p와 q 둘다 값이 없을 경우에는 값이 null로 동일하기 때문에 true를 리턴
2. p나 q 하나만 null일 경우에는 값이 서로 다르기 때문에 false를 리턴
3. 두 개의 값이 서로 다를 경우에는 false를 리턴
4. 두 개의 값이 같을 …

litae / 6주차 / 4문제

---

src/weekly6/poco/Programmers/타겟넘버.js
src/weekly6/poco/leetCode/100_SameTree.js
src/weekly6/poco/leetCode/102_BinaryTreeLevelOrderTraversal.js
src/weekly6/poco/leetCode/226_InvertBinaryTree.js

- 출처 : https://leetcode.com/problems/same-tree
매개변수로 주어진 두개의 tree가 같은지 확인하는 문제
두 개의 tree가 같은지 확인하면서, 재귀의 종료 조건은
두 노드 모두 null이다 = true (p노드와 q노드 모두 더이상 자식 노드가 없는 경우)
두 노드의 값(val)이 서로 다르다 = false
두 노드 중에 하나의 노드만 null이다 = false
세 기준을 가지고 각 노드의 좌측, 우측이 같은지를 확인하는 재귀적 풀이
시간복잡도 76ms, 공간복잡도 42.1MB
---
- 출처 : https://leetcode.com/problems/binary-tree-level-order-traversal
매개변수로 주어지는 이진트리를 순회하여 값들을 2차원 배열로 반환하는 문제
queue를 활용한 bfs를 사용하여 문제를 해결
같은 깊이의 값들을 같은 배열에 넣기 위해 while문 내부에서 해당 depth의
node 갯수만큼(queue.length) for loop를 통해, queue에 null 값이 아닌
새로운 node들을 추가 및 temp 배열에 push
while문 1회순회마다 result에 temp를 push 해줌으로써 같은 depth 처리하는 로직
시간복잡도 68ms, 공간복잡도 43.7 MB
---
- 출처 : https://leetcode.com/problems/invert-binary-tree
이진트리는 각 노드가 최대 두 개의 자식을 갖는 트리를 뜻한다. 즉, 각 노드는 자식이 없거나 한 개 이거나 두 개만을 갖는 것이다.
결국 매개변수로 주어진 …

Poco / 6주차 / 4문제

---

src/weekly7/den/leetcode/200_NumberOfIslands.js
src/weekly7/den/programmers/거리두기확인하기.js
src/weekly7/den/programmers/게임맵최단거리.js

**개인 사정으로 스터디에 참석할 수 없어 코드에 대한 설명을 주석으로 달았습니다.**
---
- 출처 : [leetcode - 200 / medium](https://leetcode.com/problems/number-of-islands/description/)
> Example 1
```js
Input: grid = [
["1","1","1","1","0"],
["1","1","0","1","0"],
["1","1","0","0","0"],
["0","0","0","0","0"]
]
Output: 1
```
forEach문과 DFS를 이용해서 문제를 풀었습니다. 
grid의 좌표들을 탐색하면서, "1"을 만나면 그 좌표 기준 상하좌우를 탐색(DFS)하면서 해당 섬의 모든 좌표값을 확인합니다.
DFS 탐색 중 섬의 크기 확인이 끝나면, 다음 좌표로 넘어갑니다.
---
- 출처 : [programmers - 2021 카카오 채용연계형 인턴쉽 / Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/81302)
> Example 1
```js
Input: [["POOOP", "OXXOX", "OPXPX", "OOXOX", "POXXP"], ["POOPX", "OXPXP", "PXXXO", "OXXXO", "OOOPP"], ["PXOPX", "OXOXP", "OXPOX", "OXXOP", "PXPOX"], ["OOOXX", "XOOOX", "OOOXX", "OXOOX", "OOOOO"], ["PXPXP", "XPXPX", "PXPXP", …
```

Den / 7주차 / 3문제

---

src/weekly7/poco/leetCode/200_NumberOfIslands.js
src/weekly7/poco/programmers/게임맵최단거리.js

- 출처 : https://leetcode.com/problems/number-of-islands/
'0'과 '1'로 이루어진 2차원 배열이 매개변수로 주어졌을 때, '0'은 물, '1'은 땅을 뜻한다.
섬은 땅이 상하좌우로 이어져있는 경우 연결된 것으로 판단한다(대각선은 제외)
이때, 주어진 2차원 배열에서의 섬의 갯수를 구하는 문제
먼저 주어진 2차원 배열을 탐색하면서 해당 좌표의 값이 "1" 인 경우, count를 1씩 올려주고
해당 좌표의 값을 0으로 만들고, 해당 좌표의 상하좌우 위치를 탐색한다.
이때 상하좌우 좌표 중 값이 "1"인 경우에는 해당 좌표의 값을 "0"으로 바꾸고, 이전 좌표 값의 상하좌우 탐색을 멈추고
같은 방법으로 현재 좌표의 상하좌우를 탐색한다(DFS)
최종적으로 DFS의 return의 조건은 해당 좌표를 기준으로 더이상 상하좌우에 연결된 땅 즉, "1" 값이 없는 경우이다.
시간복잡도 O(n^2) 이상, 105ms
공간복잡도 51.4 MB
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/1844
5x5 크기의 2차원 배열이 주어지고, 현재 캐릭터의 위치는 배열의 [0,0]에 위치해있다.
목적지는 배열의 [4,4]에 위치해있다고 가정했을 때, 최단거리로 목적지에 도착하는 이동 횟수를 구하는 문제
BFS 사용 문제로 queue를 사용해서 현재 좌표의 상하좌우 중에 이동할 수 있는 곳을 queue에 넣고
queue의 맨 앞에서부터 하나씩 좌표를 꺼내서 상하좌우를 탐색하고 이동하는 로직 사용
이동중에 목적지를 …

Poco / 7주차 / 2문제

---

src/weekly7/nanii/leetCode/200_NumberOfIslands.js
src/weekly7/nanii/programmers/게임맵최단거리.js

- 출처 : [Programmers - 게임맵 최단거리](https://school.programmers.co.kr/learn/courses/30/lessons/1844)
> Example 1
```js
Input: maps = [[1,0,1,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,1,0,1],[0,0,0,0,1]]
Output: 11
```
> Example 2
```js
Input: maps = [[1,0,1,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,1,0,0],[0,0,0,0,1]]
Output: -1
```
큐와 방문처리하는 방법을 통해 BFS로 문제풀이하였습니다.
먼저 시작위치를 visitQ에 넣고 방문했다는 표시로 값에 +1 증가시킵니다.
while문을 돌면서 maps[x][y] 값을 확인합니다.
이때 값이 1이면 갈 수 있으므로 추가 조건을 확인한 뒤 조건을 성립하면 visitQ에 현재 위치를 push하고, 값을 +1 증가시킵니다. 그렇지않을 경우 continue 하여 다음 방향으로 이동합니다.
따라서 마지막 maps[m][n]에 상대편이 위치한 곳이므로 해당 위치의 값을 확인하여
1일경우 마지막 0을 지나 (길이 막혔다가) 1이 되었기때문에 -1을 반환합니다.
----
- 출처 : [LeetCode - 200](https://leetcode.com/problems/number-of-islands/)
> Example 1
```js
Input: grid = [
["1","1","1","1","0"],
["1","1","0","1","0"], …
```

Nanii / 7주차 / 2문제

---

src/weekly7/litae/leetcode/200_NumberOfIslands.js
src/weekly7/litae/programmers/ShortestDistanceOfMap.js

- 출처 : [200. Number of Islands](https://leetcode.com/problems/number-of-islands/)
> Example 1
```
Input: grid = [
["1","1","1","1","0"],
["1","1","0","1","0"],
["1","1","0","0","0"],
["0","0","0","0","0"]
]
Output: 1
```
> Example 2
```
Input: grid = [
["1","1","0","0","0"],
["1","1","0","0","0"],
["0","0","1","0","0"],
["0","0","0","1","1"]
]
Output: 3
```
- 출처 : [게임 맵 최단거리](https://school.programmers.co.kr/learn/courses/30/lessons/1844)
> Example 1
```
maps = [[1,0,1,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,1,0,1],[0,0,0,0,1]]
answer = 11
```
> Example 2
```
maps = [[1,0,1,1,1],[1,0,1,0,1],[1,0,1,1,1],[1,1,1,0,0],[0,0,0,0,1]]
answer = -1
```

litae / 7주차 / 2문제

---

src/weekly8/litae/leetcode/338_CountingBits.js
src/weekly8/litae/programmers/Camouflage.js
src/weekly8/litae/programmers/H-Index.js

- 출처 : [[LTC] 338. Counting Bits](https://leetcode.com/problems/counting-bits/)
> Example 1
```
Input: n = 2
Output: [0,1,1]
Explanation:
0 --> 0
1 --> 1
2 --> 10
```
> Example 2
```
Input: n = 5
Output: [0,1,1,2,1,2]
Explanation:
0 --> 0
1 --> 1
2 --> 10
3 --> 11
4 --> 100
5 --> 101
```
1. n이 0일 경우, 0이 담긴 배열을 리턴
2. for문을 돌면서 toString()을 이용해 이진법 수로 변환
3. filter를 통해 이진법 수에 '1'을 구별
4. '1'이 담긴 배열의 길이(1의 개수)를 리턴
- 출처 : [[PGS] H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
> Example 1
```
citations: [3, 0, 6, 1, 5]
return: 3
```
1. sort()를 통해 citations 배열을 내림차순으로 정렬
2. for문을 돌면서 i >= sortCitations[i]일 경우, i를 리턴
3. sortCitations.length(h의 최대값)을 리턴
- 출처 : [[PGS] 위장](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
> Example 1
```
clothes: …
```

litae / 8주차 / 3문제

---

src/weekly8/nanii/leetCode/338_CountingBits.js
src/weekly8/nanii/programmers/h-index.js
src/weekly8/nanii/programmers/위장.js

- 출처 : [leetCode - 338](https://leetcode.com/problems/counting-bits/)
> Example 1
```js
Input: n = 2
Output: [0,1,1]
```
> Example 2
```js
Input: n = 5
Output: [0,1,1,2,1,2]
```
몫과 나머지를 이용한 이진법 계산을 한뒤 1만 더하여 배열에 넣어 계산하였습니다.
비트연산자를 사용한 풀이를 보고 학습의 필요성을 느낄 수 있었습니다.
왜 사용하는지? 장단점은 무엇인지 알아봐야겠습니다.....😅
----
- 출처 : [programmers - 위장](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
> Example 1
```js
Input: clothes = [["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]]
Output: 5
```
> Example 2
```js
Input: clothes = [["crow_mask", "face"], ["blue_sunglasses", "face"], ["smoky_makeup", "face"]]
Output: 3
```
먼저 종류별로 clothes의 갯수를 map 객체를 이용하여 구분한 다음,
그 values의 값을 이용해 경우의 수를 계산하여 풀이했습니다.
----
- 출처 : [programmers - …

Nanii / 8주차 / 3문제

---

src/weekly8/poco/leetCode/338_CountingBits.js
src/weekly8/poco/programmers/h-index.js
src/weekly8/poco/programmers/위장.js

- 출처 : https://leetcode.com/problems/counting-bits/
문제 설명 및 해결
어떤 양의 정수 n이 주어지면 0~n 까지 총 n+1 개의 배열을 만들어서 n까지의 양의 정수를 이진수로 변환시에 1의 개수를 반환하는 것이다.
0의 경우, 1이 아닌 2진법으로 변환시에도 0이 반환되기 때문에, 정규표현식을 사용했을 때 null 값이 출력된다. 따라서, 모든 경우에서 0은 고정
1부터 n까지 for 루프를 통해 2진법으로 변환한 뒤 정규표현식으로 1의 갯수를 count 해주었다.
시간복잡도 135ms, 공간복잡도 53.2MB
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/42747
문제 설명 및 해결
길이가 n인 배열이 주어지고, 해당 배열의 값 중 값과 그 값의 이상인 숫자의 갯수가 일치할 때, 해당 값을 반환하는 문제
먼저 큰 수부터 비교가 필요하기 때문에, 주어진 배열을 내림차순으로 정렬하고
for문을 통해 정렬된 배열을 순회하면서, 값이 이 index + 1 보다 크거나 같은 경우, answer를 1씩 더해주는 방식으로 해결
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/42578
문제 설명 및 해결
의상 이름과 의상 종류가 담긴 2차원 배열이 주어졌을 때, 서로 다른 옷의 조합의 수를 반환하는 문제
최소 하루에 1개의 의상은 입고, 모든 종류의 의상을 무조건 착용하는 것은 아니다
먼저 종류별로 의상 갯수를 확인하기 …

Poco / 8주차 / 2.5문제

---

src/weekly8/den/leetcode/388_CountingBits.js
src/weekly8/den/programmers/H-Index.js
src/weekly8/den/programmers/위장.js

- 출처 : [leetcode - easy](https://leetcode.com/problems/counting-bits/])
> Example 1
```js
Input: 2
Output: [0, 1, 1]
```
```js
Input: 5
Output: [0 ,1 ,1 , 2, 1, 2]
```
for문과 재귀를 이용해서 0부터 Input으로 들어오는 숫자까지 각각의 Bit를 구한 다음에, BIt에 1이 몇 개 있는지 확인 후 배열에 넣어서 반환습니다. 1시간 내에 풀긴 했지만, Follow-up을 충족시키지 못 했습니다.
---
- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/42747l)
> Example 1
```js
Input: [3, 0, 6, 1, 5]
Output: 3
```
입력 배열을 내림차순으로 소팅하고, 논문 인용 횟수를 하나씩 돌면서, n회 이상 인용된 논문이 n개 보다 같거나 클 때를 구해줬습니다.
---
- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
> Example 1
```js
Input: [["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]]
Output: 3
```
```js
Input: [["yellow_hat", "headgear"], …
```

Den / 8주차 / 2.5문제

---

src/weekly10/nanii/baekjoon/로프.js
src/weekly10/nanii/programmers/체육복.js
src/weekly10/nanii/programmers/큰수만들기.js
src/weekly9/nanii/baekjoon/11055_가장큰증가부분수열.js

- 출처 : [baekjoon -11055](https://www.acmicpc.net/problem/11055)
> Example 1
```js
Input: 1 100 2 50 60 3 5 6 7 8
Output: 113
```
dp [] 배열을 생성하여 array 를 순회하면서 다음 요소의 값이 증가하는 경우 
앞의 요소들과의 합을 dp 에 넣어 배열 내 최대값 메서드 Math.max를 이용합니다.
---
- 출처 : [baejoon - 2217](https://www.acmicpc.net/problem/2217)
> Example 1
```js
Input: 2, 10 ,15
Output: 20
```
먼저 로프의 배열을 내림차순으로 정렬합니다.
(배열의 인덱스 + 1) = 로프의 갯수
(배열의 각 요소) = 로프가 버틸 수 있는 최대 중량
임을 이용해 배열안에 넣고 최대값 Math.max를 이용합니다.
---
- 출처 : [programmers - Lv1](https://school.programmers.co.kr/learn/courses/30/lessons/42862)
> Example 1
```js
Input: 5, [2,4], [1,3,5]
Output: 5
```
```js
Input: 5, [2,4], [3]
Output: 4
```
```js
Input: 3, [3], [1]
Output: 2
```
lost 배열을 순회하면서 +1 또는 -1 한 값이 reverse 에 있는지 확인합니다
reverse 에 있으면서 used 에 없으면 used 에 넣고
reverse 에 있지만 used에 있으면 …

Nanii / 9, 10 주차 / 4문제

---

src/weekly10/den/programmers/체육복.js
src/weekly10/den/programmers/큰수만들기.js
src/weekly9/den/baekjoon/2×n_타일링 2.js
src/weekly9/den/baekjoon/로프.js

- 출처 : [baekjoon - silver3](https://www.acmicpc.net/problem/11727)
> Example 1
```js
Input: 2
Output: 1
```
```js
Input: 8
Output: 171
```
```js
Input: 12
Output: 2731
```
1*2, 2*1, 2*2 3가지 타일을 가지고 주어진 2 * n 크기의 영역을 채울 수 있는 경우의 수를 구하는 문제다. 
이 문제를 풀기 위해 실제로 n의 값에 따라 경우의 수가 몇 개가 나오는지 구해봤다.
n = 1일 때, 즉 2*1 크기일 때, 2*1 타일 1개만 들어간다. 경우의 수 1개
n = 2일 때, 즉 2*2 크기일 때, 1*2 2개 = 경우의 수 1, 2*1 2개 = 경우의 수 1, 2*2 1개 = 경우의 수 1 -> 경우의 수 총 3개
n = 3일 때 즉 2*3 크기일 때, n = 2일 때의 경우의 수 + n = 1일 때의 경우의수 * 2(2*1 타일, 2*2 타일) = 3 + 1 * 2 = 5
이런 식으로 n = n -1 + (n -2 * 2) 규칙으로 경우의 수 가 커지는 것을 알 수 있다. 이를 코드로 구현했다.
---
- 출처 : [baejoon - siver4](https://www.acmicpc.net/problem/2217)
> Example 1
```js
Input: 2, 10 ,15
Output: 20
```
주어진 로프들로 들어올릴 수 있는 최대 중량을 구하는 문제다. 
각각의 로프들은 자신이 버틸 수 있는 중량보다 더 큰 중량을 들 수 있다. 
그러므로, 우선 주어진 …

Den / 9주차, 10주차 / 4문제

---

src/weekly10/poco/BOJ/로프.js
src/weekly10/poco/programmers/체육복.js
src/weekly10/poco/programmers/큰수만들기.js
src/weekly9/poco/BOJ/2xn스타일링2.js

- 출처 : https://www.acmicpc.net/problem/11727
문제 설명 및 해결
2(행) x n(열) 모양의 직사각형을 1 x 2, 2 x 1, 2 x 2 타일로 채우는 방법의 수를
구하는 문제로, 채우는 방법의 수를 10,007로 나눈 나머지를 출력하는 문제
먼저 2 x n 모양의 직사각형의 가장 왼쪽에 2 x 1 / 1 x 2 / 2 x 2 타일을 채우는 경우
남은 부분에 대해서 타일을 채울 수 있는 경우의 수는 각각 2 x (n-1) / 2 x (n-2) / 2 x (n-2) 이다
따라서 위의 경우의 수 3가지를 모두 더하는 방법으로 2 x n 모양의 직사각형을 채우는 방법의 수를 구할 수 있다.
---
- 출처 : https://www.acmicpc.net/problem/2217
문제 설명 및 해결
input으로 총 로프의 갯수와 각 로프들의 최대 중량이 주어질 때, 로프를 병렬로 연결해서
버틸 수 있는 최대 중량을 구하는 문제
모든 로프를 사용할 필요는 없으나, 각각의 로프에는 모두 (총 중량 / 로프의 수)만큼의 중량이 걸리게 된다)
로프가 버틸 수 있는 중량을 기준으로 오름차순 정렬을 하고, 전체 로프의 중량을
순회하면서, 해당 로프의 중량을 최소 기준으로 정했을 때, 들 수 있는 최대 중량을 구한다.
즉, 10, 15, 20, 25라는 각각의 중량을 버틸 수 있는 로프들이 있는 경우,
10 로프를 최소 값으로 정하는 경우, 각 로프는 균등한 무게를 버텨야하기 때문에, 최대 중량은
10 * 4 = 40이고, 이후 15 로프를 최소값으로 정하는 경우, 10 로프는 15 무게를 …

Poco / 9,10주차 / 4문제

---

src/weekly10/litae/programmers/MakeLargeNumber.js

- 출처 : [[PGS] 큰 수 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42883)
> Example 1
number: "1924"
k: 2
return: "94"
> Example 2
number: "1231234"
k: 3
return: "3234"
> Example 3
number: "4177252841"
k: 4
return: "775841"

litae / 9, 10주차 / 1문제

---

src/weekly11/den/leetcode/118_Pascal'sTriangle.js
src/weekly11/den/programmers/다리를지나는트럭.js

- 출처 : [leetcode - easy](https://leetcode.com/problems/pascals-triangle/description/l)
> Example 1
```js
Input: 5
Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
```
> Example 2
```js
Input: 1
Output: [[1]]
```
주어진 input과 동일한 길이의 2차원 배열을 만드는데, 내부 배열의 요소들이 규칙성 있게 만들어지는 것을 코드로 구현했습니다.
내부 배열의 0번째, 그리고 마지막 요소는 1을 고정값으로 할당해주고,
나머지 요소들은 `table[i][j] = table[i-1][j-1] + table[i-1][j]`의 규칙성으로 값을 할당했습니다.
---
- 출처 : [Programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
> Example 1
```js
Input: 2, 10, [7,4,5,6]
Output: 8
```
> Example 2
```js
Input: 100, 100, [10]
Output: 101
```
> Example 3
```js
Input: 100, 100, [10,10,10,10,10,10,10,10,10,10]
Output: 110
```
Input으로 주어진 트럭들이 중량 한계가 있는 다리를 지나는데, 모든 트럭들이 다리를 다 지나려면 몇 초가 걸리는지 계산하는 문제입니다.
다리가 견딜 수 있는 무게는 한계가 있고, 트럭이 …

Den / 11주차 / 2문제

---

src/weekly11/nanii/leetCode/118_PascalTriangle.js
src/weekly11/nanii/programmers/다리를지나는트럭.js

- 출처 : [leetcode - easy](https://leetcode.com/problems/pascals-triangle/description/l)
> Example 1
```js
Input: 5
Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
```
> Example 2
```js
Input: 1
Output: [[1]]
```
앞줄의 배열에서 - 1, + 0 위치의 인덱스의 값을 더해가며 2차원 배열을 만들었습니다.
이때 인덱스가 0이거나 맨마지막 요소인 경우는 1을 넣고, 아닐경우 [i-1][j-1] + [i-1][j]한 값을 할당합니다.
---
- 출처 : [Programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
> Example 1
```js
Input: 2, 10, [7,4,5,6]
Output: 8
```
> Example 2
```js
Input: 100, 100, [10]
Output: 101
```
> Example 3
```js
Input: 100, 100, [10,10,10,10,10,10,10,10,10,10]
Output: 110
```
while 종료조건 (남은 트럭배열의 길이가 0이 될때까지), 트럭을 다리Q에 올립니다.
다음 트럭이 올라갈 수 있는지 확인하기 위해 다리위의 트럭무게를 잰 뒤,
올라갈 수 있으면 트럭배열에서 맨 앞 요소를 shift()
올라갈 수 없다면 다리Q에 push(0)을 하였고
마지막 트럭이 올라간 뒤, 다리를 …

Nanii / 11주차 / 2문제

---

src/weekly11/poco/leetCode/118_Pascal'sTriangle.js
src/weekly11/poco/programmers/다리를지나는트럭.js

- 출처 : https://leetcode.com/problems/pascals-triangle/
매개변수 = 파스칼 삼각형의 전체 rows(행) 
파스칼 삼각형의 모습을 2차원 배열로 출력하는 문제
먼저 파스칼 삼각형의 모습을 하는 2차원 배열을 선언하였다.
파스칼 삼각형의 n번째 row의 원소들은 처음과 마지막은 1, 그외 index의 값은 n-1번째 row의 (index - 1) + (index) 값이 된다.
따라서, 2중 for문을 통해 이전 row(파스칼 삼각형의 첫번째 줄 판단)와 이전 row의 (index - 1), (index) 값 중 하나라도 없을 경우,
해당 row의 index 값은 1(처음과 마지막 index)이 되고, 반대의 경우에는 이전 row의 (index - 1) + (index) 값으로 해주었다.
시간복잡도 O(n^2)
2중 for문 안에서의 조건문을 처리할 때, 단순히 이전 row의 (index - 1)값과 (index)값의 조건만을 판단했을 때,
error가 계속 발생하였고, 이전 row가 있는지 여부 먼저 판단했을 때 통과
아마도 이전 row가 없는 상태에서 이전 row 배열의 값에 index를 이용해 접근했을 때 오류가 발생한 것으로 보인다
전체 배열의 크기를 먼저 선언을 하고 for문을 통해 값들을 변경하기
vs
빈배열에 for문을 통해 값들을 넣기
둘중에 어떤게 더 효율적일지
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/42583
매개변수
bridge_length : 다리에 올라갈 수 있는 …

Poco / 11주차 / 2문제

---

src/weekly12/nanii/신고결과받기.js

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
> Example 1
```js
Input: ["muzi", "frodo", "apeach", "neo"], ["muzi frodo","apeach frodo","frodo neo","muzi neo","apeach muzi"], 2
Output: [2,1,1,0]
```
```js
Input: ["con", "ryan"], ["ryan con", "ryan con", "ryan con", "ryan con"], 3
Output: [0,0]
```
1. 맵객체를 사용하여[ key : 신고당한사람 , value : 신고자 ] 로 값을 등록합니다.
2. 이때 이미 신고된 사람이면, 중복신고가 아닌경우 신고자를 추가로 등록하고
3. 처음 신고되는 사람이면, 신고자를 추가로 등록합니다.
4. 그 다음 그 신고된 리스트를 이용하여 id리스트를 순회하면서 k 번 이상 신고된 사람이 있다면 이메일 통보 횟수를 증가시켜 값을 등록하였습니다..만 주어진 테스트 케이스 외에 예외처리를 실패하였습니다.. 🥹

Nanii / 12주차 / 1문제

---

src/weekly12/den/programmers/신고결과받기.js

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
> Example 1
```js
Input: ["muzi", "frodo", "apeach", "neo"], ["muzi frodo","apeach frodo","frodo neo","muzi neo","apeach muzi"], 2
Output: [2,1,1,0]
```
```js
Input: ["con", "ryan"], ["ryan con", "ryan con", "ryan con", "ryan con"], 3
Output: [0,0]
```
유저들이 신고한 유저 중 게시판 정지 처분을 받은 유저의 수를 구하는 문제다.
풀이 과정을 요약하면,
우선 변수 ids에 Map 객체 할당해서 Map에 유저 목록을 추가해주고,
Set 객체를 사용해서, 한 유저가 특정 한 유저를 중복 신고한 경우를 처리했다.
그리고 input인 reports를 순회하면서 ids에 있는 각 유저가 신고한 목록을 넣어주고, 
새로운 reportCounts 변수에 Map 객체를 할당해서 각 유저가 신고받은 횟수를 Map 객체에 count 해줬다.
마지막으로 각 유저가 신고한 유저 중 정지 처분을 받은 유저의 수를 reportCounts 객체와 비교해서 구한 뒤 return 해줬다.

Den /  12주차 / 1문제

---

src/weekly12/poco/programmers/신고결과받기.js

- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/92334
매개변수
id_list : 이용자의 ID가 담긴 문자열 배열
report : 각 이용자가 신고한 이용자의 ID 정보가 담긴 문자열 배열
k : 정지 기준이 되는 신고 횟수
출력
각 유저별로 처리 결과 메일을 받은 횟수를 배열에 담아 return
한번에 한명의 유저를 신고할 수 있다.
신고횟수에 제한은 없기 때문에, 다른 유저를 계속 신고할 수 있다
하지만, 동일 유저에 대한 신고를 1회로 처리된다
k번 이상 신고된 유저는 게시판 이용이 정지되고, 해당 유저를 신고한
모든 유저에게 정지 사실이 메일로 발송된다
코드내에서 id는 신고한 사람, target은 신고당한 사람으로 정의하였다
먼저 요소가 0이고 전체 유저 수만큼의 길이를 갖는 answer 배열을 만든다
다음으로 key는 target, value는 빈 배열(신고한 사람을 추가) 되는 reportObj 생성
매개변수 report 배열을 순회하면서 id = 신고한 사람, target = 신고당한사람으로 해체할당 하였고
target을 신고한 사람의 목록(배열)중에 동일한 id(신고한 사람)이 없는 경우에만 배열에 id를 push
그리고 reportObj 객체를 순회하면서, target을 신고한 사람이 k보다 큰 경우에만
id 배열을 순회하면서, answer 배열에 해당 id의 index에 1 더해주는 방식으로 해결
배운 것
삼항연산자 내부에서는 continue 사용이 불가하다
대신 some과 함께 사용해서, true 값이 될 때, …

Poco / 12주차 / 1문제

---

src/weekly12/litae/programmers/신고 결과 받기.js

- [[PGS] 신고 결과 받기](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
> Example 1
```
id_list: ["muzi", "frodo", "apeach", "neo"]
report: ["muzi frodo","apeach frodo","frodo neo","muzi neo","apeach muzi"]
k: 2
result: [2,1,1,0]
```
> Example 2
```
id_list: ["con", "ryan"]
report: ["ryan con", "ryan con", "ryan con", "ryan con"]
k: 3
result: [0,0]
```
1. set 객체를 통해 중복되는 신고 제거
2. indexOf 매서드를 통해 신고된 아이디 유저의 횟수를 카운트해서 id_list의 index에 저장
3. 신고된 횟수가 K보다 많거나 같은 유저를 reportedKUser 저장
4. set을 돌면서 reportedKUser에 해당되는 유저가 있을 경우 카운트해서 result에 저장

litae / 12주차 / 1문제

---

src/weekly13/nanii/leetCode/replaceWords.js
src/weekly13/nanii/programmers/완주하지못한선수.js

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
> Example 1
```js
Input: [participant, completion] = [["leo", "kiki", "eden"], ["eden", "kiki"]]
Output: "leo"
```
> Example 2
```js
Input: [participant, completion] = [["marina", "josipa", "nikola", "vinko", "filipa"], ["josipa", "filipa", "marina", "nikola"]]
Output: "vinko"
```
> Example 3
```js
Input: [participant, completion] = [["mislav", "stanko", "mislav", "ana"], ["stanko", "ana", "mislav"]]
Output: "mislav"
```
1. Map 객체를 사용하여 선수이름을 Key값으로 순회합니다
2. 참가자들의 이름을 key, 참가한 경우 +1
3. 완주자들의 이름을 key, 완주한 경우 -1
5. 참가했고 완주한 경우는 `value = 0`
6. 참가했고 완주를 못한경우 뺀 값이 없을 것이므로 `value > 0`
7. 따라서 value > 0 일때 Key가 완주하지 못한 선수입니다
---
- 출처 : [Leetcode - Mediium](https://leetcode.com/problems/replace-words/)
> …

Nanii / 13주차 / 2문제

---

src/weekly13/den/leetcode/648_Replace Words.js
src/weekly13/den/programmers/완주하지못한선수.js

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
> Example 1
```js
Input: ["leo", "kiki", "eden"], ["eden", "kiki"]
Output: "leo"
```
> Example 2
```js
Input: ["marina", "josipa", "nikola", "vinko", "filipa"], ["josipa", "filipa", "marina", "nikola"], "vinko"
Output: "vinko"
```
> Example 3
```js
Input: ["mislav", "stanko", "mislav", "ana"], ["stanko", "ana", "mislav"]
Output: "mislav"
```
완주하지 못 한 선수를 구하는 문제로, 문제 조건 중에 "단 한 명의 선수를 제외하고는 모든 선수가 마라톤을 완주하였습니다."으로 인해서 문제 난이도가 좀 낮아진 느낌을 받았습니다.
우선, 참가한 선수들을 Map 객체에 넣고 value는 1을 줬습니다.
그리고 완주한 선수들의 value 값을 1씩 뺴주고, 
최종적으로 value가 1인 선수를 return 해줬습니다.
---
- 출처 : [Leetcode - medium](https://leetcode.com/problems/replace-words/)
> Example 1
```js
Input: ["cat","bat","rat"], "the cattle was rattled by the …
```

Den / 13주차 / 2문제

---

src/weekly13/litae/leetcode/648_ReplaceWords.js
src/weekly13/litae/programmers/완주하지못한선수.js

-  [[PGS] 완주하지 못한 선수](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
> Example 1
participant: ["leo", "kiki", "eden"]
completion: ["eden", "kiki"]
return: "leo"
> Example 2
participant: ["marina", "josipa", "nikola", "vinko", "filipa"]
completion: ["josipa", "filipa", "marina", "nikola"]
return: "vinko"
> Example 3
participant: ["mislav", "stanko", "mislav", "ana"]
completion: ["stanko", "ana", "mislav"]
return: "mislav"
1. sort와 find 활용
2. sort를 통해 이름을 정렬하고 두 배열의 인덱스의 값이 다른 값을 리턴
-  [[LTC] 648_Replace Words](https://leetcode.com/problems/replace-words/description/)
> Example 1
Input: dictionary = ["cat","bat","rat"], sentence = "the cattle was rattled by the battery"
Output: "the cat was rat by the bat"
> Example 2
Input: dictionary = ["a","b","c"], sentence = "aadsfasf …

litae / 13주차 / 2문제

---

src/weekly14/poco/programmers/[PGS]괄호회전하기.js
src/weekly14/poco/programmers/[PGS]성격유형검사하기.js

- 출처 : [괄호회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
s : 대괄호, 중괄호, 그리고 소괄호로 이루어진 문자열
괄호로 이루어진 문자열 s를 0번부터 s.lenght -1 번 이동했을 때, 올바른 괄호가 되는 경우의 수의 개수를 return 하는 문제
for문을 통해 문자열 s를 좌측으로 0번부터 s.length -1번 이동하게 하였고, 각각 좌측으로 n번 이동한 문자열을 checkBracket 함수를 통해 올바른 괄호인지 판단했다.
---
- 출처 : [성격 유형 검사하기](https://school.programmers.co.kr/learn/courses/30/lessons/118666)
survey : 판단하는 지표를 담은 1차원 문자열 배열
choices : 검사자가 각 잘문마다 선택한 선택지를 담은 1차원 정수 배열
검사자의 성격 유형 검사 결과를 지표 번호 순서대로 return
매우 동의, 매우 비동의는 3점
동의, 비동의는 2점
약간 동의, 약간 비동의는 1점
모르겠음은 0점
더 높은 점수를 받은 성격 유형이 검사자의 성격 유형이 된다.
만약 하나의 지표에서 각 성격 유형 점수가 같으면, 두 성격 유형 중 사전순으로
빠른 성격 유형을 검사자의 성격 유형으로 판단한다.
survey[i] 의 첫번째 문자열의 비동의 관련, 두번째 문자열은 동의 관련 문자열이다.
choices는 1부터 7까지이며, 1은 매우 비동의, 4는 모르겠음, 7은 매우 동의이다.
각 유형별로 점수를 체크할 수 있는 count 객체를 선언 …

Poco / 14주차 / 2문제

---

src/weekly14/nanii/programmers/괄호회전하기.js
src/weekly14/nanii/programmers/성격유형검사하기.js

- 출처 : [프로그래머스](https://school.programmers.co.kr/learn/courses/30/lessons/76502#)
> Example 1
```js
Input: "[](){}"
Output: 3
```
> Example 2
```js
Input: "}]()[{"
Output: 2
```
> Example 3
```js
Input: "[)(]"
Output: 0
```
> Example 4
```js
Input: "}}}"
Output: 0
```
1. 주어진 문자열을 순회하면서 괄호문법을 계산합니다.
2. 먼저 괄호문법이 올바른지 확인하는 함수를 작성합니다.
3. 여는 괄호일경우 `stack.push(닫는괄호)`를 하고,
4. 닫는 괄호일경우 stack의 마지막 인덱스값과 닫는 괄호가 일치하는지 확인후 `stack.pop()`합니다.
5. 그렇지 않을 경우 잘못된 괄호문법이므로 return 합니다.
6. 주어진 문자열의 길이만큼 x칸을 계속해서 이동해야하므로 for문 내에서 `string.substring()`으로 새로운 문자열 조합을 생성하고 괄호문법을 확인하여 최종 answer를 반환합니다.
--- 
- 출처 : [프로그래머스](https://school.programmers.co.kr/learn/courses/30/lessons/118666#)
> Example 1
```js
Input: [survey, choices] = [["AN", "CF", "MJ", "RT", "NA"], [5, 3, 2, 7, 5]]
Output: "TCMA"
```
> Example 2 …

Nanii / 14주차 / 2문제

---

src/weekly14/den/programmers/성격유형검사하기.js

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/118666?language=javascript )
> Example 1
```js
Input: ["AN", "CF", "MJ", "RT", "NA"], [5, 3, 2, 7, 5]
Output: "TCMA"
```
> Example 2
```js
Input: ["TR", "RT", "TR"], [7, 1, 3]
Output: "RCJA"
```
성격 검사 테스트의 결과 도출 로직을 구현하고, 검사자가 choices와 survey를 제출하면 지표번호 순서대로 return 해야 되는 문제로 이해했습니다. 조건이 까다롭진 않아서 코드 자체가 복잡하지 않지만 조건의 수는 많아서 각각의 조건을 구현하기 위해 조건문과 고차함수를 활용했습니다.
문제 로직 흐름
1. choice 매개변수를 바탕으로 각 성격 유형별 점수 산출
2. 산출된 성격 유형벌 점수를 2개씩 순서대로 비교해서, 지표번호 순서대로 return 될 수 있도록 로직 구현

Den / 14주차 / 1문제

---

src/weekly14/litae/programmers/괄호 회전하기.js

- [[PGS] 괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
> Example 1
s: "[](){}"
result: 3
> Example 2
s: "}]()[{"
result: 2
> Example 3
s: "[)(]"
result: 0
> Example 4
s: "}}}"
result: 0

litae / 14주차 / 1문제

---

src/weekly15/litae/programmers/문자열 정렬하기(1).ts
src/weekly15/litae/programmers/문자열을 정수로 바꾸기.ts

- [[PGS] 문자열을 정수로 바꾸기](https://school.programmers.co.kr/learn/courses/30/lessons/12925)
> Example 1
```
input: "1234"
result: 1234
```
> Example 2
```
input: "-1234"
result: -1234
```
string 타입의 s를 Number를 활용하여 number 타입으로 변경
- [[PGS] 문자열 정렬하기 (1)](https://school.programmers.co.kr/learn/courses/30/lessons/120850)
> Example 1
```
my_string: "hi12392"
result: [1, 2, 2, 3, 9]
```
> Example 2
```
my_string: "p2o4i8gj2"
result: [2, 2, 4, 8]
```
> Example 3
```
my_string: "abcde0"
result: [0]
```
string 타입의 my_string를 받아 각 글자별 배열을 만들고 filter를 통해 숫자만 분류(숫자는 1로 나누었을 때 자기 자신이 나오는 성질을 활용)
map을 이용하여 string 타입을 number 타입으로 변경하고, sort로 정렬하여 리턴

litae / 15주차 / 2문제

---

src/weekly15/nanii/programmers/문자열을정수로바꾸기.ts
src/weekly15/nanii/programmers/문자열정렬하기.ts

- 출처 : [프로그래머스](https://school.programmers.co.kr/learn/courses/30/lessons/12925)
> Example 1
```js
Input : "1234"
Ouput : 1234
```
> Example 2
```js
Input : "-1234"
Ouput : -1234
```
JS에서 흔히 사용하던 Math 메서드도 `Math.abs`(`Number(s)`) 매개변수가 number 여야하는 사실을 깨달았습니다.
`Math.abs(s) `로 하면 에러가 나 명시적으로 **Number type 변환을 한 뒤** Math.abs 메서드를 사용할 수 있었습니다.
--- 
- 출처 : [프로그래머스](https://school.programmers.co.kr/learn/courses/30/lessons/120850)
> Example 1
```js
Input: my_string = "hi12392"
Output: [1, 2, 2, 3, 9]
```
> Example 2
```js
Input: my_string = "p2o4i8gj2"
Output: [2, 2, 4, 8]
```
> Example 3
```js
Input: my_string = "abcde0"
Output: [0]
```
문제를 푸는 도중 ['number' 형식의 인수는 'never' 형식의 매개 변수에 할당될 수 없습니다.] 이라는 에러가 발생했는데요, 
자연스럽게 return 값에 :number[] 했기때문에 스코프 내부에 있는 answer 변수가 반환될꺼니까~맞지않나 하고 answer변수 타입을 …

Nanii / 15주차 / 2문제

---

src/weekly15/den/programmers/문자열 정렬하기(1).ts
src/weekly15/den/programmers/문자열을 정수로 바꾸기.ts

1. npm i typescript -g : 전역에 install
2. npm i ts-node --save-dev
- npx tsc : js 파일로 컴파일 후 js 코드 실행
- 혹은 npx ts-node src/~path 로 ts 파일 직접 실행
- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/120850)
> Example 1
```js
Input: hi12392
Output: [1, 2, 2, 3, 9]
```
> Example 2
```js
Input: p2o4i8gj2
Output: [2, 2, 4, 8]
```
> Example 3
```js
Input: abcde0
Output: [0]
```
이 문제의 input 타입은 string, output 타입은 number 입니다.
그래서 타입 어노테이션을 활용해 solution 함수의 매개변수는 string만, output은 number만 반환할 수 있게 설정했습니다.
함수 내 로직 흐름은 다음과 같습니다.
1. split사용해서 Input string을 배열화하고
2. sort를 사용해서 배열을 정렬하고
3. fitler를 사용해서 배열 내에 타입이 숫자인 요소만으로 이루어진 배열을 반환하고
4. map을 사용해서 배열 내 요소의 타입을 모두 숫자로 변환해 준 뒤 return 했습니다.
- 출처 : [programmers - Lv.0](https://school.programmers.co.kr/learn/courses/30/lessons/129 …

Den / 15주차 / 2문제

---

src/weekly15/poco/[PGS]문자열을정수로바꾸기.js
src/weekly15/poco/[PGS]문자열정렬하기.js

- 출처 : [문제링크](https://school.programmers.co.kr/learn/courses/30/lessons/120850)
my_string : 0~9까지의 숫자 한 개 이상과 영어 소문자로 이루어진 문자열
my_string 문자열 내에서 숫자만 골라서 오름차순으로 정렬해서 출력
매개변수로 주어진 my_string에서 숫자만 골라내서 오름차순으로 정렬해서 출력하는 문제
정규표현식으로 my_string에서 숫자만을 골라낸 뒤, Number 메서드로 숫자화 시키고,
sort 메서드로 오름차순 정렬
---
- 출처 : [문제링크](https://school.programmers.co.kr/learn/courses/30/lessons/12925)
s : 문자열
매개변수 문자열 s를 숫자로 변환한 결과를 출력하라
Number 메서드 활용해서, 문자열을 숫자로 변환
---

Poco /  15주차 / 2문제

---

src/weekly16/poco/programmers/[PGS]부족한금액계산하기.js
src/weekly16/poco/programmers/[PGS]비밀지도.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/82612))
price : 놀이기구 이용료
money : 처음가지고 있던 금액
count : 놀이기구를 이용하는 횟수
놀이기구를 count 이용했을 때, 가지고 있는 money에서 얼마가 모자라는지 return
놀이기구를 N번 이용하면, 원래 이용로의 N배를 내야한다.
총 놀이기구를 COUNT번 탄다고 했을 때, 현재 가지고 있는 money가
얼마나 모자라는지 return 하는 문제
놀이기구를 이용할 때 필요한 전체 금액과 현재 가진 금액을 비교해서 해결
test case 4번의 경우
이용료보다 내가 가진 돈이 큰 경우에는 부족한 금액이 없기 때문에 0을
return 해야하기 때문에, return 문에 조건 추가로 해결
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/17681))
n : 지도 한 변의 크기
arr1, arr2 : 정수 배열
비밀지도를 해독해서 벽(#)과 공백(" ")으로 구성된 문자열 배열 return
지도에는 공백과 벽 두 종류로 이루어져 있다
지도 1 또는 지도 2에서 벽인 부분은 전체 지도에서도 벽이다
암호화된 배열은 지도의 각 가로줄에서 벽 부분을 1, 공백 부분을 0으로
부호화했을 때 얻어지는 이진수에 해당하는 값의 배열이다
arr1, arr2를 순회하면서, 각 10진수의 요소를 2진수로 변환
2진수로 변환된 두개의 배열을 순회하면서, 지도의 영역이 벽("#")일지, …

Poco / 16주차 / 2문제

---

src/weekly16/den/programmers/[1차]비밀지도.ts
src/weekly16/den/programmers/부족한금액계산하기.ts

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/17681)
> Example 1
```js
Input: 5, [9, 20, 28, 18, 11], [30, 1, 21, 17, 28]
Output: ["#####","# # #", "### #", "# ##", "#####"]
```
> Example 2
```js
Input: 6, [46, 33, 33 ,22, 31, 50], [27 ,56, 19, 14, 14, 10]
Output: ["######", "### #", "## ##", " #### ", " #####", "### # "]
```
1. 주어진 배열 arr1, arr2의 숫자 요소들을 이진수로 이루어진 배열로 변환해서 2차원 배열로 만들어줬습니다.
- 이진수로  변환하는 작업을 두번 하기 때문에, 코드 중복을 줄이기 위해 `convertMapToBinary` 헬퍼 함수를 만들었습니다.
- `convertMapToBinary` 함수는 매개변수로 size와 array를 받습니다.
- array의 각 숫자 요소들을 `.toString(2)`을 이용해서 2진수로 변환하고, `split`을 이용해 배열화 했습니다.
- 변환 완료된 2진수 배열의 길이가 size보다 작다면, size길이에 맞게 0을 채워 줬습니다.
- ex. 2진수가 [0,1,0,1]이고 size가 5면 0을 `.unshift(0)`를 이용해서 삽입해서 [0,0,1,0,1]으로 만들어 준다.
- 마지막으로, 2진수 배열의 각 요소가 …

Den / 16주차 / 2문제

---

src/weekly16/nanii/programmers/부족한금액계산하기.ts
src/weekly16/nanii/programmers/비밀지도.ts
src/weekly16/nanii/programmers/비밀지도_JS.js

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/17681)
> Example 1
```js
Input : [n = 5, arr1 = [9, 20, 28, 18, 11], arr2 = [30, 1, 21, 17, 28]]
Output : ["#####","# # #", "### #", "# ##", "#####"]
```
> Example 2
```js
Input : [n = 6, arr1 = [46, 33, 33 ,22, 31, 50], arr2 = [27 ,56, 19, 14, 14, 10]]
Output : ["######", "### #", "## ##", " #### ", " #####", "### # "]
```
1. 우선 10진수로 이루어진 배열을 2진수로 변환합니다.
2. 2진수로 변환한 숫자의 자릿수가 주어진 변보다 작을 경우 맨 앞자리에 0을 채워야 하므로 padStart method를 사용하려했습니다. TS 파일로는 적용이 안되서 찾아보니 "es2017" 부터 적용된다고 합니다... 
3. 배열 내부 요소를 2진수로 변환했다면, 두 배열을 비교하면서 해당 인덱스의 값이 같으면 그 값을, 다르면 1이므로 1을 넣어 주어진 지도에서 사용되는 문자열을 입력해주었습니다.
---
- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/82612)
> Example 1
```js
Input: 3, …
```

Nanii / 16주차 / 2문제

---

src/weekly17/litae/programmers/로또의 최고 순위와 최저 순위.ts
src/weekly17/litae/programmers/숫자 문자열과 영단어.ts

- [[PGS] 숫자 문자열과 영단어](https://school.programmers.co.kr/learn/courses/30/lessons/81301)
> Example 1
```
s: "one4seveneight"
result: 1478
```
> Example 2
```
s: "23four5six7"
result: 234567
```
> Example 3
```
s: "2three45sixseven"
result: 234567
```
> Example 4
```
s: "123"
result: 123
```
- [[PGS] 로또의 최고 순위와 최저 순위](https://school.programmers.co.kr/learn/courses/30/lessons/77484)
> Example 1
```
lottos: [44, 1, 0, 0, 31, 25]
win_nums: [31, 10, 45, 1, 6, 19]
result: [3, 5]
```
> Example 2
```
lottos: [0, 0, 0, 0, 0, 0]
win_nums: [38, 19, 20, 40, 15, 25]
result: [1, 6]
```
> Example 3
```
lottos: [45, 4, 35, 20, 3, 9]
win_nums: [20, 9, 3, 45, 4, 35]
result: [1, 1]
```

litae / 17-18주차 / 2문제

---

src/weekly17/den/programmers/로또의최고순위최저순위.ts
src/weekly17/den/programmers/숫자문자열과영단어.ts

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/81301)
> Example 1
```js
Input: "one4seveneight"
Output: 1478
```
> Example 2
```js
Input: "23four5six7"
Output: 234567
```
> Example 3
```js
Input: "2three45sixseven"
Output: 234567
```
> Example 4
```js
Input: "123"
Output: 123
```
1. 매개변수 문자열 for문 돌면서 숫자 여부 판단.
- 숫자면 answer 문자열에 더하고,
- 타입이 String이면, 검증 문자열에 더한다.
- 검증 문자열에 맞는 숫자를 표에서 찾는다.
- 있으면, answer 문자열에 더하고, 검증 문자열 ''로 reset한다.
- 없으면, continue
2. for문 끝나면 answer 문자열을 숫자 타입으로 변환하고 반환한다.
---
- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/77484)
> Example 1
```js
Input: [44, 1, 0, 0, 31, 25], [31, 10, 45, 1, 6, 19]
Output: [3, 5]
```
> Example 2
```js
Input: [0, 0, 0, 0, 0, 0], [38, 19, 20, 40, 15, 25]
Output: …
```

Den / 17주차 / 2문제

---

src/weekly17/poco/programmers/로또의최고순위와최저순위.js
src/weekly17/poco/programmers/숫자문자열과영단어.js
src/weekly18/poco/programmers/이모티콘할인행사.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/150368))
lottos : 민우가 구매한 로또 번호
win_nums : 당첨 번호
당첨 가능한 최고 순위, 최저 순위를 담은 배열
민우가 구매한 로또 번호 중에 알아볼수 없는 번호를 0으로 표시했을 때,
당첨번호와 비교해서 민우가 당첨될 수 있는 최고, 최저 순위를 배열에 담아서 return 하는 문제
먼저 민우가 구매한 로또 번호와 당첨 번호 중에 일치하는 번호의 갯수를 구한다
이는 0으로 표시된 알아볼수 없는 번호가 당첨번호와 모두 다를 때, 최저 순위를 계산할 수 있는 번호 갯수가 된다
그리고 민우가 맞춘 번호 갯수와 0의 갯수를 더하는 경우 최고 순위를 계산할 수 있는 번호 갯수가 된다
--- 
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/81301))
s : 숫자 문자열
매개변수 s가 의미하는 원래 숫자를 return
문자열 s 중에 숫자가 아닌 문자열로 표시된 부분을 숫자로 변경하는 문제
정규표현식을 사용해서 s의 문자열들을 해당하는 숫자로 변형한 뒤 return해서 해결
처음 풀이에는 객체에 각 문자열에 해당하는 숫자를 먼저 저장하고 매개변수 s를 순회하는 방식을 사용했는데
테스트 7, 8, 9를 통과하지 못하였고 예외사항에 대해서 찾지 못하였고 정규표현식을 사용해서 풀이하는 방법으로 선회
---
- 출처 : …

Poco / 17~ 18주차 / 2.5문제

---

src/weekly17/nanii/programmers/로또의최고순위와최저순위.ts
src/weekly17/nanii/programmers/숫자문자열과영단어.ts
src/weekly18/nanii/programmers/이모티콘할인행사.ts

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/77484)
> Example 1
```js
Input : lottos = [44, 1, 0, 0, 31, 25], win_nums = [31, 10, 45, 1, 6, 19]
Output : [3, 5]
```
> Example 2
```js
Input : lottos = [0, 0, 0, 0, 0, 0], win_nums = [38, 19, 20, 40, 15, 25] 
Output : [1, 6]
```
> Example 3
```js
Input : lottos = [45, 4, 35, 20, 3, 9], win_nums = [20, 9, 3, 45, 4, 35]
Output : [1, 1]
```
1. 주어진 로또 배열을 순회하면서 0일경우 : 당첨이 될 수도있고, 안될 수 도 있는 경우이므로 `zero`값을 ++
2. 0이 아닌경우 당첨 번호 배열에 값이 있으면 맞췄기때문에 `count`값을 ++합니다.
3. 당첨이 가능한 최고순위는 zero 변수에 담긴 경우의 수가 모두 당첨 번호일 경우 이므로 count + zero 의 값을 구하고,
4. 최저순위는 zero가 0일 때 이므로 count의 값만 구합니다.
5. 로또 순위가 1등의 경우 6개, 2등은 5개, 3등은 4개... 등수와 맞춘 개수의 합이 7이라는 규칙을 이용해 정답 배열을 반환합니다.
---
- 출처 : [programmers - …

Nanii / 17-18주차 / 2.5문제

---

src/weekly19/litae/programmers/[1차] 다트게임.js
src/weekly19/litae/programmers/실패율.js

- [[PGS] 실패율](https://school.programmers.co.kr/learn/courses/30/lessons/42889)
> Example 1
```
N: 5
stages: [2, 1, 2, 6, 2, 4, 3, 3]
result: [3,4,2,1,5]
```
> Example 2
```
N: 4
stages: [4,4,4,4,4]
result: [4,1,2,3]
```
1. 반복문을 돌면서 filter를 통해 스테이지별 실패율(userInStage / playedUser)을 구해 resultArray에 넣는다
2. map으로 value와 index를 가진 객체를 만들고, sort로 내림차순 정렬(value를 기준)
3. 객체의 index에 1을 더해(index는 0부터 세기 때문) 리턴
- [[PGS] 1차 다트게임](https://school.programmers.co.kr/learn/courses/30/lessons/17682)
> Example 1
```
dartResult: 1S2D*3T
answer: 37
설명: 11 * 2 + 22 * 2 + 33
```
> Example 2
```
N: 1D2S#10S
stages: 9
result: 12 + 21 * (-1) + 101
```
> Example 3
```
N: 1D2S0T
stages: 3
result: 12 + 21 + 03
```
1. 점수가 10점인 경우가 있기 때문에 i-1이 1이고 i가 숫자면 10점으로 처리
2. 보너스가 "S", "D", "T"일 때 각각 조건문으로 처리
3. 옵션이 "*", "#"일 때 …

litae / 19주차 / 2문제

---

src/weekly19/poco/programmers/다트게임.js
src/weekly19/poco/programmers/실패율.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/42889))
N : 전체 스테이지의 개수
stages : 게임을 이용하는 사용자가 현재 멈춰있는 스테이지의 번호가 담긴 배열
실패율이 높은 스테이지부터 내림차순으로 스테이지 번호가 담긴 배열 return
전체 스테이지 개수가 주어지고, 각 사용자가 멈춰있는 스테이지 번호가 담긴 배열이 주어질 때,
각 스테이지의 실패율을 구하고, 실패율을 기준으로 내림차순으로 스테이지 번호가 담긴 번호를 return 하는 문제
실패율 계산은 아직 클리어하지 못한 플레이어 수 / 스테이지에 도달한 플레이어 수로 한다
만약 스테이지에 도달한 유저가 없는 경우 해당 스테이지의 실패율은 0으로 정의한다
각 스테이지별로 실패한 사람과 실패율을 구하고 각 실패율을 key로 하고 value를 스테이지 번호를 갖는 배열로 하는
객체 obj를 만들어 주었다
전체 stage별로 모든 실패율을 계산한 뒤, obj 객체의 key를 내림차순 정렬하고, value에 있는 스테이지 번호들을 return해서 해결
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/17682))
dartResult : 점수|보너스|[옵션]으로 이루어진 문자열 3세트
최종 점수
다트를 세 차례 던져 점수의 합계로 순위를 정한다
각 기회마다 얻을 수 있는 점수는 0점에서 10점까지
s, d, t 영역이 있고 각각 1제곱, 2제곱, 3제곱으로 점수가 계산
스타상(*) …

Poco / 19주차 / 2문제

---

src/weekly19/den/programmers/[1차]다트게임.ts
src/weekly19/den/programmers/실패율.ts

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/17682)
> Example 1
```js
Input: 1S2D*3T
Output: 37
```
> Example 2
```js
Input: 1D2S#10S
Output: 9
```
> Example 3
```js
Input: 1D2S0T
Output: 3
```
1. dartResult 문자열을 split해서, 각 문자열을 for문을 돌면서 파싱한다.
2. 문자가 0~9 숫자면 str 변수에 추가한다.
3. 문자가 S,D,T인지 판별한다. 만약 S,D,T 중 하나라면, 규칙에 맞게 점수를 계산하고 scoreArray 배열에 추가한다. 그리고 str 변수를 초기화한다.
4. 문자가 *인 경우 이전에 던진 두 개의 다트에 대한 보너스를 계산한다. 그리고 scoreArray 배열에서 최근 추가한 2개의 다트에 대해서 2배를 해준다.
5. 문자가 #인 경우 마이너스 배수를 곱해준다.
6. 계산이 모두 완료되면, scoreArray 배열의 모든 값을 더해서 반환한다.
---
- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/42889)
> Example 1
```js
Input: 5, [2, 1, 2, 6, 2, 4, 3, 3]
Output: [3,4,2,1,5]
```
> Example 2
```js
Input: 4, [4,4,4,4,4]
Output: …
```

Den / 19주차 / 2문제

---

src/weekly19/nanii/programmers/다트게임.ts
src/weekly19/nanii/programmers/실패율.ts

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/42889)
N | stages | result
-- | -- | --
5 | [2, 1, 2, 6, 2, 4, 3, 3] | [3,4,2,1,5]
4 | [4,4,4,4,4] | [4,1,2,3]
1. 스테이지 번호를 순서대로 사용자가 멈춰있는 스테이지 번호를 순회하면서 그 번호와 같은 숫자를 카운트하여 `person ++`
2. person / 도달한 인원수로 나눈 값인 실패율과 현재 스테이지 번호를 answer 배열에 넣는다.
3. 다음 스테이지로 넘어갈 때 인원수는 이전에 넣은 person 값을 빼야한다. `total -= person`
4. 스테이지별 실패율을 담은 배열 failureRate를 생성하고, 인덱스 [1]값인 rate를 내림차순으로 정렬한뒤, 인덱스[0]의 값만 포함하는 배열을 반환한다.
---
- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/17682)
> Example 
예제 | dartResult | answer | 설명
-- | -- | -- | --
1 | 1S2D*3T | 37 | 11 * 2 + 22 * 2 + 33
2 | 1D2S#10S | 9 | 12 + 21 * (-1) + 101
3 | 1D2S0T | 3 | 12 + 21 + 03
4 | 1S*2T*3S | 23 | 11 * 2 * 2 + 23 * 2 + 31 …

Nanii / 19주차 / 2문제

---

src/weekly20/den/programmers/뒤에있는큰수찾기.ts
src/weekly20/den/programmers/키패드누르기.ts

- 출처 : (programmers - Lv.1)[https://school.programmers.co.kr/learn/courses/30/lessons/67256]
> Example 1
```js
Input: [1, 3, 4, 5, 8, 2, 1, 4, 5, 9, 5], "right"
Output: "LRLLLRLLRRL"
```
> Example 2
```js
Input: [7, 0, 8, 2, 8, 3, 1, 5, 7, 6, 2], "left"
Output: "LRLLRRLLLRR"
```
> Example 3
```js
Input: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0], "right"
Output: "LLRLLRLLRL"
```
1. 키패드에 올라가 있는 왼쪽, 오른쪽 엄지손가락의 위치를 알고 있어야 되서, 임의로 각 숫자마다 위치 값을 부여했습니다.
```js
const keyPad = {
1: [1, 4],
2: [2, 4],
3: [3, 4],
4: [1, 3],
5: [2, 3],
6: [3, 3],
7: [1, 2],
8: [2, 2],
9: [3, 2],
'*': [1, 1],
0: [2, 1],
'#': [3, 1],
}
```
2. 오른손과 왼손이 고정으로 처리하는 숫자들을 한 배열에 넣어놨습니다.
```js
const leftHandTargetList = [1, 4, 7];
const rightHandTargetList = [3, 6, 9];
```
3. 각 손의 초기 위치 값을 부여하고 변수화 했습니다.
```js
let leftHandPosition = …
```

Den / 20주차 / 2문제

---

src/weekly20/poco/programmers/뒤에있는큰수찾기.js
src/weekly20/poco/programmers/키패드누르기.js

- 출처 : [링크](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
매개변수
numbers : 정수로 이루어진 배열
출력
모든 원소에 대한 뒷 큰수들을 차례로 담은 배열 return
문제 설명 및 해결
배열의 각 원소들에 대해 자신보다 뒤에 있는 숫자 중에서
자신보다 크면서 가장 가까이 있는 수를 뒷 큰수라고 한다
뒷 큰수가 존재하지 않는 경우에는 -1을 담는다
실패한 풀이 이후에 구글링 및 블로그 통해서 공부
스택이 비었다면 numbers의 인덱스를 넣어줍니다.
스택에 원소가 하나라도 있고, numbers[스택의 끝 원소인 인덱스]가 현재 탐색한 numbers의 원소보다 작다면,
answer[stack에서 pop한 인덱스]를 현재 탐색한 numbers의 원소로 바꿔줍니다.
이 조건이 만족할 경우 계속 반복해줍니다.
---
- 출처 : [링크](https://school.programmers.co.kr/learn/courses/30/lessons/67256)
매개변수
numbers : 순서대로 누를 번호가 담긴 배열
hand : 왼손잡이인지, 오른손 잡이인지
출력
numbers의 각 번호를 누를때의 엄지손가락이 왼손인지 오른손인지를 나타내는 str
문제 설명 및 해결
키패드를 누른다고 가정했을 때,
1, 4, 7는 왼손으로, 3, 6, 9 오른손으로 누른다
그외 2, 5, 8, 0의 경우 눌러야하는 번호와 가까운 손을 사용한다
거리가 같은 경우, hand로 주어진 주 사용 손으로 누른다
키패드와 동일한 모양의 2차원 배열을 먼저 선언하고 …

Poco / 20주차 / 1.5 문제

---

src/weekly20/litae/programmers/뒤에 있는 큰 수 찾기.js
src/weekly20/litae/programmers/키패드 누르기.js

- [[PGS] 뒤에 있는 큰 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
> Example 1
```
numbers: [2, 3, 3, 5]
result: [3, 5, 5, -1]
```
> Example 2
```
numbers: [9, 1, 5, 3, 6, 2]
result: [-1, 5, 6, 6, -1, -1]
```
1. numbers와 같은 크기의 배열을 만들고 모든 값을 -1로 초기화
2. 스택 배열(초기값 빈배열)
- [[PGS] 키패드 누르기](https://school.programmers.co.kr/learn/courses/30/lessons/67256)
> Example 1
```
numbers: [1, 3, 4, 5, 8, 2, 1, 4, 5, 9, 5]
hand: "right"
result: "LRLLLRLLRRL"
```
> Example 2
```
numbers: [7, 0, 8, 2, 8, 3, 1, 5, 7, 6, 2]
hand: "left"
result: "LRLLRRLLLRR"
```
> Example 3
```
numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
hand: "right"
result: "LLRLLRLLRL"
```
1. 키패드의 위치를 객체와 배열을 사용하여 좌표를 만든다
2. 손가락의 위치를 초기화
3. 조건문을 통해 키패드가 1, 4, 7일 경우 왼손("L")을 result에 추가하고, 키패드가 3, 6, 9일 경우 오른손("R")을 추가
4. …

litae / 20주차 / 2문제 

---

src/weekly20/nanii/programmers/뒤에있는큰수찾기.ts

- 출처 : [프로그래머스 - Lv1](https://school.programmers.co.kr/learn/courses/30/lessons/154539#)
> Example 
numbers | result
-- | --
[2, 3, 3, 5] | [3, 5, 5, -1]
[9, 1, 5, 3, 6, 2] | [-1, 5, 6, 6, -1, -1]
1. 주어진 `numbers` 배열을 순회하면서 다음 인덱스 값을 비교합니다.
2. `indexStack`에 뒷큰수를 만났을 때의 인덱스값을 담고, `answer` 인덱스스택에 마지막으로 넣은 인덱스 값에 현재 `numbser[i]`값을 담습니다.
3. 뒷큰수를 만나지 않았을 경우 `answer`에 -1을 담아 `answer`배열을 반환합니다.

Nanii / 20주차 / 1문제

---

src/weekly22/den/programmers/나머지가1이되는수찾기.ts

- 출처 : [programmers - Lv.1](https://school.programmers.co.kr/learn/courses/30/lessons/87389)
> Example 1
```js
Input: 10 
Output: 3
```
> Example 2
```js
Input: 12
Output: 11
```
매개변수 n에 대해서 x를 나눈 나머지가 1이 되는 x를 찾을 때 까지 while문을 돌았습니다.
x를 찾으면 x를 return 합니다.
첫 번째 시도 때 재귀로 문제를 풀었습니다. 근데 첫 번째 케이스에서 런타임 에러가 발생해서, 고민 해봤지만  원인을 못 찾았습니다.
```js
function solution(n: number, x = 2): number {
return n % x === 1 ? x : solution(n, x += 1)
}
```
--- 
1시간 30분 가량 고민 했지만, 푸는데 실패했습니다.

Den / 22주차 / 1문제

---

src/weekly22/litae/programmers/나머지가 1이 되는 수 찾기.ts
src/weekly22/litae/programmers/호텔 대실.ts

- [[PGS] 나머지가 1이 되는 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/87389)
> Example 1
```
n: 10
result: 3
```
> Example 2
```
n: 12
result: 11
```
1부터 n까지 반복문을 돌면서 조건을 만족하는 경우(n을 x로 나눈 나머지가 1이 되는 경우) x를 리턴

litae / 22주차 / 1문제

---

src/weekly23/poco/leetCode/1512_NumberofGoodPairs.js
src/weekly23/poco/programmers/호텔대실.js

- 출처 : https://leetcode.com/problems/number-of-good-pairs/
nums : 정수로 이루어진 배열
good pairs의 갯수
문제에서 말하는 good pairs란?
nums[i] === nums[j]이고 i < j 일때, i와 j
obj 객체를 선언하고 nums 배열 요소를 순회하면서
obj의 키값과 일치하는지 확인하고, 일치하는 내용이 이미 있다면 해당 key 값의 배열의 길이를 answer에 더해준다.
일치하는 내용이 없다면 해당 key 값의 배열에 요소를 추가해준다.
---
- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/155651
book_time : 예약 시각이 문자열 형태로 담긴 2차원 배열
코니에게 필요한 최소 객실의 수
호텔을 운영 중인 코니는 최소한의 객실만을 사용하여 예약 손님들을 받으려고 합니다.
한 번 사용한 객실은 퇴실 시간을 기준으로 10분간 청소를 하고 다음 손님들이 사용할 수 있습니다.
예약 시각이 문자열 형태로 담긴 2차원 배열 book_time이 매개변수로 주어질 때, 코니에게 필요한 최소 객실의 수를 return 하는 solution 함수를 완성해주세요.
먼저 매개변수 book_time을 오름차순으로 정렬한다.
그리고 각 예약 시작 시간을 앞선 예약들의 대실 종료 시간들과 비교하면서, 대실 종료 시간보다 예약 시작 시간이 빠르다면, 새로운 예약의 종료시간을 room 배열에 추가
반대로 예약 시간 보다 대실 종료 시간이 빠르다면, 대실 종료 시간을 새로운 예약의 …

Poco / 23주차 / 2문제

---

src/weekly23/litae/leetcode/1512. Number of Good Pairs.ts
src/weekly23/litae/programmers/호텔 대실.ts

- [[LTC]1512. Number of Good Pairs](https://leetcode.com/problems/number-of-good-pairs/)
> Example 1
```
Input: nums = [1,2,3,1,1,3]
Output: 4
Explanation: There are 4 good pairs (0,3), (0,4), (3,4), (2,5) 0-indexed.
```
> Example 2
```
Input: nums = [1,1,1,1]
Output: 6
Explanation: Each pair in the array are good.
```
> Example 3
```
Input: nums = [1,2,3]
Output: 0
```

litae / 23주차 / 1문제

---

src/weekly23/nanii/leetCode/1512.NumberOfGoodPairs.ts

- 출처 : [leetcode - lv.1](https://leetcode.com/problems/number-of-good-pairs/)
> Example 1
```js
Input: [1,2,3,1,1,3]
Output: 4
```
> Example 2
```js
Input: [1,1,1,1]
Output: 6
```
> Example 3
```js
Input: [1,2,3]
Output: 0
``` 
- 주어진 배열을 순회하면서 값이 같을 때를 카운트합니다.
- map을 활용하여 value가 같은 key가 있는경우에는 해당 value 를 꺼내 +1을 하고
- 그렇지 않을 경우에는 1을 더합니다.
- 최종 answer를 반환합니다.

Nanii / 23주차 / 1문제

---

src/weekly24/den/leetcode/704_BinarySearch.ts

- 출처 : [leetcode - easy](https://leetcode.com/problems/binary-search/description/)
> Example 1
```js
Input: [-1,0,3,5,9,12], 9
Output: 4
```
> Example 2
```js
Input:  [-1,0,3,5,9,12], 2
Output: -1
```
Input으로 받은 배열 내에 target이 있는지 여부를 확인 하는 문제다. O(log n) 시간 복잡도 내에 확인이 가능한 로직을 구현하는 것이 문제의 조건이다.
이를 이행하기 위해 우선, start를 0으로 선언하고, end를 배열의 길이에 1을 뺀 값으로 선언한다.
그리고 start가 end 보다 커지기 전 까지 while문을 돌면서 start와 end를 더하고 2를 나눈 mid를 계산한다.
계산된 mid를 배열에 indexing해서 target인지 여부를 확인한다.
만약 indexing한 값이 mid이면 바로 return 하고, target 보다 작으면 start 값을 mid에 1을 더한 값으로 재할당 한다음에 다음 루프를 돈다.
target 보다 크면, end를 mid에 1을 뺀 값으로 재할당한 뒤에 반복문을 돈다.
이렇게 반복문을 돌면서 input 배열에 target이 있는지 여부를 확인하고, 있으면 해당 target이 있는 index를 반환하고, 없으면 -1을 반환한다.

Den / 24주차 / 1문제

---

src/weekly24/litae/leetcode/2627. Debounce.ts
src/weekly24/litae/leetcode/704. Binary Search.ts

- [[LTC] 704. Binary Search](https://leetcode.com/problems/binary-search/)
> Example 1
```
Input: nums = [-1,0,3,5,9,12], target = 9
Output: 4
Explanation: 9 exists in nums and its index is 4
```
> Example 2
```
Input: nums = [-1,0,3,5,9,12], target = 2
Output: -1
Explanation: 2 does not exist in nums so return -1
```
1. indexOf를 이용하여 target이 nums 배열에 존재하면 해당 배열의 인덱스를 반환하고 배열 내에 존재하지 않을 경우 -1을 반환
- [[LTC] 2627. Debounce](https://leetcode.com/problems/debounce/)
> Example 1
```
Input: 
t = 50
calls = [
{"t": 50, inputs: [1]},
{"t": 75, inputs: [2]}
]
Output: [{"t": 125, inputs: [2]}]
```
> Example 2
```
Input: 
t = 20
calls = [
{"t": 50, inputs: [1]},
{"t": 100, inputs: [2]}
]
Output: [{"t": 70, inputs: [1]}, {"t": 120, inputs: [2]}]
```
> Example 3
```
Input: 
t = 150
calls = [
{"t": 50, …
```

litae / 24주차 / 2문제

---

src/weekly24/poco/leetCode/BinarySearch.js
src/weekly24/poco/leetCode/Debounce.js

- 출처 : https://leetcode.com/problems/binary-search/
매개변수
nums : 정렬된 배열
target : 찾고자 하는 값
출력
target의 인덱스
문제 해결 및 설명
오름차순으로 정렬된 배열 nums와 target이 주어지고, target의 idx를 구하는 문제
문제 요구사항에서 시간 복잡도는 logN을 요구하고 있고, 이진 탐색을 구현하는 문제
이진 탐색은 배열의 중간 값을 기준으로 탐색 범위를 좁혀가며 값을 찾는 알고리즘
추가로 좁혀진 범위에 대해서 확인하는 방법으로는 재귀를 사용
재귀의 탈출 조건은 nums의 길이가 0일때, pivot과 target이 같은 경우이고,
만약 현재 pivot보다 target이 큰 경우에는 pivot의 오른쪽을 탐색하는데, 그 결과 값 idx에는
현재 pivotIdx + 1을 더해준다(최초 nums에서의 idx를 찾아야하기 때문)
---
- 출처 : https://leetcode.com/problems/debounce/
매개변수
fn : 실행할 함수
t : 지연시간
출력
지연된 함수
문제 해결 및 설명
실행할 함수 fn과 지연시간 t가 주어지고, 지연된 함수를 반환하는 문제
지연된 함수는 t시간이 지나기 전에 호출되면 호출이 취소되고, t시간이 지난 후에 호출된다.
지연된 함수는 매개변수를 받아서 실행할 함수에 전달한다.
즉, 함수가 호출이되고, t시간이 지나기 전에 다시 호출이 되면, 이전에 호출된 함수는 취소되고, t시간이 지난 후에 호출
이를 구현하기 위해서는 setTimeout과 clearTimeout을 사용했음
그럼 매개변수에 …

Poco / 24주차 / 1.5 문제

---

src/weekly24/nanii/leetCode/704_BinarySearch.ts

- 출처 : [leetcode - easy](https://leetcode.com/problems/binary-search/description/)
> Example 1
```js
Input: [-1,0,3,5,9,12], 9
Output: 4
```
> Example 2
```js
Input:  [-1,0,3,5,9,12], 2
Output: -1
```
배열의 findIndex메서드를 사용합니다
- [[LTC] 2627. Debounce](https://leetcode.com/problems/debounce/)
> Example 1
```
Input: 
t = 50
calls = [
{"t": 50, inputs: [1]},
{"t": 75, inputs: [2]}
]
Output: [{"t": 125, inputs: [2]}]
```
> Example 2
```
Input: 
t = 20
calls = [
{"t": 50, inputs: [1]},
{"t": 100, inputs: [2]}
]
Output: [{"t": 70, inputs: [1]}, {"t": 120, inputs: [2]}]
```
> Example 3
```
Input: 
t = 150
calls = [
{"t": 50, inputs: [1, 2]},
{"t": 300, inputs: [3, 4]},
{"t": 300, inputs: [5, 6]}
]
Output: [{"t": 200, inputs: [1,2]}, {"t": 450, inputs: [5, 6]}]
```

Nanii / 24주차 / 1문제

---

src/weekly25/den/leetcode/120_Triangle.ts
src/weekly25/den/leetcode/242_ValidAnagram.ts

- 출처 : [leetcode - easy](https://leetcode.com/problems/valid-anagram/description/)
> Example 1
```js
Input: s = "anagram", t = "nagaram"
Output: true
```
```js
Input: s = "rat", t = "car"
Output: false
```
Input으로 들어오는 두 문자열이 각각 재정렬시 같은 문자열이 되는지 여부를 확인하는 문제입니다.
이를 위해서 문자열 s를 순회하며 각 문자를 객체에 1과 함께 저장하고, 이미 저장되어 있으면 기존 value에 1씩 증가시킵니다.(스택의 형태)
그 다음 문자열 t를 순회하며 객체에 이미 있는 문자열이면, 기존 value에 1을 빼고, 만약 아예 없는 문자열이면 문자열 s에 일치하는 문자열이 없는 문자열이기 때문에 anagram이 아니여서 false를 Return 합니다.
최종적으로 false를 Return하지 않고 반복문을 순환이 모두 끝나면 두 문자열이 anagram 관계라는 것이 증명되기 때문에 true를 반환합니다.
--- 
- 출처 : [leetcode - easy](https://leetcode.com/problems/valid-anagram/description/)
> Example 1
```js
Input: triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]
Output: 11
```
```js
Input: triangle = [[-10]]
Output: -10
```
Input으로 들어오는 2차원 배열을 …

Den / 25주차/ 1문제 

---

src/weekly25/poco/leetCode/120_Triangle.js
src/weekly25/poco/leetCode/242_ValidAnagram.js

- 출처 : [(링크)](https://leetcode.com/problems/valid-anagram/)
s : 문자열
t : 문자열
boolean (s와 t가 anagram이면 true, 아니면 false)
문자열 s와 t가 주어지고, s와 t가 anagram이면 true, 아니면 false를 반환하는 문제
anagram이란 문자열을 재배열해서 다른 문자열을 만드는 것을 의미
따라서, s와 t의 길이가 다르면 false를 반환
s와 t를 sorting해서 문자열을 순회하면서 비교하는 방법
hash 테이블 사용해서, 각 문자열 갯수를 비교하는 방법
s, t를 각각 split으로 배열화 및 sorting 후, 순회하면서 비교
---
- 출처 : [(링크)](https://leetcode.com/problems/triangle/)
triangle : 2차원 배열
number (최소 경로의 합)
2차원 배열 triangle이 주어지고, 삼각형의 최소 경로의 합을 반환하는 문제
삼각형의 최소 경로의 합이란, 맨 위에서부터 아래로 내려가면서, 각 행에서 인접한 수로만 이동할 수 있을 때, 최소 경로의 합을 의미
처음에 문제를 잘못 이해하고 풀고, 문제를 다시 이해했을 때에는 DP를 사용해서 풀어야함을 알게되었고
블로그를 보면서 공부했지만 도저히 이해가 되지 않음
최소 경로 합을 구할 때, 바로 다음 row에서의 idx와 idx+1 중에 작은 수를 고르는 문제라고 문제를 잘못 이해함

Poco / 25주차 / 1.5문제

---

src/weekly25/litae/leetcode/120. Triangle.ts
src/weekly25/litae/leetcode/242. Valid Anagram.ts

- [[LTC] 242. Valid Anagram](https://leetcode.com/problems/valid-anagram/)
> Example 1
```
Input: s = "anagram", t = "nagaram"
Output: true
```
> Example 2
```
Input: s = "rat", t = "car"
Output: false
```
- [[LTC] 242. Valid Anagram](https://leetcode.com/problems/triangle/)
> Example 1
```
Input: triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]
Output: 11
Explanation: The triangle looks like:
2
3 4
6 5 7
4 1 8 3
The minimum path sum from top to bottom is 2 + 3 + 5 + 1 = 11 (underlined above).
```
> Example 2
```
Input: triangle = [[-10]]
Output: -10
```

litae / 25주차 / 1문제

---

src/weekly26/nanii/leetCode/104_MaximumDepthOfBinaryTree.ts
src/weekly26/nanii/programmers/카펫.ts

- 출처 : [leetcode - easy](https://leetcode.com/problems/maximum-depth-of-binary-tree/)
> Example 1
```js
Input: root = [3,9,20,null,null,15,7]
Output: 3
```
```js
Input: root = [1,null,2]
Output: 2
```
- binary tree 순회는 1. 재귀 2. 스택 두가지 방법을 이용하는데요
- 이 문제에서 저는 재귀를 사용하여 트리를 순회하였습니다.
- 먼저 root에 값이 있는지 확인한뒤, 왼쪽 노드와 오른쪽 노드를 탐색합니다.
- 이때 depth가 깊어질 수록 1을 증가시키고 왼쪽과 오른쪽 노드중 더 깊은 값을 반환해야되므로 `Math.max` 메서드를 사용하였습니다.
--- 
- 출처 : [programmers-Lv2](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
brown | yellow | return
-- | -- | --
10 | 2 | [4, 3]
8 | 1 | [3, 3]
24 | 24 | [8, 6]
- `brown + yellow` = 배열의 `width * height` 라는 점을 이용하여 문제풀이를 진행하였습니다.
- 노란색이 최소 1, 갈색이 최소 8 이상이므로 이 이중배열의 길이는 최소 3*3 이고, 따라서 이 이중배열에서 height 의 최소값은 3부터 시작합니다.
- 주어진 문제에서 갈색은 노란색을 1줄로 감싸고 있다는 점을 이용하면, yellow의 개수는 …

Nanii / 26주차 / 2문제

---

src/weekly26/poco/leetCode/104_MaximumDepthOfBinaryTree.js
src/weekly26/poco/programmers/카펫.js

- 출처 : ([링크](https://leetcode.com/problems/maximum-depth-of-binary-tree/))
* 매개변수
root : 트리의 루트 노드
* 출력
트리의 최대 깊이
* 문제 해결 및 설명
트리의 최대 깊이를 구하는 문제
트리의 최대 깊이는 루트 노드에서 가장 먼 리프 노드(자식 노드가 없는 노드)까지의 가장 긴 경로를 의미함
트리의 최대 깊이를 구하는 문제이므로, DFS를 사용해서 풀이(재귀 사용)
재귀 탈출 조건은 root(val) 값이 null일 경우 0을 반환하여 재귀를 종료
재귀를 돌면서, 왼쪽 자식 노드와 오른쪽 자식 노드 중에 더 깊은 노드를 선택하여 +1을 해주면서 재귀를 돌아서 최대 깊이를 구함
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/42842?language=javascript))
* 매개변수
brown : 갈색 카펫 갯수
yellow : 노란색 카펫 갯수
* 출력
number[] : 전체 카펫의 가로, 세로 크기
* 문제 해결 및 설명
카펫의 가로, 세로 크기를 구하는 문제
노란색 카펫은 최소 1개이기 때문에, 카펫의 최소 가로, 세로 갯수는 3, 3개이다
갈색 카펫과 노란 카펫을 모두 더해서 전체 카펫의 갯수를 확인하고, 전체 카펫을 i로 나누어서 너비와 높이를 구하고
높이가 너비보다 큰 경우(문제의 조건에서 벗어나느 경우)에는 continue를 통해 다음 반복문으로 넘어가고
높이가 너비보다 작은 경우에는 현재 (너비 -2) * (높이 -2)가 …

Poco / 26주차 / 2문제

---

src/weekly26/den/leetcode/104_MaximumDepthOfBinaryTree.ts
src/weekly26/den/programmers/카펫.ts

- 출처 : [leetcode - easy](https://leetcode.com/problems/maximum-depth-of-binary-tree/)
> Example 1
```js
Input: root = [3,9,20,null,null,15,7]
Output: 3
```
> Example 2
```js
Input: root = [1, null, 2]
Output: 1
```
1. root가 null이면 0을 반환한다.
2. root가 null이 아니면 1을 반환한다.
3. root의 left와 right를 재귀적으로 호출한다.
4. left와 right 중 큰 값을 반환한다.
---
- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
> Example 1
```js
Input: 10, 2
Output: [4, 3]
```
> Example 2
```js
Input: [8, 1]
Output: [3, 3]
```
> Example 3
```js
Input: [24, 24]
Output: [8, 6]
```
1. width 와 height의 곱은 brown과 yellow의 합이다.
brown + yellow = width * height
2. 아래와 같이 height와 width에 각각 2를 빼서 곱한 값이 yellow다.
(height - 2) * (width - 2) = yellow
3. 위 2개의 수식을 이용해서 for문을 돌며 알맞은 height 값과 width 값을 찾으면 반환한다.

Den / 26주차 / 2문제

---

src/weekly26/litae/leetcode/104. Maximum Depth of Binary Tree.ts
src/weekly26/litae/programmers/카펫.ts

- [[LTC]104. Maximum Depth of Binary Tree](https://leetcode.com/problems/maximum-depth-of-binary-tree)
> Example 1
```
Input: root = [3,9,20,null,null,15,7]
Output: 3
```
> Example 2
```
Input: root = [1,null,2]
Output: 2
```
1. 노드가 존재하지 않을 때까지 recursion(재귀함수)를 실행
2. 노드의 깊이가 깊어질수록 depth + 1
3. 가장 깊이가 깊은(depth가 큰) 수를 리턴
- [[PGS] 카펫](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
> Example 1
```
brown: 10
yellow: 2
return: [4, 3]
```
> Example 2
```
brown: 8
yellow: 1
return: [3, 3]
```
> Example 3
```
brown: 24
yellow: 24
return: [8, 6]
```
1. 노란색 영역의 세로 크기를 i로 하는 for문
2. '카펫의 가로 길이는 세로 길이와 같거나, 세로 길이보다 깁니다' 조건을 만족하기 위해 i <= Math.sqrt(yellow) 조건 설정
3. yellow / i의 값이 yellow의 약수인 경우(yellow % i === 0) 
4. (가로 크기 + 세로 크기) * 2 + vertex(꼭지점)의 값이 brown과 같으면
5. 해당 [가로 크기, 세로 …

litae / 26주차 / 2문제

---

src/weekly27/den/leetcode/22_GenerateParentheses.ts
src/weekly27/den/programmers/피로도.js

- 출처 : [leetcode - medium](https://leetcode.com/problems/generate-parentheses/)
> Example 1
```js
Input: 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```
> Example 2
```js
Input: 1
Output: ["()"]
```
DP, Backtracking 유형의 문제인데, 재귀를 이용해서 풀고자 했습니다. 
고민 끝에 풀었지만, 통과를 못 해서 다른분들 풀이를 참고해서 풀었습니다.
1. 재귀를 통해 모든 경우의 수를 구한다.
2. 왼쪽 괄호가 n개, 오른쪽 괄호가 n개가 될 때까지 재귀를 돌린다.
3. left > 0 이면, 왼쪽 괄호를 추가한다.
4. right > left 이면, 오른쪽 괄호를 추가한다.(오른쪽 괄호가 왼쪽 괄호보다 많을 수 없다.)
5. left === 0 && right === 0 이면, 결과에 추가한다.
6. 3 ~ 5 과정을 반복한다.
7. 결과를 반환한다.
핵심은 Input 1, 2, 3일 때 출력 값 패턴을 분석해서 한글로 옮겨 놓고, 이를 코드로 풀어나가야 될 것 같은데, 아직도 많이 어렵습니다.
--- 
- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/87946)
> Example 1
```js
Input: 80, [[80, 20], [50, 40], [30, 10]]
Output: 3
```
완전탐색 유형의 문제인데, …

Den / 27주차 / 1.5문제

---

src/weekly27/litae/leetcode/22. Generate Parentheses.ts
src/weekly27/litae/programers/피로도.ts

- [[LTC] 22. Generate Parentheses](https://leetcode.com/problems/generate-parentheses)
> Example 1
```
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```
> Example 2
```
Input: n = 1
Output: ["()"]
```
- [[PGS] 피로도](https://school.programmers.co.kr/learn/courses/30/lessons/87946)
> Example 1
```
k: 80
dungeons: [[80,20],[50,40],[30,10]]
result: 3
```

litae / 27주차 / 1문제

---

src/weekly27/nanii/leetCode/22_GenerateParentheses.ts

- 출처 : [leetcode - medium](https://leetcode.com/problems/generate-parentheses/)
> Example 1
```js
Input: 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```
> Example 2
```js
Input: 1
Output: ["()"]
```
1. 주어진 숫자로 괄호의 쌍을 조합하는 문제입니다.
2. 여러 경우의 수를 생각하여 문자열을 조합하는 문제이므로 재귀방법을 선택하였습니다. (이전의 [소수찾기](https://school.programmers.co.kr/learn/courses/30/lessons/42839) 풀이느낌으로)
3. `여는 괄호를 +1` , `닫는 괄호를 -1` 이라 했을 때 `괄호의 쌍이 맞을 때 합이 0` 임을 이용합니다.
4. 재귀함수 combination 의 매개변수로 `여는 괄호의 수`, `닫는 괄호의 수`, `조합된 문자열`로 받습니다.
5. 이때 확인해야되는 조건은 여는 괄호의 수가 더 클 경우, 닫는 괄호의 수가 더 클 경우, 열고 닫는 괄호의 수가 모두 0이 된 경우를 확인합니다.
6. 여는 괄호의 수가 더 클 경우에는 open 매개변수의 값을 -1 하고, 여는 괄호를 조합된 문자열에 더합니다. 닫는 괄호도 마찬가지로 close 매개변수의 값을 -1 하고, 닫는 괄호를 조합된 문자열에 더합니다.
7. 마지막으로 open, close 매개변수의 값이 모두 0이 되었을 때 조합된 문자열이 모두 완성되었으므로 result 배열에 push …

Nanii / 27주차 / 1문제

---

src/weekly28/litae/leetcode/567. Permutation in String.ts
src/weekly28/litae/leetcode/62. Unique Paths.ts

- [[LTC] 62. Unique Paths](https://leetcode.com/problems/unique-paths)
> Example 1
```
Input: m = 3, n = 7
Output: 28
```
> Example 2
```
Input: m = 3, n = 2
Output: 3
Explanation: From the top-left corner, there are a total of 3 ways to reach the bottom-right corner:
1. Right -> Down -> Down
2. Down -> Down -> Right
3. Down -> Right -> Down
```
1. 그리드의 크기가 1*1인 경우 1을 리턴
2. width의 같은 크기의 currRow 배열을 생성하고 모든 요소를 1로 초기화(중간 결과를 저장하는 용도)
3. 2차원 그리드에서 각 셀마다 왼쪽 셀과 위쪽 셀의 값을 누적하여 경로의 수를 계산
4. 마지막 행의 마지막 셀(오른쪽 하단)에 저장된 값이 전체 그리드의 경로의 수
- 크기가 7*3인 그리드
- 초기 상태: currRow = [1, 1, 1, 1, 1, 1, 1]
- 2번째 행(높이 2): 왼쪽 셀과 누적하여 업데이트
currRow[1] += currRow[0]: 1 + 1 = 2
currRow[2] += currRow[1]: 1 + 2 = 3
currRow[3] += currRow[2]: 1 + 3 = 4
currRow[4] += currRow[3]: 1 + 4 = 5
currRow[5] += currRow[4]: 1 + 5 = 6 …

litae / 28주차 / 1문제

---

src/weekly28/nanii/leetCode/567_Permutation in String.ts
src/weekly28/nanii/leetCode/62_Unique Paths.ts

- 출처 : [leetcode - medium](https://leetcode.com/problems/unique-paths/)
> Example 1
```js
Input: m = 3, n = 7
Output: 28
```
> Example 2
```js
Input: m = 3, n = 2
Output: 3
```
1. 이중배열의 `[0,0]`에서 `[m-1,n-1]`로 이동하는 경우의 수를 구하는 문제이다.
2. 시작점에서 오른쪽 또는 아래쪽으로만 이동 가능하므로 한칸씩 이동할 때마다 이동 지점에 +1 해야한다.
3. 그러기 위해 이중배열의 초기값을 1로 채운다.
4. 이중배열을 순회하면서 현재지점의 위쪽값`path[i-1][j]`과 왼쪽값`path[i][j-1]`을 더하면서 이중배열을 채워나가고, 배열의 마지막 인덱스`[m-1,n-1]` 값을 반환한다.
--- 
- 출처 : [leetcode - medium](https://leetcode.com/problems/permutation-in-string/)
> Example 1
```js
Input: s1 = "ab", s2 = "eidbaooo"
Output: true
```
> Example 2
```js
Input: s1 = "ab", s2 = "eidboaoo"
Output: false
```
1. 처음에는 단순히 모든 순열 조합을 중복없이 생성한 다음, s2에서 순열 조합을 순회하면서 값을 포함하는 지 안하는 지 확인했었다. 하지만 s1의 값이 길어졌을 때 모든 순열 조합을 생성하는 게 무리였다. 이럴땐 `슬라이딩윈도우` 알고리즘을 이용해야한다. …

Nanii / 28주차 / 2문제

---

src/weekly28/den/leetcode/62_UniquePaths.ts

- 출처 : [leetcode - medium](https://leetcode.com/problems/unique-paths/)
> Example 1
```js
Input: 3, 7
Output: 28
```
> Example 2
```js
Input: 3, 2
Output: 3
```
이 문제는 grid 상에서 왼쪽 상단 끝에서 오른쪽 하단 끝으로 이동할 수 있는 모든 경우의 수를 구하는 문제다. (단, 오른쪽과 밑으로만 이동할 수 있다.)
예시를 통해 경로를 구해보면, 2가지를 유추할 수 있다.
1. 테두리 칸 = 갈 수 있는 경우의 수 = 1
2. 나머지 칸 = 왼쪽 칸 + 위쪽 칸
m = 2, n = 7 일 때,
// 1 1 1 1 1 1 1
// 1 2 3 4 5 6 7
총 경로: 7
m = 3, n = 7 일 때,
// 1 1 1 1 1 1 1
// 1 2 3 4 5 6 7
// 1 3 6 10 15 21 28
총 경로: 28
이를 점화식으로 표현하면, `dp[i][j] = dp[i - 1][j] + dp[i][j - 1]`이다. 
기본적으로 테두리 칸들은 전부 1이기 때문에, 세로 길이가 m이고 가로길이가 n인데 요소는 1인 2차원 배열을 만들고, 나머지 칸들은 점화식에 따라 값을 채워야 되기 때문에, 2중 for문을 활용해서 값을 바꿔치면 된다.

Den / 28주차 / 1문제

---

src/weekly29/litae/leetcode/1143. Longest Common Subsequence.ts

- [[LTC] 1143. Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence/)
> Example 1
```
Input: text1 = "abcde", text2 = "ace" 
Output: 3  
Explanation: The longest common subsequence is "ace" and its length is 3.
```
> Example 2
```
Input: text1 = "abc", text2 = "abc"
Output: 3
Explanation: The longest common subsequence is "abc" and its length is 3.
```
> Example 1
```
Input: text1 = "abc", text2 = "def"
Output: 0
Explanation: There is no such common subsequence, so the result is 0.
```

litae / 29주차 / 1문제

---

src/weekly29/den/leetcode/1143_logestCommonSubsequence.ts
src/weekly29/den/leetcode/695_maxAreaOfIsland.ts

- 출처 : [leetcode - medium](https://leetcode.com/problems/max-area-of-island/description/)
> Example 1
```js
Input: grid = [[0,0,1,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,1,1,0,1,0,0,0,0,0,0,0,0],[0,1,0,0,1,1,0,0,1,0,1,0,0],[0,1,0,0,1,1,0,0,1,1,1,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,0,0,0,0,0,0,1,1,0,0,0,0]]
Output: 6
```
> Example 2
```js
Input: grid = [[0,0,0,0,0,0,0,0]]
Output: 6
```
2차원 배열인 grid에서 제일 큰 섬의 크기가 몇 인지 구하는 문제 입니다.
이를 구하기 위해서 2차원 배열을 순회하며 1인(섬) 칸을 만났을 때, 이 칸과 인접해 있는 모든 칸을 순회하며 이 섬이 얼마나 큰지 구하고, 이전 섬과 비교해서 더 큰 섬인지 판별해야 됩니다.
섬의 자료구조는 2차원 배열이기 때문에,  dfs를 이용했습니다.
- 출처 : [leetcode - medium](https://leetcode.com/problems/longest-common-subsequence/)
> Example 1
```js
Input: "abcde"
Output: "ace"
```
> Example 2
```js
Input: "abc"
Output: "abc" …
```

Den / 29주차 / 1.5문제

---

src/weekly30/den/programmers/전화번호목록.ts
src/weekly30/den/programmers/주식가격.ts

- 출처 : [programmers - Lv.2](https://programmers.co.kr/learn/courses/30/lessons/42584)
> Example 1
```js
Input: [1, 2, 3, 2, 3]
Output: [4, 3, 1, 1, 0]
```
매초 변하는 주식가격을 담은 배열이 입력 값으로 들어오면, 각각의 주식가격이 몇 초 동안 떨어지지 않고 유지 또는 오르는지 구하는 문제입니다. 가격이 떨어지는 순간, 측정을 종료합니다.
1. 각각의 주식가격이 매 초 지날 때마다 가격을 유지하거나 오르면 유지시간을 1초씩 늘립니다.
2. 가격이 떨어지면 1초 늘리고 측정을 종료합니다.
3. 마지막 시간의 가격은 더 오르거나 떨어질 일이 없으므로, 0초가 됩니다.
---
- 출처 : [programmers - Lv.2](https://programmers.co.kr/learn/courses/30/lessons/42577)
> Example 1
```js
Input: ["119", "97674223", "1195524421"]
Output: false
```
> Example 2
```js
Input: ["123", "456", "789"]
Output: true
```
> Example 3
```js
Input: ["12", "123", "1235", "567", "88"]
Output: false
```
입력 값으로 들어오는 전화번호 배열 요소 중에 번호가 다른 번호의 접두사가 있는 경우를 구하는 문제 입니다.
입력값의 범위가 아래와 같이 엄청 커서, 로직의 효율성을 신경써야 되는 …

Den / 30주차 / 2문제

---

src/weekly30/nanii/programmers/전화번호목록.ts
src/weekly30/nanii/programmers/주식가격.ts

- 출처 : [programmers - Lv.2](https://programmers.co.kr/learn/courses/30/lessons/42584)
> Example 1
```js
Input: [1, 2, 3, 2, 3]
Output: [4, 3, 1, 1, 0]
```
1. prices 배열을 순회하면서 주식가격이 떨어졌을 때 그 시점의 인덱스를 배열에 담아 반환합니다.
2. 먼저 answer배열에 sec를 담기위해 주어진 배열의 길이 만큼 0으로 채웁니다.
3. 각 인덱스에 위치한 value를 기준으로 마지막 인덱스까지 비교했을 때 value가 떨어지기 전까지의 시간을 계산합니다.`answer[i]++`
4. 기준 인덱스의 값이 떨어지면 다음 텀으로 넘어가기 위해서 break를 반환하여 answer 배열을 완성시킵니다.
---
- 출처 : [programmers - Lv.2](https://programmers.co.kr/learn/courses/30/lessons/42577)
> Example 1
```js
Input: ["119", "97674223", "1195524421"]
Output: false
```
> Example 2
```js
Input: ["123", "456", "789"]
Output: true
```
> Example 3
```js
Input: ["12", "123", "1235", "567", "88"]
Output: false
```
1. 접두어로 사용되는 경우가 있는지 확인하기 위해 먼저 오름차순으로 정렬합니다. (이때 length순으로 정렬되기때문에 비교하기 쉬워짐) …

Nanii / 30주차 / 2문제

---

src/weekly30/poco/programmers/전화번호목록.js
src/weekly30/poco/programmers/주식가격.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/42577))
phone_book : 전화번호부에 적힌 전화번호를 담은 배열
어떤 번호가 다른 번호의 접두사가 되는 번호가 있으면 false, 없으면 true
어떤 번호가 다른 번호에 포함되는지 여부가 아닌 접두사인지 여부를 확인하는 문제
따라서, sort 메서드로 전화번호를 정렬시킨 후 for문을 통해 i + 1 번째의 번호가
i 번째 번호를 접두사로 갖는지 확인하면 된다.
시간복잡도 : O(nlogn)
처음 startsWith 메서드 대신 includes를 사용했는데, 접두사가 아니라 포함되는지 여부를 확인하는 메서드이므로
테스트 코드 13번 실패 따라서, 접두사 여부를 확인할 수 있는 startsWith 메서드 사용
그리고 for문을 돌리는 범위를 배열의 맨 마지막 인수를 i + 1번째 값이 없기 때문에
sortedPhoneBook.length - 1로 설정해야한다.
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/42584))
prices : 초 단위로 기록된 주식가격이 담긴 배열
가격이 떨어지지 않은 기간은 몇 초인지를 담은 배열
초 단위로 기록된 주식 가격이 담긴 배열이 주어지고, 가격이 떨어지지 않은 기간은 몇 초인지를 담은 배열을 리턴하는 문제
가격이 떨어지지 않은 기간은 가격이 떨어지기 전까지의 기간을 의미한다.
따라서, stack을 사용하여 가격이 떨어지지 않은 기간을 구할 수 …

Poco / 30주차 / 1.5문제

---

src/weekly31/nanii/leetCode/215_Kth Largest Element in an Array Medium.ts
src/weekly31/nanii/leetCode/48_Rotate Image.ts

> Example 1
```js
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]
```
> Example 2
```js
Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
```
1. 주어진 input 을 확인해보면 [0][0] => [0][2], [0][2] => [1][2], [0][2] => [2][2] 의 위치로 이동해야합니다.
2. 이때 주어진 배열의 길이가 n*n이므로 `[x][y]` 의 요소는 `[n-1-y][n-1-x]`로 이동한 뒤 배열을 뒤집으면 90도 회전한 위치와 동일함을 알 수 있었습니다.
3. 주어진 이중 for문을 순회하면서 한번 교환한 값을 두번 바꾸지 않게하기 위해 `y < n - x` 조건문 안에서
`matrix[x][y]` <=> `matrix[n-1-y][n-1-x]` 로 교환한 뒤 `reverse()`메서드를 사용하였습니다.
-----
> Example 1
```js
Input: [3, 2, 1, 5, 6, 4], 2
Output: 5
```
> Example 2
```js
Input: [3, 2, 3, 1, 2, 4, 5, 5, 6], 4
Output: 4
```
1. 선택정렬로 배열을 정렬하였으나 시간 초과로 계속해서 실패하여 QuickSelect 방법을 찾아 해결할 수 있었습니다.
2. 우선 피벗을 기준으로 왼쪽, …

Nanii / 31주차 / 2문제

---

src/weekly31/litae/leetcode/215. Kth Largest Element in an Array.ts
src/weekly31/litae/leetcode/48. Rotate Image.ts

- [[LTC] 215. Kth Largest Element in an Array](https://leetcode.com/problems/kth-largest-element-in-an-array/)
> Example 1
```
Input: nums = [3,2,1,5,6,4], k = 2
Output: 5
```
> Example 2
```
Input: nums = [3,2,3,1,2,4,5,5,6], k = 4
Output: 4
```
- 풀이 1
1. 주어진 배열 nums를 sort를 이용하여 내림차순으로 정렬
2. k번째 큰 수를 구하기 위에 내림차순으로 정렬된 nums의 k-1번째 수
- 풀이 2
1. 퀵소트를 해보려고 했으나 29번째 케이스에서 메모리 오류 발생.....
2. 다시 퀵소트 해봐야겠다
- [[LTC] 48. Rotate Image](https://leetcode.com/problems/rotate-image/)
> Example 1
```
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]
```
> Example 2
```
Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
```
- 풀이
1. n X n의 배열을 90도 회전시킨 것은 배열을 대각선([1, 1], [2, 2], [3, 3]...[n, n])을 기준으로 반대로 이동하고 …

litae / 31주차 / 2문제

---

src/weekly32/litae/leetcode/78. Subsets.ts

- [[LTC] 78. Subsets](https://leetcode.com/problems/subsets/)
> Example 1
```
Input: nums = [1,2,3]
Output: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]
```
> Example 2
```
Input: nums = [0]
Output: [[],[0]]
```
Input: nums = [1, 2, 3];
초기값
nums: [1, 2, 3];
result: [[]];
num: 1
temp: []
temp에 [1] 추가
result: [[], [1]]
num: 2
temp: []
temp에 [[2]], [[1, 2]] 추가
result: [[], [1], [2], [1, 2]]
num: 3
temp: []
temp에 [[3], [1, 3], [2, 3], [1, 2, 3]] 추가
result: [[], [1], [2], [1, 2], [3], [1, 3], [2, 3], [1, 2, 3]]

litae / 32주차 / 1문제

---

src/weekly32/poco/leetCode/36_ValidSudoku.js
src/weekly32/poco/leetCode/78_Subsets.js

- 출처 : ([링크](https://leetcode.com/problems/subsets))
nums : number 타입을 요소로 갖는 배열
nums 배열의 정수 요소들로 만들 수 있는 모든 부분집합을 요소로 갖는 배열
nums 배열의 정수 요소들로 만들 수 있는 모든 부분집합 요소를 구하는 문제이다.
result 배열에 빈 배열을 요소로 넣어주고 for문을 통해 nums 배열의 요소를 순회한다.
그리고 이중 for문을 사용해서 result 배열의 길이만큼 반복하면서 result 배열의 요소들을 복사하고
nums 배열의 요소를 복사한 배열에 넣어준다.
이렇게 하면 nums 배열의 요소들로 만들 수 있는 모든 부분집합을 구할 수 있다.
---
- 출처 : ([링크](https://leetcode.com/problems/valid-sudoku/))
board : 문자 타입을 요소로 갖는 2차원 배열
board가 유효한 스도쿠 판이라면 true, 아니라면 false
row, column 객체를 만들고, row에는 하나의 키(cur)를 갖고, column에는 0부터 9까지의 키를 가지며
프로퍼티는 빈배열을 넣어준다.
2중 for문을 순회하면서, row와 column에 각각의 키가 존재하는지 확인한다.
만약 존재한다면, false를 반환하고, 존재하지 않는다면, row와 column의 해당하는 배열에 에 각각의 키를 넣어준다.
row는 첫 번째 for문이 한번 순회를 마치면 빈배열로 초기화 시킨다.
3x3 크기의 그리드 안에 1부터 9까지의 숫자가 중복되지 않게 들어가야 한다는 조건을 간과한 풀이.

Poco / 32주차 / 1.5문제

---

src/weekly32/nanii/leetCode/36_Valid Sudoku.ts
src/weekly32/nanii/leetCode/78_Subsets.ts

> Example 1
```js
Input: nums = [1,2,3]
Output: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]
```
> Example 2
```js
Input: nums = [0]
Output: [[],[0]]
```
1. 배열의 요소를 가지고 생성할 수 있는 모든 조합을 배열로 반환하는 문제입니다.
2. 주어진 배열을 순회하면서 재귀로 조합을 시작할 배열과 조합을 시작할 인덱스를 인자로 전달합니다.
3. 초기배열을 반환하는 result 배열에 넣고,
4. 시작인덱스부터 주어진 배열의 끝까지 반복하면서 요소를 하나씩 넣어 새로운 조합을 생성합니다.
----
> Example 1
```js
Input: board = 
[["5","3",".",".","7",".",".",".","."]
,["6",".",".","1","9","5",".",".","."]
,[".","9","8",".",".",".",".","6","."]
,["8",".",".",".","6",".",".",".","3"]
,["4",".",".","8",".","3",".",".","1"]
,["7",".",".",".","2",".",".",".","6"]
,[".","6",".",".",".",".","2","8","."]
,[".",".",".","4","1","9",".",".","5"]
,[".",".",".",".","8",".",".","7","9"]]
Output: true
```
> Example 2
```js
Input: board = …
```

Nanii / 32주차 / 2문제

---

src/weekly33/litae/leetcode/17. Letter Combinations of a Phone Number.ts
src/weekly33/litae/leetcode/347. Top K Frequent Elements.ts

- [[LTC] 17. Letter Combinations of a Phone Number](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)
> Example 1
```
Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]
```
> Example 2
```
Input: digits = ""
Output: []
```
> Example 3
```
Input: digits = "2"
Output: ["a","b","c"]
```
풀이 방법
1. digits이 빈 배열인 경우 예외처리
2. result은 최종적으로 생성된 문자 조합을 저장
3. permutation 함수는 재귀적으로 문자 조합을 생성(temp: 현재까지 생성된 문자 조합, index: 현재 처리 중인 digits 문자열의 인덱스)
4. permute 함수에서 index digits 문자열의 길이와 동일해지면 result 배열에 현재 생성된 조합 temp을 추가하고 종료
5. 아닌 경우, 현재 숫자에 대한 문자 배열을 돌며 temp에 해당 문자를 추가, 다음 숫자에 대한 조합을 생성하기 위해 재귀 호출
- [[LTC] 347. Top K Frequent Elements](https://leetcode.com/problems/top-k-frequent-elements/)
> Example 1
```
Input: nums = [1,1,1,2,2,3], k = 2
Output: [1,2]
``` …

litae / 33-34주차 / 2문제

---

src/weekly33/poco/leetCode/17_LetterCombinationsOfAPhoneNumber.js
src/weekly33/poco/leetCode/347_TopKFrequentElements.js

- 출처 : ([링크](https://leetcode.com/problems/letter-combinations-of-a-phone-number/?envType=study-plan-v2&envId=top-100-liked))
digits : 2에서 9까지의 숫자를 입력받는다.
2에서 9까지의 숫자를 입력받아 만들 수 있는 모든 문자 조합을 배열로 반환한다.
- 번호판이 존재할 때, 각 숫자(1과 0 제외)마다 문자들이 존재한다.
digits는 2~9까지의 숫자를 입력 받을 때, 각 숫자들을 입력했을 때 만들 수 있는 모든 문자 조합을 배열로 반환하는 문제이다.
먼저 digits의 길이가 0일때는 빈 배열을 return을 해주고, 2~9에 해당하는 각 문자열을 요소로 하는 배열을 value로 갖는 strObj를 만든다.
digits의 길이가 1일때는 strObj[digits[0]]을 map 하여 return 해주고,
digits의 길이가 2이상일 때는 재귀를 통해 모든 문자 조합을 구한다.
permute 함수를 만들어, string과 index를 매개변수로 받는다.
index가 digits의 길이와 같아지면 result에 string을 push하고 return한다.
index가 digits의 길이와 같지 않다면, strObj[digits[index]]를 순회하며
permute(string + newString, index + 1)을 재귀적으로 호출한다.
즉, 다음 digits의 다음 index의 문자열들을 하나씩 더하는 과정을 진행하는 것이다.
---
- 출처 : …

Poco / 33주차 / 2문제

---

src/weekly33/den/leetcode/17_Letter Combinations of a Phone Number.js
src/weekly33/den/leetcode/347_Top K Frequent Elements.js

- 출처 : [leetcode -medium](https://leetcode.com/problems/letter-combinations-of-a-phone-number/?envType=study-plan-v2&envId=top-100-liked)
> Example 1
```js
Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]
```
> Example 2
```js
Input: digits = ""
Output: []
```
> Example 3
```js
Input: digits = "2"
Output: ["a","b","c"]
```
핸드폰 자판 숫자들의 조합이 매개변수로 들어오면, 각 숫자에 매핑되어 있는 알파벳들로 조합할 수 있는 모든 조합을 구하는 문제다.
숫자의 길이와 동일한 길이의 조합을 만들면 되고, 숫자 순서대로 알파벳들을 조합하면 된다.
각 숫자 별로 어떤 문자열이 매핑되어 있는지 알아야 풀 수 있기 때문에, 객체형태로 데이터 구조를 만들었다.
```js
const data = {
2: ["a", "b", "c"],
3: ["d", "e", "f"],
4: ["g", "h", "i"],
5: ["j", "k", "l"],
6: ["m", "n", "o"],
7: ["p", "q", "r", "s"],
8: ["t", "u", "v"],
9: ["w", "x", "y", "z"],
};
```
그리고 dfs라는 helper 함수를 만들어서 각 숫자를 기준으로 계층별로 dfs 탐색을 할 수 있도록 함수 로직을 …

Den / 33주차 / 2문제 

---

src/weekly33/nanii/leetCode/17_Letter Combinations of a Phone Number.ts
src/weekly33/nanii/leetCode/347_Top K Frequent Elements.ts
src/weekly34/nanii/leetCode/388_Longest Absolute File Path.ts

> Example 1
```js
Input: nums = [1,1,1,2,2,3], k = 2
Output: [1,2]
```
> Example 2
```js
Input: nums = [1], k = 1
Output: [1]
```
1. 주어진 배열을 순회하면서 요소에 대한 횟수를 카운트 하기 위해 Map 객체를 사용합니다.
2. 요소를 key로 set하면서 횟수를 +1씩 증가시켜 input 배열에 대한 key(요소), value(횟수)형태의 Map 객체를 생성하고
3. value를 기준으로 내림차순으로 정렬한 다음 주어진 k 인덱스까지의 key값만을 반환합니다.
----
> Example 1
```js
Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]
```
> Example 2
```js
Input: digits = ""
Output: []
```
> Example 3
```js
Input: digits = "2"
Output: ["a","b","c"]
```
1. 먼저 input digits 에 대한 letters 를 맵핑한 객체와 dfs 함수를 생성합니다.
2. dfs 함수의 매개변수로 digits 의 인덱스와 새롭게 조합된 문자열을 받습니다.
3. for문 을 순회하면서 인덱스에 해당하는 버튼의 letter 배열 내에서
i 를 증가시키면서 `letters[i]` 값을 이어붙여 새로운 조합의 문자열을 생성합니다.
4. 주어진 길이가 digits의 길이와 같을 때 결과 배열에 push하여 넣습니다. …

Nanii / 33-34주차 / 3문제

---

src/weekly35/litae/leetcode/93. Restore IP Addresses.ts

- [[LTC] 93. Restore IP Addresses](https://leetcode.com/problems/restore-ip-addresses/)
> Example 1
```
Input: s = "25525511135"
Output: ["255.255.11.135","255.255.111.35"]
```
> Example 2
```
Input: s = "0000"
Output: ["0.0.0.0"]
```
> Example 3
```
Input: s = "101023"
Output: ["1.0.10.23","1.0.102.3","10.1.0.23","10.10.2.3","101.0.2.3"]
```
1. getValidIps 함수를 재귀로 호출(getValidIps(s, 0, 0, '') 로 시작)
2. 현재 만들어진 IP 주소(temp)가 4개인 경우와 s 문자열을 모두 사용한 경우(s.length === startIdx)에는 유효한 IP 주소로 판단하고 마지막에 추가한 '.'를 제거한 결과를 result 배열에 추가
3. 아닌 경우 startIdx와 dotCount에 각각 +1, 현재 문자를 IP 주소에 '.'를 추가
4. 길이가 2에서 3인 부분 문자열의 유효성 검사
5. isValid는 첫번째 IP 주소가 유효한지 여부를 확인

litae / 35주차 / 0.5문제

---

src/weekly35/den/leetcode/93_RestoreIpAddresses.js

- 출처 : [leetcode - medium](https://leetcode.com/problems/restore-ip-addresses/description/)
> Example 1
```js
Input: s = "25525511135"
Output: ["255.255.11.135","255.255.111.35"]
```
> Example 2
```js
Input: s = "0000"
Output: ["0.0.0.0"]
```
> Example 3
```js
Input: s = "101023"
Output: ["1.0.10.23","1.0.102.3","10.1.0.23","10.10.2.3","101.0.2.3"]
```
주어진 문자열 s를 가지고 만들 수 있는 IP 주소를 배열에 담아서 반환하는 문제다.
올바른 IP 주소를 만들기 위해서는, 몇 가지 조건이 있다.
1. 점으로 구분되는 옥텟이 4개여야한다.
2. 각 옥텟은 0 ~ 255 
3. 각 옥텟은 10진수
주어진 문자열에서 3개의 조건을 만족하는 IP주소를 모두 찾기 위해서 dfs를 사용했다.
0의 자리 문자열부터, 문자열을 1,2,3자리씩 slice해서 3개의 조건이 맞는지 확인하고, 맞으면 다음 옥텟을 만들고, 
또 조건에 맞으면 다음 옥텟은 만드는 반복되는 검증 과정을 거쳐서 최종적으로 올바른 IP 주소를 만들면 res 배열에 push 하는 로직을 구현했다.
dfs탐색이 종료되면 res 배열을 IP주소 문자열로 변화해서 반환했다.

덴 / 35주차 / 1문제

---

src/weekly36/poco/programmers/더맵게.js
src/weekly36/poco/programmers/폰켓몬.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/1845))
nums : 폰켓몬의 종류번호가 담긴 1차원 배열
가장 많은 종류의 폰켓몬을 선택했을 때, 폰켓몬 종류 번호의 개수
가장 많은 종류의 폰켓몬을 선택했을 때의 폰켓몬 종류 번호의 개수를 구하는 문제
먼저 폰켓몬의 총 종류의 개수를 구하기 위해, nums 배열을 순회하면서 ponketMonObj에 폰켓몬 종류별 마리수를 저장한다
ponketMonObj의 key 개수를 구하고, 폰켓몬을 선택할 수 있는 count 변수와 비교
만약 count가 ponketMonObj의 key 개수, 즉 폰켓몬의 종류보다 큰 경우에는 폰켓몬의 종류 개수를 반환하고
그외의 경우에는 count를 반환
--- 
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/42626))
scoville: 음식의 스코빌 지수가 담긴 배열
K: 스코빌 지수의 최소값
모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 섞어야 하는 최소 횟수
모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 섞어야 하는 최소 횟수를 구하는 문제
이 문제를 해결하기 위해서는 Heap 자료 구조를 사용해야 한다
Heap 자료 구조는 최소 힙과 최대 힙으로 나뉘는데, 최소 힙은 부모 노드의 값이 자식 노드의 값보다 작거나 같은 완전 이진 트리를 말한다
최소 힙은 부모 노드의 값이 자식 노드의 값보다 작거나 같기 때문에, 루트 노드의 값이 최소값이 된다
이 …

Poco / 36주차 / 1.5문제

---

src/weekly36/litae/programmers/더 맵게.ts
src/weekly36/litae/programmers/폰켓몬.ts

- [[PGS] 폰켓몬]((https://school.programmers.co.kr/learn/courses/30/lessons/1845))
> Example 1
```
nums: [3,1,2,3]
result: 2
```
> Example 2
```
nums: [3,3,3,2,2,4]
result: 3
```
> Example 3
```
nums: [3,3,3,2,2,2]
result: 2
```
1. 새로운 map을 생성
2. nums 배열을 돌면서 각 요소(num)을 키값으로 있는지 여부를 확인
3. map에 해당 요소(num)를 키값으로 하는 값이 없으면 해당 요소를 키값으로 하고 value를 1(임의의 값)로 생성
4. for문이 돌고 나면 map의 키값은 nums의 중복되는 숫자가 제거된 요소들이 키값으로 존재
5. map.size와 nums.length 중 작은 값을 리턴
-----
- [[PGS] 더 맵게]((https://school.programmers.co.kr/learn/courses/30/lessons/42626))
> Example 1
```
scoville: [1, 2, 3, 9, 10, 12]
K: 7
return: 2
```
1. sortScoville 함수는 scoArray 배열을 오름차순으로 정렬하는 함수
2. mixScoville 함수는 scoArray의 두 가지 음식을 섞는 코드(섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2))
3. 두 과정이 끝나면 count++
4. 만약 scoArray의 가장 …

litae / 36주차 / 1문제

---

src/weekly36/nanii/programmers/더맵게.ts
src/weekly36/nanii/programmers/폰켓몬.ts

> Example
nums | result
-- | --
[3,1,2,3] | 2
[3,3,3,2,2,4] | 3
[3,3,3,2,2,2] | 2
1. N마리의 폰켓몬중에서 N/2마리를 선택할 수 있는 방법의 규칙을 찾아보니
2. 주어진 nums 배열을 순회하면서 존재하는 폰켓몬 종류의 수 를 찾고
3. 종류의 개수가 N/2보다 크면 N/2를 반환하고, 아니면 종류의 개수를 반환합니다.
----
> Example
scoville | K | return
-- | -- | --
[1, 2, 3, 9, 10, 12] | 7 | 2
1. 자료구조 힙을 사용해야했지만, 문제를 보고 왜 힙으로 풀어야할지 감이 오지 않아 힙을 사용하지 않았습니다. (Q. 왜 사용해야하는가..!!!!!)
2. 두번의 시도끝에 테스트 통과는 했지만 효율성테스트는 통과하지 못하였답니다..?
3. scoville이 담긴 배열을 오름차순으로 정렬하면 0번째 인덱스의 값이 최솟값임을 이용하여 풀이하였습니다.
4. while문을 순회하면서 최솟값이 K보다 작으면 계속해서 섞어야하므로 조건을 걸고
5. 만약 섞은 배열의 길이가 1이 되었는데도 K 보다 크지않은 경우 -1을 반환하고
6. 최솟값과 그다음 최솟값의 2배한 값을 더하여 새 배열을 생성하고 섞은 횟수 answer ++ 합니다.
7. 이 과정을 계속해서 반복하다 K 보다 최솟값이 작아지면 answer 를 반환합니다.

Nanii / 36주차 / 2문제

---

src/weekly38/litae/programmers/베스트앨범.ts
src/weekly38/litae/programmers/신고 결과 받기.ts

- [[PGS] 신고 결과 받기](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
> Example 1
```
id_list: ["muzi", "frodo", "apeach", "neo"]
report: ["muzi frodo","apeach frodo","frodo neo","muzi neo","apeach muzi"]
k: 2
result: [2,1,1,0]
```
> Example 2
```
id_list: ["con", "ryan"]
report: ["ryan con", "ryan con", "ryan con", "ryan con"]
k: 3
result: [0,0]
```
1. Set을 활용하여 중복된 요소를 제거하고 [신고한 유저, 신고당한 유저]를 담은 2차원 배열로 저장
2. reportedUser에 신고당한 유저를 배열로 저장
3. reportCount에 모든 유저의 수만큼 길이를 가진 배열을 생성하고 0으로 초기화
4. 신고당한 유저 배열(reportedUser)을 forEach로 돌면서 해당 유저의 index에 신고당한 수를 카운트
5. 카운트 된 배열(reportCount)을 돌면서 최소 k번 이상 신고된 경우(k 보다 신고당한 횟수가 많거나 같을 경우) reportedKUser 배열에 추가
6. set 배열을 돌면서 신고당한 사용자가 reportedKUser 배열에 포함되어 있는 경우, 해당 신고를 한 사용자의 result 값을 증가
- [[PGS] 베스트 …

litae / 37주차 / 2문제

---

src/weekly37/nanii/leetCode/139_Word Break.ts
src/weekly37/nanii/programmers/신고결과받기.ts

> Example
```js
Input: s = "leetcode", wordDict = ["leet","code"]
Output: true
```
> Example
```js
Input: s = "applepenapple", wordDict = ["apple","pen"]
Output: true
```
> Example
```js
Input: s = "catsandog", wordDict = ["cats","dog","sand","and","cat"]
Output: false
```
1. `wordDict`의 요소를 조합하여 문자열(`s`) 생성 가능 여부를 반환해야한다.
2. 문자열(`s`)의 인덱스를 증가시키면서 Dfs로 조합이 가능한지 확인합니다.
3. `wordDict` 배열에 중복 요소가 있는지 확인하기 위해 `Set()` 객체를 사용하고
4. 인덱스를 증가시키면서 중복 확인을 방지하기 위해 인덱스를 저장하는 `memo` 객체리터럴을 생성해놓고 시작합니다.
5. Dfs 함수인 check함수에 매개변수로 0을 넣어, 0번째 인덱스부터 i를 증가시켜 문자열(`s`)에서 slice한 word를 생성합니다.
6. 이 word가 `wordDict`Set 객체에 있으면, 그럼 다음 인덱스부터 다시 word가 있는지 확인합니다.
7. 그럼 확인이 끝난 index는 memo 객체에 true로 넣고, 계속해서 재귀를 호출합니다.
----
> Example
id_list | report | k | result
-- | -- | -- | --
["muzi", "frodo", "apeach", "neo"] | …

Nanii / 37주차 / 2문제

---

src/weekly38/nanii/leetCode/739. Daily Temperatures.ts
src/weekly38/nanii/programmers/이모티콘할인행사.ts

> Example
```js
Input: temperatures = [73,74,75,71,69,72,76,73]
Output: [1,1,4,2,1,1,0,0]
```
> Example
```js
Input: temperatures = [30,40,50,60]
Output: [1,1,1,0]
```
> Example
```js
Input: temperatures = [30,60,90]
Output: [1,1,0]
```
1. 온도배열을 순회하면서 기준이 되는 Index의 value보다 큰 값이 나올 때까지 `day++` 합니다.
2. 더 큰 값이 나오면 day를 해당 인덱스의 result 배열의 value로 대체하고 없으면 다음으로 넘어갑니다.
----
> Example
users | emoticons | result
-- | -- | --
[[40, 10000], [25, 10000]] | [7000, 9000] | [1, 5400]
[[40, 2900], [23, 10000], [11, 5200], [5, 5900], [40, 3100], [27, 9200], [32, 6900]] | [1300, 1500, 1600, 4900] | [4, 13860]
1. 사용자별 이모티콘 할인율에 대한 모든 경우의 수를 구하고, 그 경우에 대한 구매가격을 조합해야합니다.
2. 사용자별 조건에 대한 조합을 해야하므로 dfs알고리즘을 이용합니다.
3. 먼저, 전체 이모티콘 배열을 순회하면서 10-40%까지의 할인율을 적용한 조합을 생성합니다.
4. 그 다음 사용자 배열을 순회하면서 이전에 생성한 조합에서 최대 목적을 …

Nanii / 38주차 / 1.5문제

---

src/weekly38/litae/leetcode/739. Daily Temperatures.ts
src/weekly38/litae/programmers/이모티콘 할인행사.ts

- [[LTC] 739. Daily Temperatures](https://leetcode.com/problems/daily-temperatures/)
> Example 1
```
Input: temperatures = [73,74,75,71,69,72,76,73]
Output: [1,1,4,2,1,1,0,0]
```
> Example 2
```
Input: temperatures = [30,40,50,60]
Output: [1,1,1,0]
```
> Example 3
```
Input: temperatures = [30,60,90]
Output: [1,1,0]
```
1. 결과를 담는 result 배열 생성
2. 2중 for문으로 기준 온도보다 더 높은 온도가 있는 경우 index의 차를 result 배열에 push
3. 높은 온도를 찾은 경우 break(불필요한 순환 방지)
4. 더 높은 온도가 없는 경우를 찾기 위해 result에 새로 추가되지 않은 경우 0을 push
- [[PGS] 이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)
> Example 1
```
users: [[40, 10000], [25, 10000]]
emoticons: [7000, 9000]
result: [1, 5400]
```
> Example 2
```
users: [[40, 2900], [23, 10000], [11, 5200], [5, 5900], [40, 3100], [27, 9200], [32, 6900]]
emoticons: …
```

litae / 38주차 / 1.5문제

---

src/weekly39/den/leetcode/198_House Rover.js
src/weekly39/den/leetcode/71_Simplify Path.js

- 출처 : [leetcode - medium](https://leetcode.com/problems/simplify-path/description/\?envType\=study-plan-v2\&envId\=top-interview-150)
> Example 1
```js
Input: path = "/home/"
Output: "/home"
```
---
- 출처 : [leecode - medium](https://leetcode.com/problems/house-robber/)
> Example 1
```js
Input: nums = [1,2,3,1]
Output: 4
```
1. maxTwo와 maxOne이라는 두 개의 변수를 선언하고 0으로 초기화합니다. 이 두 변수는 현재 집까지의 최대 돈과 직전 집까지의 최대 돈을 저장합니다.
2. 배열 nums을 반복하면서 각 집에서 훔칠 수 있는 돈의 양을 nums[i]로 나타냅니다. 이 반복문은 배열의 길이(nums.length)만큼 실행됩니다.
3. 각 집에서 훔칠 수 있는 돈의 양과 직전 집까지의 최대 돈인 maxTwo를 더한 값과 현재 집까지의 최대 돈인 maxOne 중에서 더 큰 값을 maxCurrent에 저장합니다. 이렇게 함으로써, 현재 집을 훔칠 경우와 훔치지 않을 경우 중에서 어떤 경우가 더 이익을 가져올지 결정합니다.
4. 그 다음, maxTwo를 maxOne으로 업데이트하고, maxOne을 maxCurrent로 업데이트합니다. 
5. 반복문이 모든 집을 순회한 후에 maxOne에는 주어진 배열 nums를 훔칠 수 있는 최대 금액이 저장되어 …

Den / 39주차 / 2문제

---

src/weekly39/litae/leetcode/198. House Robber.ts
src/weekly39/litae/leetcode/71. Simplify Path.ts

- [[LTC] 71. Simplify Path / Medium](https://leetcode.com/problems/simplify-path/)
> Example 1
```
Input: path = "/home/"
Output: "/home"
```
> Example 2
```
Input: path = "/../"
Output: "/"
```
> Example 3
```
Input: path = "/home//foo/"
Output: "/home/foo"
```
1. path에 split과 filter를 통해 "/"가 제외된 요소를 가진 배열을 생성
2. forEach문을 통해 요소가 ".."인 경우 result 배열의 가장 마지막 요소를 제거(".."는 상위 폴더로 가는 개념이기 때문에 경로가 한단계 줄어듦)
3. 요소가 "."인 경우 아무 영향을 주지 않음("."는 현재 디렉토리)
4. 그 외는 result 배열에 경로를 추가
5. 가장 앞에 "/"를 붙여주고 join 메서드로 각 경로를 "/"로 연결하여 리턴
- [[LTC] 198. House Robber / Medium](https://leetcode.com/problems/house-robber/)
> Example 1
```
Input: nums = [1,2,3,1]
Output: 4
```
> Example 2
```
Input: nums = [2,7,9,3,1]
Output: 12
```
1. nums 배열이 빈 배열이거나 length가 1일 때 예외처리
2. for문을 돌면서 이전의 최대값과 현재값을 비교
```
nums = …
```

litae / 39주차 / 1.5문제

---

src/weekly40/litae/leetcode/540. Single Element in a Sorted Array.ts

- [[LTC]540. Single Element in a Sorted Array](https://leetcode.com/problems/single-element-in-a-sorted-array/)
> Example 1
```
Input: nums = [1,1,2,3,3,4,4,8,8]
Output: 2
```
> Example 2
```
Input: nums = [3,3,7,7,10,11,11]
Output: 10
```

litae / 40주차 / 1문제

---

src/weekly40/den/leetcode/540_SingleElementInASortedArray.js

- 출처 : [leetcode - medium](https://leetcode.com/problems/single-element-in-a-sorted-array/description/)
Example 1:
```js
Input: nums = [1,1,2,3,3,4,4,8,8]
Output: 2
```
Example 2:
```js
Input: nums = [3,3,7,7,10,11,11]
Output: 10
```
주어진 배열 nums는 오름차순으로 정렬되어 있고, 배열 내에는 단 하나의 요소만이 한 번만 나타난다. 그래서 그 한 번만 나타나는 요소를 찾는 함수를 구현하는 문제다. 이 문제는 O(log n)의 시간 복잡도로 풀어야 해서, 이진 검색을 활용해서 풀었다.
우선 이진 탐색을 위해서, 배열의 왼쪽 끝 index를 나타나는 변수 left, 배열의 오른쪽 끝 index를 나타내는 변수 right를 선언했다.
그리고 반복문을 돌면서 left가 right보다 작으면 계속 순회하는 while문을 실행한다.
while문 내에서는, left와 right를 기준으로 중앙값을 나타내는 mid 변수를 선언 및 계산하고,
mid가 홀수인 경우, mid를 1 감소시켜서 짝수로 만들어준다. (이진 탐색을 위해서는 mid가 짝수여야 한다.)
그리고 nums[mid]와 nums[mid + 1]이 같지 않은 경우, 즉 mid가 짝수인 경우에는, right를 mid로 설정해준다.
그리고 nums[mid]와 nums[mid + 1]이 같은 경우, 즉 mid가 홀수인 경우에는, left를 mid + 2로 설정해준다.
이렇게 하면, …

Den / 40주차 / 1문제

---

src/weekly40/poco/leetCode/45_JumpGameII.js
src/weekly40/poco/leetCode/540_SingleElementInASortedArray.js

- 출처 : ([링크](https://leetcode.com/problems/jump-game-ii/description/))
nums : 정수를 요소로 갖는 배열
nums 배열의 요소들을 이용하여 마지막 인덱스로 이동할 수 있는 최소 점프 횟수
nums 배열의 각 요소는 현재 위치에서 점프할 수 있는 최대 거리를 의미한다.
nums 배열의 요소들을 이용하여 마지막 인덱스로 이동할 수 있는 최소 점프 횟수를 구하는 문제이다.
dp를 사용해서 문제를 해결해야 한다.
dp 배열의 각 요소는 해당 요소까지 최소 몇번만에 도달할 수 있는지를 기록한다.
이중 for 문을 통해 dp[i + j]는 결국 i는 nums 배열의 idx를 의미하고
j는 nums[i]의 값이므로, dp[i + j]는 결국 i번째 idx에서 점프해서 이동할 수 있는 지점을 의미한다.(최소 1부터 j까지))
dp[i + j]까지 도달하는데 걸리는 횟수가 0이라면 dp[i + j]까지 도달하는데 걸리는 횟수는 dp[i] + 1이다.
dp[i + j]까지 도달하는데 걸리는 횟수가 0이 아니라면 dp[i + j]까지 도달하는데 걸리는 횟수와 dp[i] + 1 중에서 작은 값을 dp[i + j]에 할당한다.
그래야 dp[i + j]까지 도달하는데 걸리는 최소 횟수를 구할 수 있다.
마지막으로 dp[nums.length - 1]을 반환하면 최소 점프 횟수를 구할 수 있다.
---
출처 : ([링크](https://leetcode.com/problems/jump-game-ii/description/](https://leetcode.com/problems/si …

Poco / 40주차 / 2문제

---

src/weekly40/nanii/leetCode/45. Jump Game II.ts
src/weekly40/nanii/leetCode/540. Single Element in a Sorted Array.ts

> Example
```js
Input: nums = [2,3,1,1,4]
Output: 2
```
> Example
```js
Input: nums = [2,3,0,1,4]
Output: 2
```
1. 주어진 배열에서 인덱스를 기준으로 최대로 점프하여 마지막 인덱스를 도달할 때까지 최소로 점프한 횟수를 반환하는 문제입니다.
2. 주어진 배열을 순회하면서 해당 인덱스를 기준으로 가장 많이 점프할 수 있는 거리를 Math.max로 구한다음
3. 현재 위치에서 이동할 때 step 수를 증가시키면서 그 가장 많이 점프할 수 있는 값으로 갱신하여 step 수를 반환합니다.
----
> Example
```
Input: nums = [1,1,2,3,3,4,4,8,8]
Output: 2
```
> Example
```
Input: nums = [3,3,7,7,10,11,11]
Output: 10
```
1. 주어진 배열이 정.렬.된 배열이기때문에 같은 숫자일 경우 연속됨을 이용합니다.
2. `[i]`인덱스와 `[i+1]`인덱스의 요소가 같지 않으면 값을 반환합니다.
3. 같을 경우 2개의 값을 비교했기때문에 `i+=2`를 하여 다음 값을 비교합니다.

Nanii / 40주차 / 2문제 

---

src/weekly41/poco/leetCode/34_FindFirstandLastPositionofElementinSortedArray.js
src/weekly42/programmers/구명보트.js

- 출처 : ([링크](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/))
nums: 정수를 요소로 갖는 배열
target: 정수
nums 배열에서 target의 시작 인덱스와 끝 인덱스를 배열로 반환
매개변수로 주어진 nums 배열에서 target의 시작과 끝 인덱스를 배열로 반환하는 문제이다.
문제에서 주어진 조건은 O(log n)의 시간복잡도로 문제를 풀어야했고 이진탐색을 활용하여 문제 해결을 시도했다.
처음에는 target이 최대 2개일거라고 문제를 해석해서 밑에 실패한 풀이처럼 문제를 풀었다.
하지만 nums가 [3,3,3]인 테스트 케이스가 있다는 것을 확인했고, 풀이를 수정했다.
전체 문제 풀이는 이진탐색을 이용했고, 실패 풀이보다 더 추가한 풀이 방법은
start와 end 변수를 추가로 만들고 만약 nums[mid]가 target과 일치하는 경우에는
start와 end 변수를 각각 -1, +1 하는 while문을 추가했다.
그리고 더이상 start, end 변수를 다루는 while문이 실행되지 않는 경우에는
start + 1, end -1 을 반환하도록 했다.
--- 
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/42885))
people : 사람들의 몸무게가 담긴 배열
limit : 구명보트의 무게 제한
구명보트의 최소 개수
사람들의 몸무게가 담긴 배열 people이 주어지고 …

Poco / 41 ~ 42주차 / 2문제

---

src/weekly41/litae/leetcode/34. Find First and Last Position of Element in Sorted Array.ts
src/weekly41/litae/programmers/여행경로.ts
src/weekly42/litae/programmers/구명보트.ts

- [[PGS] 여행경로](https://school.programmers.co.kr/learn/courses/30/lessons/43164)
> Example 1
```
tickects: [["ICN", "JFK"], ["HND", "IAD"], ["JFK", "HND"]]
return: ["ICN", "JFK", "HND", "IAD"]
```
> Example 2
```
tickects: [["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"]]
return: ["ICN", "ATL", "ICN", "SFO", "ATL", "SFO"]
```
1. 티켓 배열을 알파벳 순으로 정렬
2. visit 배열을 false로 초기화하고 방문여부를 체크
3. 현재 위치, 카운트, 경로를 받는 dfs
4. 모든 티켓을 확인하고(cnt === tickets.length), 정답이 없는 경우(answer.length === 0) 현재 경로를 답으로 하고 dfs 함수 종료
5. for문으로 티켓을 탐색하면서 이미 확인한 티켓은 건너뛰기
6. 만약 출발하는 공향이 현재 공항과 일치하는 경우 해당 티켓을 방문 처리
7. 다음 단계 탐색 실행
8. 탐색이 끝나면 방문여부 체크 해제
---
- [[LTC] 34. Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sor …

litae / 41-42주차 / 3문제

---

src/weekly41/nanii/leetCode/34_Find First and Last Position of Element in Sorted Array.ts
src/weekly42/nanii/leetCode/64_Minimum Path Sum.ts

> Example
```js
Input: grid = [[1,3,1],[1,5,1],[4,2,1]]
Output: 7
```
> Example
```js
Input: grid = [[1,2,3],[4,5,6]]
Output: 12
```
1. 왼쪽위에서 오른쪽아래로 이동할 때 경로에 있는 숫자들의 합이 최소인 경로를 찾아서 그 합을 리턴해야합니다.
2. 2차 배열을 순회하면서 행을 하나씩 증가시켰을 때 나올 수 값을 그 다음 행에 누적합니다.
3. 그 다음 열을 하나씩 증가시켰을 때 나올 수 있는 값을 그 다음 열에 누적합니다.
4. 그 다음 for 문을 순회하면서 각 인덱스에서 접근할 수 있는 값은 최소값으로만 누적해야하므로 `Math.min`메서드를 사용하여 누적합니다.
5. 그러면 배열의 마지막 인덱스의 값이 최솟값이 누적됩니다.
----
> Example
```
Input: nums = [5,7,7,8,8,10], target = 8
Output: [3,4]
```
> Example
```
Input: nums = [5,7,7,8,8,10], target = 6
Output: [-1,-1]
```
> Example
```
Input: nums = [], target = 0
Output: [-1,-1]
```
1. 타겟값의 첫번째 인덱스를 앞에서부터 찾고,
2. 마지막 인덱스를 뒤에서부터 찾아서
3. 없으면 -1를 반환합니다.

Nanii / 41-42주차 / 2문제

---

src/weekly43/den/leetcode/229_MajorityElement2.js
src/weekly43/den/leetcode/300_LongestIncreasingSubsequence.js

- 출처 : [leetcode - medium](https://leetcode.com/problems/majority-element-ii/)
> Example 1:
```
Output: [3]
```
> Example 2:
```js
Input: nums = [1]
Output: [1]
```
> Example 3:
```js
Input: nums = [1,2]
Output: [1,2]
```
주어진 배열에서 배열의 길이 n/3 보다 많은 요소를 찾는 문제다.
이를 위해서, 우선 Map 객체를 만들어 배열의 각 요소가 몇 개있는지 count 했다.
그러고 나서 Map 객체의 요소를 순회하며 n/3 보다 많은 요소를 찾아 배열에 push하고 반환했다.
---
- 출처 : [leetcode - medium](https://leetcode.com/problems/longest-increasing-subsequence/description/)
> Example 1:
```js
Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
```
> Example 2:
```js
Input: nums = [0,1,0,3,2,3]
Output: 4
```
> Example 3:
```js
Input: nums = [7,7,7,7,7,7,7]
Output: 1
```
가장 긴 증가하는 수열의 길이를 찾는 문제다.
우선, arr 배열을 하나 선언해서, nums 배열의 첫 번째 요소를 넣어줬다.
그리고 nums 배열을 순회하며, 
순회 중인 요소가 만약 arr의 …

Den / 43주차 / 2문제

---

src/weekly43/nanii/leetCode/229_Majority Element II.ts
src/weekly43/nanii/leetCode/300_Longest Increasing Subsequence.ts

> Example
```js
Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
```
> Example
```js
Input: nums = [0,1,0,3,2,3]
Output: 4
```
> Example
```js
Input: nums = [7,7,7,7,7,7,7]
Output: 1
```
1. 예제 3번을 보면, 배열내의 요소가 일정할 때 output이 1 이므로 dp배열을 생성하면서 fill(1)합니다.
2. 그다음 주어진 nums 배열을 순회하면 i번째 인덱스를 기준으로 그보다 작은 인덱스의 값들이 증가할 때에만 +1을 하면서 dp의 i인덱스에 값을 누적합니다.
3. dp[0]에는 nums[0]이 nums[0]보다 크지 않으므로 1이고 그 다음부터, 
dp[1] = nums[1] > nums[0] 이면 ? dp[0] + 1 한 값을 누적하고, 아니면 패스합니다.
4. 인덱스를 계속해서 증가하면서 마지막 인덱스까지 갔을 때 누적값을 반환합니다.
----
> Example
```
Output: [3]
```
> Example
```
Input: nums = [1]
Output: [1]
```
> Example
```
Input: nums = [1,2]
Output: [1,2]
```
1. 주어진 배열의 길이의 3을 나눈 값보다 더 많이 등장하는 요소를 찾는 문제입니다.
2. nums 배열을 순회하면서 등장하는 횟수를 map 객체에 카운트 합니다.
3. map 객체를 다시 순회하면서 n/3 보다 큰 key의 값을 찾아서 반환합니다.

Nanii / 43주차 / 2문제

---

src/weekly43/litae/leetcode/229. Majority Element II.ts
src/weekly43/litae/leetcode/300. Longest Increasing Subsequence.ts

- [[LTC]229. Majority Element II](https://leetcode.com/problems/majority-element-ii/)
> Example 1
```
Output: [3]
```
> Example 2
```
Input: nums = [1]
Output: [1]
```
> Example 3
```
Input: nums = [1,2]
Output: [1,2]
```
- [[LTC] 300. Longest Increasing Subsequence](https://leetcode.com/problems/longest-increasing-subsequence/)
> Example 1
```
Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
Explanation: The longest increasing subsequence is [2,3,7,101], therefore the length is 4.
```
> Example 2
```
Input: nums = [0,1,0,3,2,3]
Output: 4
```
> Example 3
```
Input: nums = [7,7,7,7,7,7,7]
Output: 1
```

litae / 43주차 / 2문제

---

src/weekly44/litae/leetcode/137. Single Number II.ts
src/weekly44/litae/leetcode/416. Partition Equal Subset Sum.ts

[[LTC] 137. Single Number II / Medium](https://leetcode.com/problems/single-number-ii/)
> Example 1
```
Input: nums = [2,2,3,2]
Output: 3
```
> Example 2
```
Input: nums = [0,1,0,1,0,1,99]
Output: 99
```
[[LTC] 416. Partition Equal Subset Sum](https://leetcode.com/problems/partition-equal-subset-sum/)
> Example 1
```
Input: nums = [1,5,11,5]
Output: true
Explanation: The array can be partitioned as [1, 5, 5] and [11].
```
> Example 2
```
Input: nums = [1,2,3,5]
Output: false
Explanation: The array cannot be partitioned into equal sum subsets.
```

litae / 44문제 / 1문제

---

src/weekly44/nanii/leetCode/137_Single Number II.ts
src/weekly44/nanii/leetCode/416_Partition Equal Subset Sum.ts

> Example
```js
Input: nums = [2,2,3,2]
Output: 3
```
> Example
```js
Input: nums = [0,1,0,1,0,1,99]
Output: 99
```
1. 하나의 요소를 빼고 다른 요소들이 3번씩나오는 배열에서 1번만 나오는 요소를 반환해야합니다.
- 조건 1. O(n) time complexity 시간복잡도
- 조건 2. O(1) space complexity 공간복잡도
2. Map객체를 사용하여 요소 나타난 횟수를 저장하고, 다시 map 객체를 순회하면서 value가 1인 key를 반환하도록 하였습니다.
3. 시간복잡도는 for 문에서 return을 사용했지만, 공간복잡도는 더 좋은 방법이 있을 것같습니다...
----
> Example
```
Input: nums = [1,5,11,5]
Output: true
```
> Example
```
Input: nums = [1,2,3,5]
Output: false
```
1. nums 배열이 2개의 부분집합으로 나눴을 때 각 부분집합의 합이 같아지는 지 boolean 값으로 반환
2. dp 배열을 생성해서 배열내에 target 값 을 순으로 순회하면서
3. 현재 부분집합의 합과 현재 숫자를 더한 값을 더한 부분집합의 합 중 큰 값을 dp에 저장합니다
4. dp의 target 인덱스의 값이 타겟값과 같으면 true를 반환하고 아니면 false를 반환합니다.

Nanii / 44주차 / 1.5문제

---

src/weekly44/den/leetcode/137_SingleNumber2.js
src/weekly44/den/leetcode/416_PartitionEqualSubsetSum.js

> Example 1
```js
Input: nums = [2,2,3,2]
Output: 3
```
> Example 2:
```js
Input: nums = [0,1,0,1,0,1,99]
Output: 99
```
주어진 배열에는 각 요소가 동일하게 3개씩 있거나, 유일하게 하나 있는 요소가 있다. 이 중 하나 있는 요소를 찾는 문제다.
우선 nums를 오름차순 정렬한 뒤에, for문을 돌면서 순회 대상 요소와 3번째 뒤에 있는 요소가 같은지 여부를 판별해서,
같지 않다면 순회 대상 요소가 배열 안에 유일하게 하나 있는 요소라고 판단하고, 그 요소를 반환한다.

Den / 44주차 / 1.5문제

---

src/weekly45/litae/leetcode/131. Palindrome Partitioning.ts
src/weekly45/litae/leetcode/75. Sort Colors.ts

[75. Sort Colors](https://leetcode.com/problems/sort-colors/)
> Example 1
```
Input: nums = [2,0,2,1,1,0]
Output: [0,0,1,1,2,2]
```
> Example 2
```
Input: nums = [2,0,1]
Output: [0,1,2]
```

litae / 45주차 / 1문제

---

src/weekly45/den/leetcode/75_SortColors.js

- 출처 : [[LTC] 75. Sort Colors / medium](https://github.com/Algorithm-Squad/Algorithm/commit/0b2e946fdf65afe3f61340d49d7ceac47b9fbcd9)
주어진 nums 배열을 오름차순 정렬하는 문제로, 버블 정렬을 이용하여 문제를 풀었습니다.
1. 배열의 첫 번째 요소부터 시작하여 인접한 두 요소를 비교합니다.
2. 만약 첫 번째 요소가 두 번째 요소보다 크다면 두 요소의 위치를 교환합니다.
3. 이후 배열의 두 번째 요소와 세 번째 요소를 비교하고, 이 과정을 배열의 끝까지 반복합니다.
4. 위 가정이 완료된 후에는 가장 큰 요소가 배열의 마지막으로 이동하게 됩니다.
5. 이제 배열의 마지막 요소를 제외하고 위의 과정을 다시 반복합니다.
6. 배열이 정렬될 때까지 이러한 패스를 계속 반복합니다.

Den / 45주차 / 1문제

---

src/weekly45/nanii/leetCode/131_Palindrome Partitioning.ts
src/weekly45/nanii/leetCode/75_Sort Colors.ts

> Example
```js
Input: nums = [2,0,2,1,1,0]
Output: [0,0,1,1,2,2]
```
> Example
```js
Input: nums = [2,0,1]
Output: [0,1,2]
```
1. 0, 1, 2로 이루어진 배열에서 같은 숫자끼리 인접하도록 정렬하는 문제입니다.
2. 숫자를 key, 반복되는 횟수를 value로 갖는 map객체를 생성하였고
3. 추가메모리없이 nums배열의 index에 값을 교체하는 방식으로 저장하였습니다.
----
> Example
```
Input: s = "aab"
Output: [["a","a","b"],["aa","b"]]
```
> Example
```
Input: s = "a"
Output: [["a"]]
```
1. 주어진 배열에서 Palindrome이 될 수 있는 요소의 집합을 배열로 반환하는 문제입니다.
2. 먼저 Palindrome인지 확인하는 함수를 생성하였고
3. 주어진 문자열을 순회하면서 Palindrome조합을 생성합니다.
4. dfs의 첫번째 인자로 조합해야되는 문자열, 두번째인자로 조합된 배열을 받습니다.
5. 문자열을 순회하면서 조합을 생성하는데 이 생성된 조합이 Palindrome이면, 해당 문자열의 다음 인덱스부터 다시 조합을 생성하도록 합니다.
6. 문자열의 마지막 인덱스가 되었을 땐 첫번째 인자가 빈 문자열이 들어오므로 그때 result 배열에 조합들을 push하여 반환합니다.

Nanii / 45주차 / 2문제

---

src/weekly45/poco/leetCode/131_PalindromePartitioning.js
src/weekly45/poco/leetCode/75_SortColors.js

- 출처 : ([링크](https://leetcode.com/problems/sort-colors/))
nums : 0, 1, 2를 요소로 갖는 배열
nums 배열을 0, 1, 2 순서로 정렬해서 반환
0, 1, 2를 요소로 갖는 배열 nums가 주어졌을 때, nums 배열을 0, 1, 2 순서로 정렬해서 반환하는 문제이다.
라이브러리의 sort 메서드를 사용하지 않고 문제를 해결해야 하며 제자리 정렬을 해야한다.
선택 정렬을 사용해서 문제를 해결했다. 선택 정렬은 in place 제자리 정렬이며, 중복데이터의
자리를 교체하지 않는 stable 정렬이다.
선택 정렬은 배열의 1번째 요소부터 순회하면서 해당 요소를 기준으로 그 이전의 요소들과 비교한다.
기준 요소보다 이전의 요소가 더 크다면, 기준 요소와 이전 요소의 자리를 바꾼다.
선택 정렬은 정렬되어 있는 배열의 경우, 시간복잡도는 O(n) 이지만, 정렬이 하나도 되지 않은 배열의 경우 O(n^2)이다.
--- 
- 출처 : ([링크](https://leetcode.com/problems/palindrome-partitioning/))
s: 문자열
s를 분할하여 만들 수 있는 모든 회문 문자열의 집합
문자열 s가 주어졌을 때, s를 분할하여 만들 수 있는 모든 회문 문자열의 집합을 구하는 문제이다.
회문 문자열이란 앞에서 읽으나 뒤에서 읽으나 같은 문자열을 의미한다.
s를 분할했을 때, 모든 회문 문자열을 구하는 것이 아닌,
s를 분할하여 만들 수 있는 모든 회문 문자열의 집합을 구하는 것이다.
즉, s를 분할했을 때, 만들어지는 부분 문자열들이 모두 …

Poco / 45주차 / 2문제

---

src/weekly46/den/leetcode/386_LexicographicalNumbers.js
src/weekly46/den/programmers/네트워크.js

- 출처 : [[LTC] 386. Lexicographical Number / medium](https://github.com/Algorithm-Squad/Algorithm/commit/c113299d4b16a60ffabc73c3a4603c420ab0f02b)
입력되는 숫자 n에 대해서 0~n까지의 숫자를 사전식 순서로 나열해서 Return해야 되는 문제다.
result 배열을 선언하고, 숫자 i 매개변수를 받는 dfs 함수를 구현해서  1~10까지 dfs를 호출합니다.
dfs함수 내부에서는, 매개변수로 받은 숫자 i를 i1 ~ i9 까지 result 배열에 넣는 작업을 반복합니다.
단, 매개변수로 받은 숫자가 n 보다 크면 dfs 재귀 호출을 종료하게 됩니다.
재귀 호출이 종료되면 result 배열을 반환합니다./

Den / 46주차 / 1.2문제

---

src/weekly46/litae/leetcode/386. Lexicographical Numbers.ts
src/weekly46/litae/programmers/네트워크.ts

###[PGS] 네트워크 / Lv. 3
-[[PGS] 네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
> Example 1
```
n: 3
computers: [[1, 1, 0], [1, 1, 0], [0, 0, 1]]
return: 2
```
> Example 2
```
n: 3
computers: [[1, 1, 0], [1, 1, 1], [0, 1, 1]]
return: 1
```
1. n이 1인 경우, 네트워크의 수는 1개일 수 밖에 없기 때문에 1을 반환
2. 반복문을 통해 연결된 컴퓨터를 돌면서 방문처리
3. 반복문으로 네트워크를 탐색하고 더이상 연결된 컴퓨터가 없는 경우 네트워크 개수를 + 1
4. 반목문을 통해 모든 컴퓨터를 탐색한 후 총 네트워크 개수를 반환
###[LTC] 386. Lexicographical Numbers / Medium
-[[LTC] 386. Lexicographical Numbers](https://leetcode.com/problems/lexicographical-numbers/)
> Example 1
```
Input: n = 13
Output: [1,10,11,12,13,2,3,4,5,6,7,8,9]
```
> Example 2
```
Input: n = 2
Output: [1,2]
```
1. 반복문을 돌면서 1부터 시작되는 모든 자리수를 정답 배열에 push
2. curNum이 0인 경우 정답 배열에서 제외되어야 하기 때문에 조건문을 통해 필터링
3. curNum이 가장 큰수보다 …

litae / 46주차 / 2문제

---

src/weekly46/nanii/leetCode/386_Lexicographical Numbers.ts

> Example
```js
Input: n = 13
Output: [1,10,11,12,13,2,3,4,5,6,7,8,9]
```
> Example
```js
Input: n = 2
Output: [1,2]
```
1. 주어진 숫자보다 작은 숫자들을 정렬할 때, 일의 자리 < 십의 자리 로 자릿수가 큰 값을 기준으로 오름차순으로 정렬하는 문제입니다.
2. dfs로 재귀 함수를 호출하는데 이때 숫자 1부터 9까지의 숫자를 대입합니다.
3. 그 대입한 숫자를 십진수로 이동시킨후 새로운 숫자를 for문으로 순회하면서 대입합니다.
4.  num이 1일경우, 10, 11, 12, ... 19까지 재귀호출하는데 이때 주어진 n 보다 크지 않을경우에만 result 배열에 넣어야합니다.

Nanii / 46주차 / 1문제

---

src/weekly47/litae/leetcode/419. Battleships in a Board.ts
src/weekly48/litae/leetcode/921. Minimum Add to Make Parentheses Valid.ts

- [[LTC]419. Battleships in a Board](https://leetcode.com/problems/battleships-in-a-board/)
> Example 1
```
Input: board = [["X",".",".","X"],[".",".",".","X"],[".",".",".","X"]]
Output: 2
```
> Example 2
```
Input: board = [["."]]
Output: 0
```
1. 이중 for문을 돌면서 각 배의 마지막을 찾는다
2. 마지막을 찾는 방법은 해당 문자가 X이고, 우측이나 아래에 X 문자열이 없는 경우 배의 끝이 된다
3. 조건문을 통해 위의 조건에 맞는 배의 끝의 수를 카운트한다.
- [[LTC] 921. Minimum Add to Make Parentheses Valid](https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/)
> Example 1
```
Input: s = "())"
Output: 1
```
> Example 2
```
Input: s = "((("
Output: 3
```
1. 반복문을 돌면서 문자가 "("인 경우 스택(배열)에 넣는다.
2. "("가 아닌 경우 스택의 마지막 문자가 "("이면 해당 요소를 제거한다.
3. "("가 아닐 경우 스택에 추가한다.
4. 최종 스택의 길이가 필요한 이동수가 된다.

litae / 47-48주차 / 2문제

---

src/weekly47/nanii/leetCode/419_Battleships in a Board.ts
src/weekly48/nanii/leetCode/921_Minimum Add to Make Parentheses Valid.js

> Example
```js
Input: board = [["X",".",".","X"],[".",".",".","X"],[".",".",".","X"]]
Output: 2
```
> Example
```js
Input: board = [["."]]
Output: 0
```
1. 2차원배열에서 수직,수평으로 이어져있는 전함의 개수를 세는 문제입니다.
2. 주어진 `board`를 순회하면서 전함의 시작점을 찾아서 문제를 해결하였습니다. 
3. 문자열"X"를 만났을때, 해당 인덱스를 기준으로 위 또는 왼쪽으로 X 가 있는지 확인하고, X가 없었을 경우에만 `count` 변수를 증가시켜 반환하였습니다.
----
> Example
```js
Input: s = "())"
Output: 1
```
> Example
```js
Input: s = "((("
Output: 3
```
1. 주어진 괄호문자열을 유효하면 만드는데 필요한 괄호 수를 반환하는 문제입니다.
2. 주어진 s를 순회하면서 열린괄호를 만난경우 stack 배열에 넣고,
3. 닫힌괄호를 만난경우 stack배열에 요소가 있으면 pop하여 제거합니다.
4. 이때 stack이 비었을 경우에는 불충분한 괄호세트이기때문에 `count`변수를 증가시키고,
5. 마지막 요소까지 다 순회했을때 증가시킨 `count` 와 `stack` 에 남은 요소를 더하여 최소로 필요한 괄호의 개수를 반환합니다.

Nanii / 47-48주차 / 2문제

---

src/weekly47/poco/leetCode/419_Battleships In a Board.js
src/weekly47/poco/programmers/택배배달과 수거하기.js
src/weekly48/poco/leetCode/921_Minimum Add to Make Parentheses Valid.js

- 출처 : ([링크](https://leetcode.com/problems/battleships-in-a-board/))
board : 2차원 배열. 'X'는 전함이 있는 곳, '.'은 전함이 없는 곳
전함의 수
2차원 배열 board가 주어졌을 때, "X"는 전함이 있는 곳, "."은 전함이 없는 곳이다.
전함은 가로 또는 세로로 연속되어 있으며, 한 칸을 띄고 있으면 다른 전함이다.
board에 있는 전함의 전체 개수를 구하는 문제이다.
dfs를 사용하여 문제를 해결했다.
먼저 2차원 배열 board를 순회하면서 "X"를 만나면 answer를 증가시키고, 해당 위치를 1(방문했다는 표시)로 바꾼다.
그리고 해당 i, j를 dfs의 매개변수로 전달한다.
dfs에서는 i, j를 기준으로 상하좌우 위치에 "X"가 있는지를 확인하고,
"X"가 있다면 해당 위치를 1(방문했다는 표시)로 바꾸고 다시 그 위치를 기준으로 상하좌우에 "X"가 있는지를 확인한다.
이렇게 반복하면, 전함의 개수를 구할 수 있다.
--- 
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/150369?language=javascript))
cap : 트럭이 한 번에 실을 수 있는 재활용 택배 상자의 개수
n : 집의 개수
deliveries : 배달할 재활용 택배 상자의 개수를 담은 배열
deliveries[i]는 i+1번째 집에 배달할 재활용 택배 상자의 개수를 나타냅니다.
pickups : 수거할 빈 재활용 택배 상자의 개수를 담은 배열
pickups[i]는 …

Poco / 47 ~ 48주차 / 3문제

---

src/weekly49/poco/programmers/가장많이받은선물.js
src/weekly49/poco/programmers/도넛과막대그래프.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/258712))
friends : 친구들의 이름을 담은 1차원 문자열 배열
gifts : 이번 달까지 친구들이 주고받은 선물 기록을 담은 1차원 문자열 배열, ["A B"] 형태이며, A가 B에게 선물을 줬다는 의미이다.
다음 달에 가장 많은 선물을 받을 친구가 받을 선물의 수
친구들의 이름을 담은 1차원 문자열 배열 friends와 이번 달까지 친구들이 주고받은 선물 기록을 담은 1차원 문자열 배열 gifts가 매개변수로 주어질 때,
다음 달에 가장 많은 선물을 받을 친구가 받을 선물의 수를 구하는 문제.
만약 A와 B가 선물을 주고받았다면, 두 사람 사이에 더 많이 선물을 준 사람이 다음 달에 선물을 받는다.
만약 두 사람이 선물을 주고받지 않았거나, 두 사람 사이에 주고 받은 선물의 개수가 동일하다면, 선물 지수가 더 큰 사람이 더 작은 사람에게 하나를 받는다.
선물 지수는 이번 달에 선물을 준 횟수에서 받은 횟수를 뺀 값이다.
만약, 두 사람의 선물 지수까지 같다면 다음달에 선물을 주고 받지 않는다.
두 사람의 선물을 주고 받은 횟수가 다르다 -> 더 많이 준 사람이 다음 달에 선물을 받는다.
두 사람이 선물을 주고 받은 횟수가 같거나 주고 받은 적이 없다 -> 선물 지수 높은 사람이 받는다.
두 사람이 선물을 주고 받은 횟수가 같거나 주고 받은 적이 없으며, 선물 지수가 같다 -> 선물을 주고 받지 않는다.
friends, gifts를 순회하여 friendsObj라는 객체를 …

Poco / 49주차 / 2문제

---

src/weekly49/litae/programmers/가장 많이 받은 선물.ts
src/weekly49/litae/programmers/도넛과 막대 그래프.ts

- [[PGS] 가장 많이 받은 선물 / Lv. 1](https://school.programmers.co.kr/learn/courses/30/lessons/258712)
> Example 1
```
friends: ["muzi", "ryan", "frodo", "neo"]
gifts: ["muzi frodo", "muzi frodo", "ryan muzi", "ryan muzi", "ryan muzi", "frodo muzi", "frodo ryan", "neo muzi"]
result: 2
```
> Example 2
```
friends: ["joy", "brad", "alessandro", "conan", "david"]
gifts: ["alessandro brad", "alessandro joy", "alessandro conan", "david alessandro", "alessandro david"]
result: 4
```
> Example 3
```
friends: ["a", "b", "c"]
gifts: ["a b", "b a", "c a", "a c", "a c", "c a"]
result: 0
```
1. 반복문을 돌며 친구별 선물 보낸 횟수와 받은 횟수를 카운트
2. 친구들끼리 서로 비교해 더 많은 선물을 준 사람의 결과 배열 플러스
3. 만약 서로 주고 받은 적이 없거나 같은 횟수를 주고 받은 경우, 선물 지수가 높은 사람의 결과값을 플러스
4. 결과 배열을 반복문으로 돌며 선물을 가장 많이 받은 친구를 찾는다
</br>
</br>
---
</br>
</br>
- [[PGS] 도넛과 …

litae / 49주차 / 2문제

---

src/weekly50/den/programmers/무인도여행.js
src/weekly51/den/programmers/연속된 부분 수열의 합.js

- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/154540)
이 문제는 주어진 지도에서 섬의 크기를 구해야 합니다.
dfs헬퍼 함수를 구현해 주어지는 maps 배열에 대해서 깊이 우선탐색을 수행해서 각 섬의 크기를 계산했습니다.
계산 후 오름차순 정렬을 해서 반환해 문제를 풀었습니다.

Den / 50주차-51주차 / 2문제

---

src/weekly50/nanii/programmers/무인도여행.js
src/weekly51/nanii/programmers/연속된부분수열의합.js

> Example
maps | result
-- | --
["X591X","X1X5X","X231X", "1XXX1"] | [1, 1, 27]
["XXX","XXX","XXX"] | [-1]
1. 주어진 배열을 2차원 배열로 변환한뒤 전체를 2중 for문으로 순회합니다.
2. 현재 인덱스의 값이 섬일 때 (`current !=="X"`) dfs 재귀합니다.
3. 그 주어진 인덱스부터 시작하여 오른쪽, 왼쪽, 위, 아래의 값들을 살펴보면서 "X"가 아니면서, 맨 끝값이 아닐 때 => 섬일 때
4. 값을 더하고, 방문처리하여 최대 머무를 수 있는 기간을 구합니다.
----
> Example
sequence | k | result
-- | -- | --
[1, 2, 3, 4, 5] | 7 | [2, 3]
[1, 1, 1, 2, 3, 4, 5] | 5 | [6, 6]
[2, 2, 2, 2, 2] | 6 | [0, 2]
1. 주어진 배열을 순회하면서 `sum`이 k일 때 인덱스를 배열에 모두 넣고, 그 배열을 오름차순으로 정렬하여 첫번째 인덱스의 값을 반환하려고 했지만 시간초과되었습니다.
2. 두번째 방법으론 두 인덱스의 값을 기준으로 시작하면서 오른쪽으로 하나씩 이동하며 `sum` 을 구하는 방법입니다.
3. `[0,0]` 인덱스부터 시작하여 합이 작을 땐 더하고, 더 클 경우 빼면서 인덱스의 위치를 찾습니다.
4. sum의 값이 k와 같아졌을 때 정답 배열에 인덱스의 정보를 배열로 넣고,
5. 다시 오른쪽으로 인덱스를 이동시켜 탐색합니다.
----
> Example
land | result
-- | --
[[0, …

Nanii / 50-51주차 / 2.5문제

---

src/weekly52/den/programmers/방문길이.js
src/weekly52/den/programmers/튜플.js

- 출처 : [[PGS] 튜플 / Lv.2](https://github.com/Algorithm-Squad/Algorithm/commit/f51da48d010698fafa1304756747f25949473b5a)
> Example 1
```js
Input: "{{2},{2,1},{2,1,3},{2,1,3,4}}"
Output: [2, 1, 3, 4]
```
특정 튜플을 나타내는 집합이 담긴 문자열 s가 매개변수로 주어질 때, s가 표현하는 튜플을 배열에 담아 반환하는 함수를 구현해야 된다.
여러개의 집합이 동일한 튜플을 표현할 수도 있다. 예를 들어,
{{2}, {2, 1}, {2, 1, 3}, {2, 1, 3, 4}}
{{2, 1, 3, 4}, {2}, {2, 1, 3}, {2, 1}}
{{1, 2, 3}, {2, 1}, {1, 2, 4, 3}, {2}}
위 3개의 집합은 동일한 튜플 (2,1,3,4) 을 표현한다. 
그렇다면 각각의 집합이 매개변수로 주어졌을 때, 이 집합이 어떤 튜플을 가르키는지 알 방법이 있을까?
문제를 보면 튜플이 주어 질때, 
{{a1}, {a1, a2}, {a1, a2, a3}, {a1, a2, a3, a4}, ... {a1, a2, a3, a4, ..., an}}
위 처럼 표현될 수 있다고 하는데, 각 집합(?)의 길이가 작은 것부터 나열되어 있는 것을 알 수 있다.
이를 토대로, 매개변수 s가 주어졌을때, 길이가 짧은 집합부터 정렬 후에 각 집합을 순회하며
각 집합 내 요소를 Set에 넣으면, 중복되는 요소가 제거되고 순회가 끝나면 해당 매개변수가 표현하는 튜플을 구할 수 …

Den / 52주차 / 2문제

---

src/weekly52/litae/programmers/방문 길이.ts
src/weekly52/litae/programmers/튜플.ts

- [[PGS] 방문 길이 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/49994)
> Example 1
```
dirs: "ULURRDLLU"
answer: 7
```
> Example 2
```
dirs: "LULLLLLLU"
answer: 7
```
- [[PGS] 튜플 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/64065)
> Example 1
```
s: "{{2},{2,1},{2,1,3},{2,1,3,4}}"
result: [2, 1, 3, 4]
```
> Example 2
```
s: "{{1,2,3},{2,1},{1,2,4,3},{2}}"
result: [2, 1, 3, 4]
```
> Example 3
```
s: "{{20,111},{111}}"
result: [111, 20]
```
> Example 4
```
s: "{{4,2,3},{3},{2,3,4,1},{2,3}}"
result: [3, 2, 4, 1]
```

litae / 52주차 / 2문제

---

src/weekly52/poco/programmers/방문길이.js
src/weekly52/poco/programmers/튜플.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/49994))
dirs : 이동할 경로("U", "D", "R", "L"로 이루어진 문자열)
dirs로 이동한 경로 중 처음 가본 길의 길이를 반환
dirs로 이동한 경로 중 처음 가본 길의 길이를 반환하는 문제이다.
처음 가본 길의 길이를 구하기 위해서는 Set 객체를 사용하여 중복을 허용하지 않아야한다.
먼저 "U", "D", "R", "L"로 이루어진 문자열을 객체로 만들어 이동할 수 있는 좌표를 만들었다.
for문으로 dirs를 순회하면서, 현재 좌표와 다음 좌표를 구하고, 범위를 벗어나는 경우는 continue로 넘어가고,
중복을 허용하지 않기 위해 현재지점, 다음지점 과 다음지점, 현재점을 저장했다.
처음 가본 지점이 아니라, 처음 가본 길이기 때문에, 2개의 경우를 저장해야한다.
중복을 허용하지 않기 때문에 visited.size / 2를 반환하면 된다.
---
- 출처 : ([링크]https://school.programmers.co.kr/learn/courses/30/lessons/64065)
s: 특정 튜플을 표현하는 집합이 담긴 문자열 s
s가 표현하는 튜플을 배열에 담아 반환
특정 튜플을 표현하는 집합이 담긴 문자열 s가 주어진다.
s가 표현하는 튜플을 배열에 담아 반환하는 문제이다.
튜플은 다음과 같은 성질을 가지고 있다.
중복된 원소가 있을 수 있습니다. ex : (2, 3, 1, 2)
원소에 정해진 순서가 있으며, 원소의 순서가 다르면 서로 다른 …

Poco / 52주차 / 2문제

---

src/weekly53/litae/programmers/스킬트리.ts
src/weekly53/litae/programmers/영어 끝말잇기.ts
src/weekly54/litae/programmers/배달.ts
src/weekly54/litae/programmers/점프와 순간 이동.ts

- [[PGS] 스킬트리](https://school.programmers.co.kr/learn/courses/30/lessons/49993)
> Example 1
```
skill: "CBD"
skill_trees: ["BACDE", "CBADF", "AECB", "BDA"]
return: 2
```
1. 스킬트리가 올바르게 사용된 경우, 스킬은 중복되어 사용되지 않기 때문에 주어진 skill_tree에서 스킬트리에 없는 스킬을 제거하면 skill과 같은 순서를 가진 문자열이 나오게 된다.
2. 위의 성질을 이용하여 skill_trees의 요소를 하나씩 skill의 index와 동일한지 여부를 확인한다.
- [[PGS] 영어 끝말잇기](https://school.programmers.co.kr/learn/courses/30/lessons/12981)
> Example 1
```
n: 3
words: ["tank", "kick", "know", "wheel", "land", "dream", "mother", "robot", "tank"]
result: [3, 3]
```
> Example 2
```
n: 5
words: ["hello", "observe", "effect", "take", "either", "recognize", "encourage", "ensure", "establish", "hang", "gather", "refer", "reference", "estimate", "executive"]
result: [0, 0]
```
> Example 3
```
n: 2
words: ["hello", …
```

litae / 53 - 54주차 / 3문제

---

src/weekly55/den/programmers/줄서는방법.ts
src/weekly55/den/programmers/행렬의곱셈.ts

- 출처 : [programmers - lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/12949)
> Example 1
```js
Input:  [ [2, 3, 2], [4, 2, 4], [3, 1, 4] ], [ [5, 4, 3], [2, 4, 1], [3, 1, 1] ]
Output: [[22, 22, 11], [36, 28, 18], [29, 20, 14]]
```
수학에서 행렬의 곱셈 로직을 그대로 함수로 구현하면 되는 문제다.
행렬 곱셈 로직 흐름을 토대로 3중 for문을 이용해서 주어지는 2개의 2차원 배열을 순회해서 곱셈 결과를 구했다.
---
- 출처 : [programmers - lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
> Example 1
```js
Input:  3, 5
Output: [3, 1, 2]
```
주어지는 숫자 n으로 만들 수 있는 순열을 배열로 모두 구하고, 이 배열들이 사전순으로 나열했을 때, k 번째 배열을 반환하는 함수를 구현하는 문제다. 숫자 n으로 가능한 모든 순열을 구해야하기 때문에, dfs를 활용했다.
우선 숫자 n으로 만들 수 있는 1부터 n까지의 기본 배열을 구하고, dfs를 진행할 때 참고할 index별 방문여부를 담은 배열을 선언한다.
dfs를 위해 dfs 헬퍼 함수를 선언하는데, 이 함수의 매개변수는 dfs 진행시 사용할 숫자 depth와 탐색을 진행하며 만들어지는 순열을 넣을 배열 result를 …

Den / 55주차 / 2문제

---

src/weekly55/litae/programmers/줄 서는 방법.ts
src/weekly55/litae/programmers/행렬의 곱셈.ts

- [[PGS] 행렬의 곱셈 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/12949)
> Example 1
```
arr1: [[1, 4], [3, 2], [4, 1]]
arr2: [[3, 3], [3, 3]]
return: [[15, 15], [15, 15], [15, 15]]
```
> Example 2
```
arr1: [[2, 3, 2], [4, 2, 4], [3, 1, 4]]
arr2: [[5, 4, 3], [2, 4, 1], [3, 1, 1]]
return: [[22, 22, 11], [36, 28, 18], [29, 20, 14]]
```
- [[PGS] 줄 서는 방법 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
> Example 1
```
n: 3
k: 5
return: [3, 1, 2]
```

litae / 55주차 / 2문제

---

src/weekly56/den/programmers/짝지어제거하기.js

- 출처 : [programmers - lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/12973)
> Example 1
```js
Input: baabaa
Output: 1
```
주어지는 문자열을 순회하며 2번 연속되는 알파벳이 있으면 제거하고, 이후 반복 순회하며 짝지어 있는 알파벳을 모두 제거 했을 때, 문자열의 길이가 0이 되는지 여부를 판단하는 함수를 구현하는 문제입니다.
stack 구조를 활용해서, 각각의 문자열을 stack에 넣고, stack의 끝 문자열과 현재 순회 중인 문자열이 동일하다면 pop해주는 로직으로 해당 함수를 구현했습니다.

Den / 56주차 / 1주차

---

src/weekly56/poco/programmers/오픈채팅방.js
src/weekly56/poco/programmers/짝지어제거하기.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/87390))
record : 채팅방에 들어오고 나가거나, 닉네임을 변경한 기록이 담긴 문자열 배열
최종적으로 방을 개설한 사람이 보게 되는 메시지를 문자열 배열 형태로 반환
채팅방에 들어오고 나가거나, 닉네임을 변경한 기록이 담긴 문자열 배열이 주어진다.
이때, 최종적으로 방을 개설한 사람이 보게 되는 메시지를 문자열 배열 형태로 반환하는 문제이다.
채팅방에 들어오면 "닉네임님이 들어왔습니다."라는 메시지가 출력되고, 나가면 "닉네임님이 나갔습니다."라는 메시지가 출력된다.
닉네임을 변경하면 기존 닉네임으로 작성된 메시지들이 변경된 닉네임으로 수정된다.
채팅방은 중복으로 닉네임을 허용한다.
닉네임 변경은 채팅방에서 하거나, 채팅방에서 나간 후 새로운 닉네임으로 다시 들어간다.
첫 번째 시도와 달리 record를 한번만 순회하였고, 추가로 순회하는 것은 Change 기록을 제외한 answer 배열을 순회하였다.
먼저 record 배열을 순회하면서, answer 배열에 uid와 메시지 배열을 저장하였고, uid에 따른 nickName을 Map 객체로 관리하였다.
마지막으로 answer 배열을 순회하면서, uid에 해당하는 nickName과 메시지를 반환하였다
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/12973))
s : 소문자 문자열
짝지어 제거하는 과정을 성공적으로 수행할 수 있으면 1을, …

Poco / 56주차 / 2문제

---

src/weekly56/litae/programmers/오픈채팅방.ts
src/weekly56/litae/programmers/짝지어 제거하기.ts

- [[PGS] 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888)
> Example 1
```
record: ["Enter uid1234 Muzi", "Enter uid4567 Prodo","Leave uid1234","Enter uid1234 Prodo","Change uid4567 Ryan"]
result: ["Prodo님이 들어왔습니다.", "Ryan님이 들어왔습니다.", "Prodo님이 나갔습니다.", "Prodo님이 들어왔습니다."]
```
1. user는 유저의 id와 상태를 담는 객체
2. state가 Enter이거나 Change일 경우 아이디에 따라 닉네임을 설정
3. state가 Change가 아닐 경우 answer 배열에 id와 state를 저장
4. answer 배열의 id와 state를 이용하여 log 메세지 완성
<br />
<br />
- [[PGS] 짝지어 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973)
> Example 1
```
s: baabaa
result: 1
```
> Example 2
```
s: cdcd
result: 0
```
1. 스택 생성
2. 스택의 맨 마지막 문자와 현재 순서의 문자를 비교하여 같을 경우 두 문자를 제거, 다를 경우 현재 문자를 스택에 추가
3. 예시(baabaa)
[loop 1]
stack.length === 0 이므로 s[0]을 stack에 추가
[loop 2]
stack.length …

litae / 56주차 / 2문제

---

src/weekly56/nanii/programmers/오픈채팅방.js
src/weekly56/nanii/programmers/짝지어제거하기.js

> Example 1
record | result
-- | --
["Enter uid1234 Muzi", "Enter uid4567 Prodo","Leave uid1234","Enter uid1234 Prodo","Change uid4567 Ryan"] | ["Prodo님이 들어왔습니다.", "Ryan님이 들어왔습니다.", "Prodo님이 나갔습니다.", "Prodo님이 들어왔습니다."]
- 주어진 배열을 순회하면서 nickname은 변경가능성이 있기때문에 id를 result에 저장하고
- id를 기준으로 nickname이 변경되었는지 또는 Change action으로 nickname을 변경하였는지 확인한 뒤 nicknameMap 객체로 Id와 nickname을 관리하였습니다.
- 최종적으로 result에서 id를 nicknameMap에서 찾아 nickname으로 변경하고 text를 연결하여 결과를 반환하였습니다.
> Example 1
s | result
-- | --
baabaa | 1
cdcd | 0
- 주어진 문자열을 순회하면서 첫번째 문자열을 answer 배열에 우선 넣고 시작
- answer 배열의 마지막 문자열과 현재 값을 비교했을 때 값이 같으면 pop하고, 다르면 push
- 최종적으로 answer 배열의 길이가 0이면 1 아니면 0 을 반환

Nanii / 56주차 / 2문제

---

src/weekly57/litae/programmers/n^2 배열 자르기.ts
src/weekly57/litae/programmers/야근 지수.ts

- [[PGS] n^2 배열 자르기 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/87390)
> Example 1
```
n: 3
left: 2
right: 5
result: [3,2,2,3]
```
> Example 2
```
n: 4
left: 7
right: 14
result: [4,3,3,3,4,4,4,4]
```
- 규칙: 좌표의 (x, y)값 중 더 큰 값이 해당 위치의 숫자가 됨(ex, (1, 1)의 값은 2)
1. 몫과 나머지를 이용하여 시작하는 지점(left)와 끝나는 지점(right)의 좌표를 구할 수 있음
2. 찾은 시작점과 끝나는 지점만 반복문을 돌려 해당하는 값을 찾아냄
<br />
<br />
- [[PGS] 야근 지수 / Lv. 3](https://school.programmers.co.kr/learn/courses/30/lessons/12927)
> Example 1
```
works: [4, 3, 3]
n: 4
result: 12
```
> Example 2
```
works: [2, 1, 2]
n: 1
result: 6
```
> Example 3
```
works: [1,1]
n: 3
result: 0
```
1. 퇴근 전까지 모든 업무를 끝낼 수 있는 경우(잔업의 총 합 <= 퇴근까지 남은 시간)는 0을 반환
2. works 배열을 내림차순으로 정렬하여 sorted에 저장
3. while문을 돌면서 가장 큰 수(sorted[0])를 max 변수에 저장
4. for문을 돌면서 가장 큰 수와 …

litae / 57주차 / 2문제

---

src/weekly58/den/programmers/뉴스클러스터링.js
src/weekly58/den/programmers/압축.js

- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/17677)
```js
console.log(solution("FRANCE", "french")); // 16384
console.log(solution("handshake", "shake hands")); // 65536
console.log(solution("aa1+aa2", "AAAA12")); // 43690
console.log(solution("E=M*C^2", "e=m*c^2")); // 65536
```
입력되는 두 문자열을 두 글자씩 끊어서 다중집합의 원소로 만든 후, 두 다중집합 간의 교집합과 합집합을 구해 자카드 유사도를 구하는 문제입니다.
문제의 요구사항대로, 우선 두 문자열을 정규표현식을 이용해 알파벳으로만 이루어진 다중집합 배열로 만든 후, 두 배열의 교집합과 합집합을 구해서 자카드 유사도를 계산하는 합수를 구현했습니다.
---
- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/17684)
> Example 1
```js
console.log(solution("KAKAO")); // [11, 1, 27, 15]
console.log(solution("TOBEORNOTTOBEORTOBEORNOT")); // [20, 15, 2, 5, 15, 18, 14, 15, 20, 44, 45, 18, 15, 18, 20] …
```

Den / 58주차 / 2문제

---

src/weekly58/nanii/programmers/뉴스클러스터링.js
src/weekly58/nanii/programmers/압축.js

> example
str1 | str2 | answer
-- | -- | --
FRANCE | french | 16384
handshake | shake hands | 65536
aa1+aa2 | AAAA12 | 43690
E=M*C^2 | e=m*c^2 | 65536
> 문제풀이
1. 주어진 문자열을 순회하면서 영소문자가 아닌 문자열은 제외하거나 소문자로 변환시키고,
2. 그 변환한 배열들을 모두 합쳐서 교집합과 합집합을 함께 찾습니다.
3. 모두 합친 set 배열을 순회하면서 각각의 배열에서 일치하는 요소들의 길이를 구하고
4. 교집합은 일치하는 요소들의 최솟값을
5. 합집합은 일치하는 요소들의 최댓값을 나타냅니다.
6. 만약 교집합이 0이면 1로 처리하고 그렇지 않으면 교집합 / 합집합을 구하여 값을 계산합니다.
> example
msg | answer
-- | --
KAKAO | [11, 1, 27, 15]
TOBEORNOTTOBEORTOBEORNOT | [20, 15, 2, 5, 15, 18, 14, 15, 20, 27, 29, 31, 36, 30, 32, 34]
ABABABABABABABAB | [1, 2, 27, 29, 28, 31, 30]
> 문제풀이
1. 문자열을 순회하면서 하나씩 이어붙인 새로운 문자열을 사전에 등록하는 문제입니다.
2. 사전에 없는 문자열이라면 추가하고
3. 추가하기 직전의 문자열 인덱스를 출력하고,
4. 현재 문자열의 위치부터 다시 순회하면서 문자열들을 처리하고
5. 마지막 남은 문자열이 있다면 해당 문자열의 인덱스를 구하여 출력합니다.

Nanii / 58주차 / 2문제

---

src/weekly58/litae/programmers/뉴스 클러스터링.ts
src/weekly58/litae/programmers/압축.ts

-[[PGS] 뉴스 클러스터링](https://school.programmers.co.kr/learn/courses/30/lessons/17677)]
> Example 1
```
str1: FRANCE
str2: french
answer: 16384
```
> Example 2
```
str1: handshake
str2: shake hands
answer: 65536
```
> Example 3
```
str1: aa1+aa2
str2: AAAA12
answer: 43690
```
> Example 4
```
str1: E=M*C^2
str2: e=m*c^2
answer: 65536
```
<br />
<br />
-[[PGS] 압축](https://school.programmers.co.kr/learn/courses/30/lessons/17684)]
> Example 1
```
msg: KAKAO
answer: [11, 1, 27, 15]
```
> Example 2
```
msg: TOBEORNOTTOBEORTOBEORNOT
answer: [20, 15, 2, 5, 15, 18, 14, 15, 20, 27, 29, 31, 36, 30, 32, 34]
```
> Example 3
```
msg: ABABABABABABABAB
answer: [1, 2, 27, 29, 28, 31, 30]
```

litae / 58주차 / 2문제

---

src/weekly58/poco/programmers/뉴스클러스터링.js
src/weekly58/poco/programmers/압축.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/17677))
str1 : 문자열
str2 : 문자열
두 문자열의 자카드 유사도를 반환하는 문제
두 문자열의 자카드 유사도를 구하는 문제
자카드 유사도란 두 집합의 교집합 크기를 두 집합의 합집합 크기로 나눈 값
만약 두 집합 모두 공집합일 경우에는 나눗셈이 정의되지 않으니 따로 1로 정의한다.
다중집합 A는 원소 "1"을 3개 가지고 있고, 다중집합 B는 원소 "1"을 5개 가지고 있다면,
다중집합 A와 B의 교집합은 원소 "1"을 min(3,5)인 3개, 합집합은 "1"을 max(3,5)인 5개가 된다.
문자열 사이의 유사도를 계산하는데 이용하면, 두 글자씩 끊어서 다중집합을 만들 수 있다.
"FRANCE"와 "FRENCH"는 두 글자씩 끊어서 자카드 유사도를 판단하면 교집합 2, 합집합 8로 0.25가 된다.
입력으로 str1, str2라는 문자열이 들어올 때, 매개변수 str1과 str2를 두 글자씩 끊어서 다중집합 원소로 만들고
영문으로 된 글자 쌍만 유효, 기타 공백이나 숫자, 특수 문자가 들어있는 경우에는 그 글자 쌍을 버린다.
만약 "ab+"가 들어오면, "ab"만 다중집합의 원소로 삼고, "b+"는 버린다. 
다중집합 원소 사이를 비교할 때, 대문자와 소문자의 차이는 무시한다.
str1, str2의 자카드 유사도를 반환하는 문제(유사도 값은 0에서 1사이의 실수이므로, 65536을 곱한 후 소수점 아래를 버리고 정수부만 출력)
str1, str2를 순회하면서 연속으로 …

Poco / 58주차 / 2문제

---

src/weekly59/litae/programmers/메뉴 리뉴얼.ts
src/weekly59/litae/programmers/방금그곡.ts
src/weekly60/litae/programmers/캐시.ts
src/weekly60/litae/programmers/파일명 정렬.ts

- [[PGS] 메뉴 리뉴얼 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/72411)
> Example 1
```
orders: ["ABCFG", "AC", "CDE", "ACDE", "BCFG", "ACDEH"]
course: [2,3,4]
result: ["AC", "ACDE", "BCFG", "CDE"]
```
> Example 2
```
orders: ["ABCDE", "AB", "CD", "ADE", "XYZ", "XYZ", "ACD"]
course: [2,3,5]
result: ["ACD", "AD", "ADE", "CD", "XYZ"]
```
> Example 3
```
orders: ["XYZ", "XWY", "WXA"]
course: [2,3,4]
result: ["WX", "XY"]
```
1. getCombinations 함수는 length에 맞는 조합을 생성하는 함수
2. forEach로 지정된 메뉴 개수의 모든 경우의 수를 생성
3. forEach로 menuCountMap 객체에 메뉴 주문 횟수를 저장
4. 가장 많이 주문된 메뉴의 횟수를 찾고 해당하는 메뉴를 추가
5. 오름차순으로 정렬 후 반환
- [[PGS] 방금그곡 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/17683)
> Example 1
```
m: "ABCDEFG"
musicinfos: ["12:00,12:14,HELLO,CDEFGAB", …
```

litae / 59 - 60주차 / 4문제

---

src/weekly59/den/programmers/[3차]방금그곡.js
src/weekly60/den/programmers/[1차]캐시.js
src/weekly60/den/programmers/[3차]파일명정렬.js

- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/17683)
여러 조건을 잘 고려해서 풀어야했던 문제였습니다.
1. 음은 알파벳으로만 이루어져 있지 않고 "#"이 붙어있는 음도 있다.
2. 음악 길이보다 재생된 시간이 길 때는 음악이 끊김 없이 처음부터 반복된다.
3. 음악 길이보다 재생된 시간이 짧을 때는 처음부터 재생 시간만큼 재생된다.
4. 조건이 일치하는 음악이 여러 개일 때에는 라디오에서 재생된 시간이 제일 긴 음악 제목을 반환한다.
5. 재싱된 시간도 같을 경우 먼저 입력된 음악 제목을 반환한다.
구현한 코드의 경우 위 조건을 고려해 풀었습니다.

Den / 59주차 - 60주차 / 3문제

---

src/weekly59/poco/programmers/메뉴리뉴얼.js
src/weekly59/poco/programmers/방금그곡.js
src/weekly60/poco/programmers/캐시.js
src/weekly60/poco/programmers/파일명정렬.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/17683))
m : 기억하고 있는 멜로디를 담은 문자열(1 <= m <= 1439)
musicinfos : 방송된 곡의 정보를 담고 있는 배열( musicinfos <= 100이며 요소는 음악 시작 시간, 끝난시간, 음악 제목, 악보 정보가 ","로 구분된 문자열)
조건과 일치하는 음악 제목을 반환
음악이 주어진 시간만큼 재생되었을 때, user가 기억하는 음과 일치하는 경우 음악 제목을 반환하는 문제
음악 길이보다 재생된 시간이 긴 경우에는 음악은 처음부터 반복 재생된다
음악 길이보다 재생된 시간이 짧은 경우에는 처음부터 재생 시간만큼 재생된다
조건이 일치하는 음악이 여러 개일 때에는 라디오에서 재생된 시간이 긴 음악 제목을 반환
재생된 시간까지 같은 경우에는 먼저 입력된 음악 제목을 반환
조건에 일치하는 음악이 없으면 "(None)"을 반환
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/72411))
orders : 손님들의 주문이 담긴 배열
course : 추가하고 싶어하는 코스요리를 구성하는 단품메뉴들의 갯수
새로 추가하게 될 코스요리의 메뉴 구성을 문자열 형태로 배열에 담아 반환하는 문제
코스요리 메뉴는 최소 2가지 이상의 단품메뉴로 구성하고 최소 2명 이상의 손님으로부터
주문된 단품메뉴 조합에 대해서만 코스요리 메뉴 후보에 포함한다.
course 배열에 들어있는 코스요리를 구성하는 …

Poco / 59주차 - 60주차 / 4문제

---

src/weekly61/litae/programmers/k진수에서 소수 개수 구하기.ts
src/weekly61/litae/programmers/삼각 달팽이.ts

- [[PGS] k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
> Example 1
```
n: 437674
k: 3
result: 3
```
> Example 2
```
n: 110011
k: 10
result: 2
```
</br>
</br>
</br>
- [[PGS] 삼각 달팽이](https://school.programmers.co.kr/learn/courses/30/lessons/68645)
> Example 1
```
n: 4
result: [1,2,9,3,10,8,4,5,6,7]
```
> Example 2
```
n: 5
result: [1,2,12,3,13,11,4,14,15,10,5,6,7,8,9]
```
> Example 3
```
n: 6
result: [1,2,15,3,16,14,4,17,21,13,5,18,19,20,12,6,7,8,9,10,11]
```

litae / 61주차 / 2문제

---

src/weekly61/den/programmers/k진수에서 소수 개수 구하기.js
src/weekly61/den/programmers/삼각달팽이.js

- 출처 : (programmers - Lv.2)[https://school.programmers.co.kr/learn/courses/30/lessons/68645]
---
- 출처 : (programmers - Lv.2)[https://school.programmers.co.kr/learn/courses/30/lessons/92335]

Den / 61주차 / 2문제

---

src/weekly61/poco/programmers/k진수에서소수개수구하기.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/92335))
n : 1 이상 100,000 이하인 자연수
k : 2 이상 10 이하인 자연수
변환된 수 안에서 찾을 수 있는 위 조건에 맞는 소수의 개수
매개변수 n을 k진수로 변환했을 때, 변환된 수 안에 아래 조건에 맞는 소수가 몇 개인지 구하는 문제
0P0처럼 소수 양쪽에 0이 있는 경우
P0처럼 소수 오른쪽에만 0이 있고 왼쪽에는 아무것도 없는 경우
0P처럼 소수 왼쪽에만 0이 있고 오른쪽에는 아무것도 없는 경우
P처럼 소수 양쪽에 아무것도 없는 경우
단, P는 각 자릿수에 0을 포함하지 않는 소수입니다.
예를 들어, 101은 P가 될 수 없습니다.
n을 k진수로 변환한 후 배열로 만들고 forEach로 순회하면서 해당 요소가 0이 아니라면 temp에 저장하고 아닌 경우에는 temp에 저장된 값을 소수인지 판별한 후 answer에 추가
마지막에 temp에 값이 남아있는 경우에도 소수인지 판별한 후 answer에 추가

Poco / 61주차 / 1문제

---

src/weekly62/litae/programmers/괄호 변환.ts
src/weekly62/litae/programmers/프렌즈4블록.ts
src/weekly63/litae/programmers/n진수 게임.ts
src/weekly63/litae/programmers/멀쩡한 사각형.ts
src/weekly64/litae/programmers/과제 진행하기.ts

- [[PGS] 프렌즈4블록 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/17679)
> Example 1
```
m: 4
n: 5
board: ["CCBDE", "AAADE", "AAABF", "CCBBF"]
result: 14
```
> Example 2
```
m: 6
n: 6
board: ["TTTANT", "RRFACC", "RRRFCC", "TRRRAA", "TTMMMF", "TMMTTJ"]
result: 15
```
1. board를 2차원 배열로 변환
2. 이중 반복문을 통해 2x2로 같은 모양의 블록을 찾아 제거하고 좌상단 블록 좌표를 removedBlock에 저장
3. 없앨 수 있는 블록이 없는 경우 반복문 종료
4. 저장된 배열을 돌면서 제거되어야 하는 블록을 "X"로 변경
5. 블록 정렬
6. "X"로 남아있는 블록 개수를 세기
</br>
</br>
</br>
- [[PGS] 괄호 변환 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/60058)
> Example 1
```
p: "(()())()"
result: "(()())()"
```
> Example 2
```
p: ")("
result: "()"
```
> Example 3
```
p: "()))((()"
result: "()(())()"
```
1. balancedString는 균형잡힌 괄호 문자열 u, v로 분리하는 함수
2. isCorrectString는 올바른 괄호 …

litae / 62 - 64주차 / 5문제

---

src/weekly62/den/programmers/[1차]프렌즈4블록.js
src/weekly62/den/programmers/괄호변환.js
src/weekly64/den/programmers/과제진행하기.js

- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/17679)
> Example 1

Den / 62주차, 64주차 / 2문제

---

src/weekly62/nanii/programmers/괄호변환.js
src/weekly63/nanii/programmers/n진수게임.js
src/weekly63/nanii/programmers/멀쩡한사각형.js
src/weekly64/nanii/programmers/과제진행하기.js

> example
n | t | m | p | result
---|---|---|---|---
2 | 4 | 2 | 1  | "0111"
16 | 16 | 2 | 1 | "02468ACE11111111"
16 | 16 | 2 | 2 | "13579BDF01234567"
> 문제풀이
- 게임에 참가하는 인원 * 튜브 순서 만큼의 문자열을 생성할 때까지 주어진 n 진법에 맞는 숫자를 변환하여 연결합니다.
- 이때 튜브가 말할 문자열만 필요로 하므로 전체 str에서 튜브 순서에 맞는 인덱스의 위치를 구하여 해당 문자열을 이어붙여 반환합니다.
-------
> example
W | H | result
---|---|---
8 | 12 | 80
> 문제풀이
- 사각형의 변을 한칸씩 늘려가며 규칙을 찾았을 때 대각선을 지나지 않은 사각형의 개수 = 너비 * 높이 - ( 너비와 높이의 최대 공약수 ) 임을 이용합니다.
- 이때 최대 공약수를 구하는 함수를 생성하여 답을 구하였습니다.
```
// 유클리드 호제법
3 % 4 = 3
4 % 3 = 1
3 % 1 = 0
=> 최대공약수는 1 (나머지가 0일 때 나눈 값)
```
-------
> example
p | result
---|---
"(()())()" | "(()())()"
")(" | "()"
"()))((()" | "()(())()"
> 문제풀이
- 균형잡힌 괄호 문자열을 분리하고 이 문자열이 올바른 문자열인지 아닌지를 확인합니다.
- 이때 문제에 적힌대로 올바른 괄호 문자열이라면 재귀적으로 solution함수를 수행하고
- 올바른 괄호 문자열이 아니라면 첫번째 …

Nanii / 62-64주차 / 4문제

---

src/weekly65/litae/programmers/2 x n 타일링.ts
src/weekly65/litae/programmers/하노이의 탑.ts
src/weekly66/litae/programmers/혼자 놀기의 달인.ts

- [[PGS] 2 x n 타일링 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/12900)
> Example 1
```
n: 4
result: 5
```
1. n은 60,000이하의 자연수로 DFS로 해결하기에는 너무 많은 경우의 수가 발생, 따라서 DP를 활용한 풀이
2. 타일링 경우의 수가 피보나치 수열의 패턴임을 확인
3. 값을 변수에 저장하여 memorization
4. 숫자 크기를 줄이기 위해서 반복문을 돌면서 1000000007 나머지 값 구하여 저장하기
</br>
</br>
</br>
- [[PGS] 하노이의 탑 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/12946)
> Example 1
```
n: 2
result: [ [1,2], [1,3], [2,3] ]
```
1. 재귀를 통해 문제 해결
2. hanoi 함수는 (n: 원판 개수, from: 출발 지점, to: 도착 지점, via: 경유지)
3. 원반이 3번째에 가기 위해서는 가장 큰 원반이 3번에 나머지 n-1개의 원반이 2번에 위치해야 된다
4. 다시 n-1개의 원반이 2번에 위치하기 위해서는 n-1개의 원반 중 가장 큰 원반이 2번에, 나머지(n-2)가 3번에 위치해야 된다
5. 위와 같이 2번, 3번을 번갈아가며 원반을 쌓기 때문에 재귀를 사용
</br>
</br>
</br>
- [[PGS] 혼자 놀기의 달인 / Lv. …

litae / 65 ~ 66주차 / 3문제

---

src/weekly66/den/programmers/혼자놀기의달인.js

- 출처 : [programmers - Lv.2](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
> Example 1

Den / 66주차 / 1문제

---

src/weekly67/litae/programmers/N-Queen.ts
src/weekly67/litae/programmers/시소 짝궁.ts

- [[PGS] 시소 짝궁](https://school.programmers.co.kr/learn/courses/30/lessons/152996)
> Example 1
```
weights: [100, 180, 360, 100, 270]
result: 4
```
1. store는 무게와 개수를 key와 value로 담는 객체
2. 무게가 담긴 배열 weights를 오름차순으로 정렬
3. 해당 무게와 비율을 곱한 값이 store에 있는지 여부를 확인하고, 값이 있는 경우 해당 비율의 개수를 정답에 +
4. 해당 무게가 store에 없는 경우 새로운 객체를 만들어 store에 생성(value =1), 있는 경우 해당 value에 + 1
</br>
</br>
</br>
- [[PGS] N-Queen](https://school.programmers.co.kr/learn/courses/30/lessons/12952)
> Example 1
```
n: 4
result: 2
```
1. DFS를 통해 Queen을 놓을 수 있는 모든 경우의 수를 탐색
5. isPossible 함수는 board, col, row를 받아 해당 위치에 Queen을 놓을 수 있는지 여부를 확인하는 함수
6. dfs는 Queen을 놓을 수 있는 모든 경우의 수를 재귀로 탐색
7. 체스판에 놓은 퀸의 개수(col)가 체스판의 길이(n)와 같은 경우 Queen을 놓을 수 있는 경우의 수(answer)를 + 1

litae / 67주차 / 2문제

---

src/weekly67/nanii/programmers/N-Queen.js
src/weekly67/nanii/programmers/시소짝꿍.js

> Example
n | result
-- | --
4 | 2
- 주어진 체스판에 n개의 퀸을 놓고, 서로 공격할 수 없으려면 각 행에 퀸은 1개씩만 존재할 수 있습니다.
- 해당 조건을 만족하기 위해서 row를 기준으로 dfs를 실행해야됩니다.
- 0번째 행부터 순회하면서 퀸을 놓을 수 있는지 없는지 확인합니다.
- 놓을 수 있는 조건 : 같은행, 같은열, 대각선에 퀸이 없을 때 입니다.
- 놓을 수 있으면 queens 배열에 해당 [행, 열]에 대한 정보를 저장하여 재귀를 돌고
- 재귀를 다 돌았으면 queens 배열에서 빼고 다음 행으로 넘어갑니다.
- 이렇게 재귀를 순회하면서 결과를 반환합니다.
---
> Example
weights | result
-- | --
[100,180,360,100,270] | 4
- 주어진 무게를 순회하면서, 해당 무게에 대한 중심 거리를 곱한 값이 존재하는 지 확인하는 문제입니다.
- 기준이 되는 무게 * (2, 3, 4) = 타겟이 되는 무게 * (2, 3, 4)로 같은 값이 있는지 확인하는 과정에서
기준이 되는 무게에 * (1, 3/2, 2, 4/3) 을 곱한 값이 존재하는지 확인하는 과정과 동일하기에 비율을 곱하여 짝꿍 가능 여부를 판단하였습니다.
- 주어진 배열을 내림차순으로 정렬한뒤 각 자리에서 나올 수 있는 비율을 곱합니다.
- 이때 현재 무게를 Map객체에 Key로 저장하여 곱한 비율이 존재할 경우 짝꿍이 될 수 있는 경우이므로 경우의 수를 더하여 정답을 반환합니다.

Nanii / 67주차 / 1.5문제

---

src/weekly68/litae/programmers/리코쳇 로봇.ts
src/weekly68/litae/programmers/혼자서 하는 틱택토.ts

- [[PGS] 리코쳇 로봇 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/169199)
> Example 1
```
board: ["...D..R", ".D.G...", "....D.D", "D....D.", "..D...."]
result: 7
```
> Example 2
```
board: [".D.R", "....", ".G..", "...D"]
result: -1
```
</br>
</br>
</br>
- [[PGS] 혼자서 하는 틱택토 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/160585)
> Example 1
```
board: ["O.X", ".O.", "..X"]
result: 1
```
> Example 2
```
board: ["OOO", "...", "XXX"]
result: 0
```
> Example 3
```
board: ["...", ".X.", "..."]
result: 0
```
> Example 4
```
board: ["...", "...", "..."]
result: 1
```

litae / 68주차 / 2문제

---

src/weekly68/poco/programmers/리코쳇 로봇.js
src/weekly68/poco/programmers/혼자서 하는 틱택토.js

- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/160585))
board : 3x3 크기의 게임판
주어진 board판이 규칙을 지켜서 틱택토를 진행했을 때 나올 수 있는 게임 상황이면 1을
아니라면 0을 반환하는 문제
틱택토가 진행된 board가 매개변수로 주어질 때, 다음 규칙을 어겨서 틱택토가 진행되었는지 확인하는 문제
틱택토에서 "O"는 선공, "X"는 후공이다.
다음은 틱택토 규칙을 어기는 경우의 예시이다.
만약 "O"를 표시할 차례인데 "X"를 표시하거나 반대로 "X"를 표시할 차례인데 "O"를 표시한다.
또는 선공이나 후공이 승리해서 게임이 종료되었음에도 그 게임을 진행한다.
---
- 출처 : ([링크](https://school.programmers.co.kr/learn/courses/30/lessons/169199))
board : 게임판의 상태를 나타내는 문자엷 배열
말이 목표위치에 도달하는데 최소 몇 번 이동해야 하는지 return
말의 움직임은 상, 하, 좌, 우 4방향 중 하나를 선택해서 게임판 위의 장애물이나
맨 끝에 부딪힐 때까지 미끄러져 이동하는 것을 한 번의 이동으로 친다.
"."은 빈 공간을, "R"은 로봇의 처음 위치를, "D"는 장애물의 위치를, "G"는 목표지점을 나타낸다.
말이 목표위치에 도달하는데 최소 몇 번 이동해야 하는지 반환하는 문제다.
만약 목표위치에 도달을 할 수 없다면 -1을 반환하다.
bfs를 활용하여 문제를 해결했다.
먼저 board를 가지고 2차원 배열로 map을 만들고 …

Poco / 68주차 / 2문제

---

src/weekly69/litae/programmers/롤케이크 자르기.ts

- [[PGS] 롤케이크 자르기 / Lv. 2](https://school.programmers.co.kr/learn/courses/30/lessons/132265)
> Example 1
```
topping: [1, 2, 1, 3, 1, 4, 1, 2]
result: 2
```
> Example 2
```
topping: [1, 2, 3, 1, 4]
result: 0
```

litae / 69주차 / 1문제
